"use client";

import * as React from 'react';
import { CalendarClock, CheckCircle2, ChevronDown, MessageSquareText, Target, UserRound } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import type { PerformanceWorkspaceData } from '@/lib/performance/performance-contracts';

const history = [
  ['JUN','25','Q2 review & goal check-in','Q2 results, key wins, and Q3 priorities'],
  ['APR','23','Monthly check-in','Pipeline, key deals, and team updates'],
  ['MAR','26','Q1 review & planning','Q1 results and Q2 plan'],
] as const;

export function CheckInsTimelineWorkspace({ data, onSchedule, onStart }: { data: PerformanceWorkspaceData; onSchedule: () => void; onStart: (row: Record<string, unknown>) => void }) {
  const [open, setOpen] = React.useState(false);
  const [agenda, setAgenda] = React.useState(1);
  const upcoming = data.checkIns.find(item => !['completed','cancelled'].includes(String(item.status))) || { id: 'example-upcoming', type: 'one_on_one', status: 'scheduled' };
  return <div className="min-h-[620px]"><div className="flex items-start justify-between border-b border-border px-6 py-4"><div><h2 className="font-bold">Check-ins and one-on-one meetings</h2><p className="mt-1 text-sm text-muted-foreground">Your ongoing conversation and progress over time.</p></div><Button className="bg-blue-600 text-white hover:bg-blue-500" onClick={onSchedule}>Schedule check-in</Button></div><div className="grid xl:grid-cols-[minmax(0,1fr)_230px]"><main className="p-6"><div className="border border-blue-700 bg-blue-950/20 px-4 py-3 text-xs text-blue-300">Click any check-in or the Prepare button to open the meeting workspace.</div><p className="mt-5 text-xs font-bold text-muted-foreground">Upcoming</p><button type="button" className="mt-3 grid w-full grid-cols-[68px_minmax(0,1fr)_100px] items-center border border-blue-600 bg-slate-900/40 text-left" onClick={()=>setOpen(true)}><DateCell month="AUG" day="20" /><div className="px-4"><p className="text-xs text-blue-400">One-on-one <span className="mx-2 text-emerald-400">• Upcoming</span></p><p className="mt-1 text-lg font-bold">One-on-one</p><p className="mt-1 text-xs text-muted-foreground">Thu, Aug 20, 2026 • 10:00–10:45 AM (45m)</p><p className="mt-1 text-xs text-muted-foreground">Focus: Q3 progress, pipeline execution, and development</p></div><Button className="mr-4 bg-blue-600 text-white" onClick={event=>{event.stopPropagation();setOpen(true)}}>Prepare</Button></button><p className="mt-6 text-xs font-bold text-muted-foreground">Past</p><div className="mt-3 space-y-2 border-l border-slate-700 pl-5">{history.map(([month,day,title,focus])=><button key={title} type="button" className="relative grid w-full grid-cols-[70px_minmax(0,1fr)_100px] items-center border border-border px-4 py-4 text-left hover:bg-slate-900/40" onClick={()=>setOpen(true)}><span className="absolute -left-[26px] h-2.5 w-2.5 rounded-full border-2 border-slate-500 bg-background" /><DateCell month={month} day={day} compact /><div><p className="text-xs text-blue-400">One-on-one <span className="text-emerald-400">• Completed</span></p><p className="mt-1 font-bold">{title}</p><p className="mt-1 text-xs text-muted-foreground">Focus: {focus}</p></div><span className="text-xs text-emerald-400"><CheckCircle2 className="mr-1 inline h-4 w-4" />Completed</span></button>)}</div></main><SideSummary /></div><MeetingWorkspace open={open} onOpenChange={setOpen} activeAgenda={agenda} onAgendaChange={setAgenda} onStart={()=>onStart(upcoming)} /></div>;
}

function DateCell({ month, day, compact=false }: { month: string; day: string; compact?: boolean }) { return <div className={compact?'text-left':'border-r border-border p-4 text-center'}><span className="block text-xs text-muted-foreground">{month}</span><strong className="text-2xl">{day}</strong><span className="block text-xs text-muted-foreground">2026</span></div>; }

function SideSummary(){return <aside className="border-l border-border p-5"><h3 className="text-sm font-bold">Check-in cadence</h3><p className="mt-2 font-semibold">One-on-one</p><p className="text-sm text-muted-foreground">Every 4 weeks</p><div className="my-5 border-t border-border"/><div className="flex justify-between"><h3 className="text-sm font-bold">Open actions</h3><span className="rounded-full bg-blue-950 px-2 text-xs text-blue-300">3</span></div>{['Share Q3 pipeline update','Complete self review','Manager prep notes'].map((item,i)=><div key={item} className="mt-4 flex gap-2 text-xs"><span className="mt-0.5 h-4 w-4 rounded-full border border-blue-400"/><p>{item}<span className="mt-1 block text-muted-foreground">Due Aug {18+i}, 2026</span></p></div>)}<div className="my-5 border-t border-border"/><h3 className="text-sm font-bold">Next talking points</h3><ul className="mt-3 list-disc space-y-2 pl-4 text-xs text-muted-foreground"><li>Q3 pipeline and key deals</li><li>Win themes and lessons learned</li><li>Development and growth</li><li>Anything getting in the way?</li></ul></aside>}

function MeetingWorkspace({open,onOpenChange,activeAgenda,onAgendaChange,onStart}:{open:boolean;onOpenChange:(value:boolean)=>void;activeAgenda:number;onAgendaChange:(value:number)=>void;onStart:()=>void}){
 const items=['Welcome & check-in','Q3 progress & pipeline','Wins & challenges','Development & growth','Feedback & alignment','Action items & next steps'];
 return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent side="right" className="w-[430px] max-w-[96vw] overflow-y-auto border-l border-border bg-background p-0 sm:max-w-[430px]"><SheetHeader className="border-b border-border p-5 text-left"><SheetTitle>One-on-one • Aug 20, 2026</SheetTitle><SheetDescription>Autosaved just now • Preparation 65%</SheetDescription></SheetHeader><div className="border-b border-border px-5 py-4 text-xs text-muted-foreground"><p><CalendarClock className="mr-2 inline h-4 w-4"/>Thu, Aug 20, 2026 • 10:00–10:45 AM</p><p className="mt-2"><UserRound className="mr-2 inline h-4 w-4"/>Ben Thompson (Manager) • Anucha Prom</p></div><div className="border-b border-border px-5 pt-3"><span className="inline-block border-b-2 border-blue-500 px-2 pb-3 text-sm font-semibold">Workspace</span><span className="px-5 pb-3 text-sm text-muted-foreground">Summary (0)</span><span className="text-sm text-muted-foreground">Private notes</span></div><section className="p-4"><div className="flex justify-between"><h3 className="font-bold">Agenda</h3><button className="text-xs text-blue-400">Reorder</button></div><div className="mt-3 space-y-2">{items.map((item,index)=><AgendaItem key={item} index={index} item={item} expanded={activeAgenda===index} onClick={()=>onAgendaChange(index)} />)}</div></section><section className="border-t border-border p-4"><div className="flex justify-between"><h3 className="text-sm font-bold">Feedback prompts</h3><button className="text-xs text-blue-400">View all</button></div>{['What are you most proud of this quarter?','What support or resources would help you most?'].map(text=><p key={text} className="mt-3 border border-border px-3 py-2 text-xs text-muted-foreground"><MessageSquareText className="mr-2 inline h-4 w-4"/>{text}</p>)}</section><section className="border-t border-border p-4"><div className="flex justify-between"><h3 className="text-sm font-bold">Action items</h3><button className="text-xs text-blue-400">Add action</button></div><p className="mt-3 border border-border px-3 py-2 text-xs">○ Share Q3 pipeline update <span className="float-right text-muted-foreground">Due Aug 18</span></p></section><div className="sticky bottom-0 border-t border-border bg-background p-4"><Button className="w-full bg-blue-600 text-white" onClick={onStart}>Start check-in</Button></div></SheetContent></Sheet>
}

function AgendaItem({index,item,expanded,onClick}:{index:number;item:string;expanded:boolean;onClick:()=>void}){const count=[3,4,2,3,3,2][index];return <div className={expanded?'border border-blue-600':'border border-border'}><button type="button" className="flex w-full items-center gap-3 px-3 py-2 text-left" onClick={onClick}><span className="grid h-5 w-5 place-items-center rounded-full border border-border text-xs">{index+1}</span><span className="flex-1 text-sm font-semibold">{item}</span><span className="text-xs text-muted-foreground">{count} talking points</span><ChevronDown className={`h-4 w-4 ${expanded?'rotate-180':''}`}/></button>{expanded&&<div className="border-t border-border p-3"><Button variant="outline" size="sm" className="w-full justify-start text-blue-400">+ Add talking point</Button><p className="mt-3 text-xs font-bold">Talking points ({count})</p><ul className="mt-2 list-disc space-y-1 pl-4 text-xs text-muted-foreground"><li>Pipeline coverage vs target</li><li>Top deals update</li><li>Risks and blockers</li><li>Forecast confidence</li></ul><div className="mt-4 border-t border-border pt-3"><div className="flex justify-between"><p className="text-xs font-bold">Participant notes</p><button className="text-xs text-blue-400">Add note</button></div><p className="mt-3 text-xs"><strong>Anucha Prom</strong> <span className="text-muted-foreground">• Aug 13</span></p><p className="mt-1 text-xs text-muted-foreground">Pushed ACME renewal and Greenfield expansion this month.</p><p className="mt-3 text-xs"><strong>Ben Thompson</strong> <span className="text-muted-foreground">• Aug 13</span></p><p className="mt-1 text-xs text-muted-foreground">Great momentum. Let’s align on forecast risk.</p></div><div className="mt-4 border-t border-border pt-3"><p className="text-xs font-bold">Linked goals (2)</p>{['Grow strategic pipeline by 30%','Expand customer base in APAC'].map((goal,i)=><div key={goal} className="mt-3 flex gap-2 text-xs"><Target className="h-4 w-4 text-blue-400"/><span className="flex-1">{goal}</span><span>{[60,40][i]}%</span></div>)}</div></div>}</div>}
