import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';

// Force dynamic rendering since we use headers() in getServerSession
export const dynamic = 'force-dynamic';

export async function GET(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Define available fields for each entity type
    const availableFields = {
      candidate: [
        'id',
        'name',
        'email',
        'phone',
        'status',
        'source',
        'recruiterId',
        'gradeId',
        'positionId',
        'createdAt',
        'updatedAt',
        'resumeUrl',
        'linkedinUrl',
        'experience',
        'education',
        'skills',
        'notes',
        'isActive',
        'lastContactDate',
        'expectedSalary',
        'currentSalary',
        'noticePeriod',
        'location',
        'availability',
        'preferredWorkType',
        'languages',
        'certifications',
        'references',
        'interviewNotes',
        'assessmentScore',
        'feedback',
        'rejectionReason',
        'offerStatus',
        'startDate',
        'onboardingStatus'
      ],
      position: [
        'id',
        'title',
        'description',
        'requirements',
        'responsibilities',
        'department',
        'location',
        'type',
        'status',
        'recruiterId',
        'gradeId',
        'headcountId',
        'createdAt',
        'updatedAt',
        'isActive',
        'salaryRange',
        'experienceLevel',
        'educationRequired',
        'skillsRequired',
        'benefits',
        'workType',
        'contractType',
        'startDate',
        'endDate',
        'priority',
        'urgency',
        'budget',
        'approvalStatus',
        'hiringManager',
        'teamSize',
        'reportingTo',
        'travelRequired',
        'relocation',
        'visaSponsorship',
        'remoteWork',
        'interviewProcess',
        'timeline',
        'successMetrics',
        'risks',
        'dependencies',
        'stakeholders',
        'communicationPlan',
        'onboardingPlan',
        'performanceMetrics',
        'careerPath',
        'growthOpportunities'
      ],
      headcount: [
        'id',
        'title',
        'department',
        'budget',
        'status',
        'createdAt',
        'updatedAt',
        'isActive',
        'fiscalYear',
        'quarter',
        'month',
        'requestedBy',
        'approvedBy',
        'approvalDate',
        'priority',
        'urgency',
        'businessCase',
        'impact',
        'risks',
        'alternatives',
        'timeline',
        'successMetrics',
        'dependencies',
        'stakeholders',
        'communicationPlan',
        'onboardingPlan',
        'performanceMetrics',
        'careerPath',
        'growthOpportunities',
        'budgetAllocation',
        'costCenter',
        'profitCenter',
        'revenueImpact',
        'efficiencyGains',
        'qualityImprovements',
        'customerImpact',
        'employeeImpact',
        'complianceImpact',
        'technologyImpact',
        'processImpact',
        'trainingRequirements',
        'infrastructureNeeds',
        'vendorRequirements',
        'contractRequirements',
        'legalRequirements',
        'regulatoryRequirements',
        'securityRequirements',
        'privacyRequirements',
        'accessibilityRequirements',
        'sustainabilityImpact',
        'diversityImpact',
        'inclusionImpact',
        'equityImpact',
        'belongingImpact',
        'wellnessImpact',
        'safetyImpact',
        'healthImpact',
        'environmentalImpact',
        'socialImpact',
        'governanceImpact',
        'riskManagement',
        'complianceManagement',
        'qualityManagement',
        'projectManagement',
        'changeManagement',
        'stakeholderManagement',
        'communicationManagement',
        'resourceManagement',
        'budgetManagement',
        'timelineManagement',
        'scopeManagement',
        'qualityManagement',
        'riskManagement',
        'procurementManagement',
        'integrationManagement',
        'closureManagement'
      ]
    };

    return NextResponse.json(availableFields);
  } catch (error) {
    console.error('Error fetching available fields:', error);
    return NextResponse.json(
      { error: 'Failed to fetch available fields' },
      { status: 500 }
    );
  }
}
