import { getSystemSetting } from '@/lib/systemSettings';

export type AiProvider = 'gemini' | 'openai';

export interface AiModelInfo {
  name: string;
  displayName: string;
  description?: string;
  supportedGenerationMethods?: string[];
}

const MODEL_NAME_PATTERN = /^[a-zA-Z0-9._-]+$/;

const modelCache = new Map<string, { timestamp: number; models: AiModelInfo[] }>();
const CACHE_DURATION = 5 * 60 * 1000;

export async function getSelectedAiProvider(): Promise<AiProvider> {
  const selectedProvider = await getSystemSetting('aiProviderSelection');
  return selectedProvider === 'openai' ? 'openai' : 'gemini';
}

export function getProviderKeyPrefix(provider: AiProvider): string {
  return provider === 'openai' ? 'openaiApiKey' : 'geminiApiKey';
}

export function getProviderLabel(provider: AiProvider): string {
  return provider === 'openai' ? 'OpenAI' : 'Google Gemini';
}

export function getProviderModelSettingKey(provider: AiProvider): string {
  return provider === 'openai' ? 'openaiModelSelection' : 'geminiModelSelection';
}

export function getDefaultModelFallback(provider: AiProvider): string {
  return provider === 'openai' ? 'gpt-4o-mini' : 'gemini-1.5-flash';
}

export function normalizeModelName(
  provider: AiProvider,
  modelName: string | undefined | null,
  availableModels?: Array<{ name: string }>
): string {
  const fallback = getDefaultModelFallback(provider);
  if (!modelName) {
    return fallback;
  }

  const normalized = modelName.startsWith('models/')
    ? modelName.replace(/^models\//, '')
    : modelName;

  if (!MODEL_NAME_PATTERN.test(normalized) || normalized.includes('..') || normalized.includes('/') || normalized.includes('\\')) {
    return fallback;
  }

  if (availableModels?.length) {
    const matched = availableModels.find((model) => {
      const candidate = model.name.startsWith('models/')
        ? model.name.replace(/^models\//, '')
        : model.name;
      return candidate === normalized;
    });

    if (matched) {
      return normalized;
    }

    return availableModels[0].name.startsWith('models/')
      ? availableModels[0].name.replace(/^models\//, '')
      : availableModels[0].name;
  }

  return normalized;
}

export async function getAvailableModels(provider: AiProvider, apiKey: string): Promise<AiModelInfo[]> {
  const cacheKey = `${provider}:${apiKey.slice(0, 12)}`;
  const cached = modelCache.get(cacheKey);
  if (cached && Date.now() - cached.timestamp < CACHE_DURATION) {
    return cached.models;
  }

  const models = provider === 'openai'
    ? await fetchOpenAiModels(apiKey)
    : await fetchGeminiModels(apiKey);

  modelCache.set(cacheKey, {
    timestamp: Date.now(),
    models,
  });

  return models;
}

export async function getDefaultModelName(provider: AiProvider, apiKey: string): Promise<string> {
  try {
    const models = await getAvailableModels(provider, apiKey);
    if (models.length > 0) {
      return normalizeModelName(provider, models[0].name, models);
    }
  } catch (error) {
    console.error(`[AI] Failed to get default ${provider} model:`, error);
  }

  return getDefaultModelFallback(provider);
}

export async function generateTextWithProvider(
  provider: AiProvider,
  apiKey: string,
  model: string,
  prompt: string,
  options?: {
    temperature?: number;
    topK?: number;
    topP?: number;
    maxOutputTokens?: number;
  }
): Promise<string> {
  if (provider === 'openai') {
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model,
        messages: [{ role: 'user', content: prompt }],
        temperature: options?.temperature ?? 0.7,
        top_p: options?.topP,
        max_tokens: options?.maxOutputTokens,
      }),
    });

    const data = await response.json().catch(() => ({}));

    if (!response.ok) {
      throw new Error(`OpenAI API error: ${response.status} ${response.statusText} - ${JSON.stringify(data)}`);
    }

    if (data.error) {
      throw new Error(`OpenAI API error: ${data.error.message || JSON.stringify(data.error)}`);
    }

    const content = data.choices?.[0]?.message?.content;
    if (typeof content === 'string' && content.trim()) {
      return content;
    }

    if (Array.isArray(content)) {
      const text = content
        .map((item: any) => {
          if (typeof item?.text?.value === 'string') return item.text.value;
          if (typeof item?.text === 'string') return item.text;
          return '';
        })
        .filter(Boolean)
        .join('\n');

      if (text.trim()) {
        return text;
      }
    }

    throw new Error('No content generated by OpenAI');
  }

  const normalizedModel = normalizeModelName(provider, model);
  const response = await fetch(`https://generativelanguage.googleapis.com/v1/models/${normalizedModel}:generateContent`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'X-goog-api-key': apiKey,
    },
    body: JSON.stringify({
      contents: [
        {
          role: 'user',
          parts: [{ text: prompt }],
        },
      ],
      generationConfig: {
        temperature: options?.temperature ?? 0.7,
        topK: options?.topK,
        topP: options?.topP,
        maxOutputTokens: options?.maxOutputTokens,
      },
    }),
  });

  const data = await response.json().catch(() => ({}));

  if (!response.ok) {
    throw new Error(`Gemini API error: ${response.status} ${response.statusText} - ${JSON.stringify(data)}`);
  }

  if (data.error) {
    throw new Error(`Gemini API error: ${data.error.message || JSON.stringify(data.error)}`);
  }

  const text = data.candidates?.[0]?.content?.parts
    ?.map((part: any) => part?.text || '')
    .filter(Boolean)
    .join('\n');

  if (!text?.trim()) {
    throw new Error('No content generated by Gemini');
  }

  return text;
}

async function fetchGeminiModels(apiKey: string): Promise<AiModelInfo[]> {
  try {
    const response = await fetch('https://generativelanguage.googleapis.com/v1/models', {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
        'X-goog-api-key': apiKey,
      },
    });

    if (!response.ok) {
      return getFallbackModels('gemini');
    }

    const data = await response.json();
    const models = (data.models || [])
      .filter((model: any) =>
        model.supportedGenerationMethods?.includes('generateContent') &&
        String(model.name || '').includes('gemini')
      )
      .map((model: any) => ({
        name: normalizeModelName('gemini', model.name),
        displayName: model.displayName || normalizeModelName('gemini', model.name),
        description: model.description || '',
        supportedGenerationMethods: model.supportedGenerationMethods || [],
      }))
      .sort((a: AiModelInfo, b: AiModelInfo) => a.displayName.localeCompare(b.displayName));

    return models.length ? models : getFallbackModels('gemini');
  } catch (error) {
    console.error('[AI] Failed to fetch Gemini models:', error);
    return getFallbackModels('gemini');
  }
}

async function fetchOpenAiModels(apiKey: string): Promise<AiModelInfo[]> {
  try {
    const response = await fetch('https://api.openai.com/v1/models', {
      method: 'GET',
      headers: {
        Authorization: `Bearer ${apiKey}`,
      },
    });

    if (!response.ok) {
      return getFallbackModels('openai');
    }

    const data = await response.json();
    const preferredModels = (data.data || [])
      .map((model: any) => String(model.id || ''))
      .filter((id: string) =>
        /^(gpt-|o[134]|chatgpt-)/.test(id) &&
        !/-(audio|realtime|transcribe|vision-preview|search|instruct)/.test(id)
      )
      .sort(sortOpenAiModels);

    const uniqueModels = Array.from(new Set(preferredModels)) as string[];
    if (!uniqueModels.length) {
      return getFallbackModels('openai');
    }

    return uniqueModels.map((name) => ({
      name,
      displayName: name,
      description: 'OpenAI text generation model',
      supportedGenerationMethods: ['chat.completions'],
    }));
  } catch (error) {
    console.error('[AI] Failed to fetch OpenAI models:', error);
    return getFallbackModels('openai');
  }
}

function getFallbackModels(provider: AiProvider): AiModelInfo[] {
  if (provider === 'openai') {
    return [
      { name: 'gpt-4o-mini', displayName: 'gpt-4o-mini', description: 'Fast and cost-efficient OpenAI model', supportedGenerationMethods: ['chat.completions'] },
      { name: 'gpt-4o', displayName: 'gpt-4o', description: 'General-purpose OpenAI model', supportedGenerationMethods: ['chat.completions'] },
      { name: 'gpt-4.1-mini', displayName: 'gpt-4.1-mini', description: 'Compact GPT-4.1 model', supportedGenerationMethods: ['chat.completions'] },
      { name: 'gpt-4.1', displayName: 'gpt-4.1', description: 'Advanced GPT-4.1 model', supportedGenerationMethods: ['chat.completions'] },
    ];
  }

  return [
    { name: 'gemini-1.5-flash', displayName: 'Gemini 1.5 Flash', description: 'Fast Gemini model', supportedGenerationMethods: ['generateContent'] },
    { name: 'gemini-1.5-pro', displayName: 'Gemini 1.5 Pro', description: 'Capable Gemini model', supportedGenerationMethods: ['generateContent'] },
    { name: 'gemini-2.0-flash-exp', displayName: 'Gemini 2.0 Flash Experimental', description: 'Experimental Gemini model', supportedGenerationMethods: ['generateContent'] },
  ];
}

function sortOpenAiModels(a: string, b: string): number {
  const preferredOrder = ['gpt-4o-mini', 'gpt-4o', 'gpt-4.1-mini', 'gpt-4.1', 'o4-mini', 'o3'];
  const indexA = preferredOrder.indexOf(a);
  const indexB = preferredOrder.indexOf(b);

  if (indexA !== -1 || indexB !== -1) {
    if (indexA === -1) return 1;
    if (indexB === -1) return -1;
    return indexA - indexB;
  }

  return a.localeCompare(b);
}
