import { readJsonObject } from './response-json';
import type { AiGenerationOptions, AiInlineFilePart, AiModelInfo } from './aiProvider-types';
import { getFallbackModels, normalizeModelName } from './aiProvider-settings';
import {
  getAiApiErrorMessage,
  getArrayProperty,
  getRecordProperty,
  getStringArrayProperty,
  getStringProperty,
} from './aiProvider-object-utils';

function getGeminiGeneratedText(data: unknown) {
  const candidate = getArrayProperty(data, 'candidates')[0];
  const content = getRecordProperty(candidate, 'content');
  const parts = getArrayProperty(content, 'parts');

  return parts
    .map(part => getStringProperty(part, 'text') || '')
    .filter(Boolean)
    .join('\n');
}

function normalizeGeminiModelInfo(model: unknown): AiModelInfo | null {
  const supportedGenerationMethods = getStringArrayProperty(model, 'supportedGenerationMethods');
  const rawName = getStringProperty(model, 'name') || '';

  if (!supportedGenerationMethods.includes('generateContent') || !rawName.includes('gemini')) {
    return null;
  }

  const name = normalizeModelName('gemini', rawName);
  return {
    name,
    displayName: getStringProperty(model, 'displayName') || name,
    description: getStringProperty(model, 'description') || '',
    supportedGenerationMethods,
  };
}

export async function generateGeminiText(
  apiKey: string,
  model: string,
  prompt: string,
  options?: AiGenerationOptions
) {
  const normalizedModel = normalizeModelName('gemini', model);
  const response = await fetch(`https://generativelanguage.googleapis.com/v1/models/${normalizedModel}:generateContent`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'X-goog-api-key': apiKey,
    },
    body: JSON.stringify({
      contents: [
        {
          role: 'user',
          parts: [{ text: prompt }],
        },
      ],
      generationConfig: {
        temperature: options?.temperature ?? 0.7,
        topK: options?.topK,
        topP: options?.topP,
        maxOutputTokens: options?.maxOutputTokens,
      },
    }),
  });

  const data = await readJsonObject(response);

  if (!response.ok) {
    throw new Error(`Gemini API error: ${response.status} ${response.statusText} - ${JSON.stringify(data)}`);
  }

  if (getRecordProperty(data, 'error')) {
    throw new Error(`Gemini API error: ${getAiApiErrorMessage(data)}`);
  }

  const text = getGeminiGeneratedText(data);

  if (!text?.trim()) {
    throw new Error('No content generated by Gemini');
  }

  return text;
}

export async function generateGeminiTextWithFiles(
  apiKey: string,
  model: string,
  prompt: string,
  files: AiInlineFilePart[],
  options?: AiGenerationOptions
) {
  const normalizedModel = normalizeModelName('gemini', model);
  const response = await fetch(`https://generativelanguage.googleapis.com/v1/models/${normalizedModel}:generateContent`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'X-goog-api-key': apiKey,
    },
    body: JSON.stringify({
      contents: [
        {
          role: 'user',
          parts: [
            { text: prompt },
            ...files.map(file => ({
              inline_data: {
                mime_type: file.mimeType,
                data: file.dataBase64,
              },
            })),
          ],
        },
      ],
      generationConfig: {
        temperature: options?.temperature ?? 0.7,
        topK: options?.topK,
        topP: options?.topP,
        maxOutputTokens: options?.maxOutputTokens,
      },
    }),
  });

  const data = await readJsonObject(response);

  if (!response.ok) {
    throw new Error(`Gemini API error: ${response.status} ${response.statusText} - ${JSON.stringify(data)}`);
  }

  if (getRecordProperty(data, 'error')) {
    throw new Error(`Gemini API error: ${getAiApiErrorMessage(data)}`);
  }

  const text = getGeminiGeneratedText(data);

  if (!text?.trim()) {
    throw new Error('No content generated by Gemini');
  }

  return text;
}

export async function fetchGeminiModels(apiKey: string): Promise<AiModelInfo[]> {
  try {
    const response = await fetch('https://generativelanguage.googleapis.com/v1/models', {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
        'X-goog-api-key': apiKey,
      },
    });

    if (!response.ok) {
      return getFallbackModels('gemini');
    }

    const data = await readJsonObject(response);
    const models = getArrayProperty(data, 'models')
      .map(normalizeGeminiModelInfo)
      .filter((model): model is AiModelInfo => model !== null)
      .sort((a: AiModelInfo, b: AiModelInfo) => a.displayName.localeCompare(b.displayName));

    return models.length ? models : getFallbackModels('gemini');
  } catch (error) {
    console.error('[AI] Failed to fetch Gemini models:', error);
    return getFallbackModels('gemini');
  }
}
