import { readJsonObject } from './response-json';
import type { AiGenerationOptions, AiModelInfo } from './aiProvider-types';
import { getFallbackModels } from './aiProvider-settings';
import {
  getAiApiErrorMessage,
  getRecordProperty,
} from './aiProvider-object-utils';
import { buildOpenAiModelList } from './aiProvider-openai-model-utils';
import {
  getOpenAiGeneratedText,
  shouldRetryOpenAiWithAlternateTokenField,
} from './aiProvider-openai-response-utils';

function buildOpenAiChatRequestBody(
  model: string,
  prompt: string,
  options?: AiGenerationOptions,
  tokenField: 'max_completion_tokens' | 'max_tokens' = 'max_completion_tokens'
): Record<string, unknown> {
  const requestBody: Record<string, unknown> = {
    model,
    messages: [{ role: 'user', content: prompt }],
  };

  if (typeof options?.temperature === 'number') {
    requestBody.temperature = options.temperature;
  }

  if (typeof options?.topP === 'number') {
    requestBody.top_p = options.topP;
  }

  if (typeof options?.maxOutputTokens === 'number') {
    requestBody[tokenField] = options.maxOutputTokens;
  }

  return requestBody;
}

async function callOpenAiChatCompletions(
  apiKey: string,
  requestBody: Record<string, unknown>
) {
  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify(requestBody),
  });

  const data = await readJsonObject(response);
  return { response, data };
}

export async function generateOpenAiText(
  apiKey: string,
  model: string,
  prompt: string,
  options?: AiGenerationOptions
) {
  let { response, data } = await callOpenAiChatCompletions(
    apiKey,
    buildOpenAiChatRequestBody(model, prompt, options, 'max_completion_tokens')
  );

  if (!response.ok && shouldRetryOpenAiWithAlternateTokenField(data)) {
    ({ response, data } = await callOpenAiChatCompletions(
      apiKey,
      buildOpenAiChatRequestBody(model, prompt, options, 'max_tokens')
    ));
  }

  if (!response.ok) {
    throw new Error(`OpenAI API error: ${response.status} ${response.statusText} - ${JSON.stringify(data)}`);
  }

  if (getRecordProperty(data, 'error')) {
    throw new Error(`OpenAI API error: ${getAiApiErrorMessage(data)}`);
  }

  const text = getOpenAiGeneratedText(data);
  if (text.trim()) {
    return text;
  }

  throw new Error('No content generated by OpenAI');
}

export async function fetchOpenAiModels(apiKey: string): Promise<AiModelInfo[]> {
  try {
    const response = await fetch('https://api.openai.com/v1/models', {
      method: 'GET',
      headers: {
        Authorization: `Bearer ${apiKey}`,
      },
    });

    if (!response.ok) {
      return getFallbackModels('openai');
    }

    const models = buildOpenAiModelList(await readJsonObject(response));
    if (!models.length) {
      return getFallbackModels('openai');
    }

    return models;
  } catch (error) {
    console.error('[AI] Failed to fetch OpenAI models:', error);
    return getFallbackModels('openai');
  }
}
