import { readJsonObject } from './response-json';
import type { AiGenerationOptions, AiModelInfo } from './aiProvider-types';
import { getFallbackModels } from './aiProvider-settings';
import {
  getAiApiErrorMessage,
  getArrayProperty,
  getRecordProperty,
  getStringProperty,
} from './aiProvider-object-utils';
import { getOpenAiGeneratedText } from './aiProvider-openai-response-utils';

const DEEPSEEK_API_BASE_URL = 'https://api.deepseek.com';

function buildDeepSeekModelList(data: unknown): AiModelInfo[] {
  return Array.from(new Set(
    getArrayProperty(data, 'data')
      .map(model => getStringProperty(model, 'id') || '')
      .filter(id => id.startsWith('deepseek-'))
      .sort((a, b) => a.localeCompare(b))
  )).map(name => ({
    name,
    displayName: name,
    description: 'DeepSeek text generation model',
    supportedGenerationMethods: ['chat.completions'],
  }));
}

function buildDeepSeekChatRequestBody(
  model: string,
  prompt: string,
  options?: AiGenerationOptions,
): Record<string, unknown> {
  const requestBody: Record<string, unknown> = {
    model,
    messages: [{ role: 'user', content: prompt }],
  };

  if (typeof options?.temperature === 'number') {
    requestBody.temperature = options.temperature;
  }

  if (typeof options?.topP === 'number') {
    requestBody.top_p = options.topP;
  }

  if (typeof options?.maxOutputTokens === 'number') {
    requestBody.max_tokens = options.maxOutputTokens;
  }

  return requestBody;
}

export async function generateDeepSeekText(
  apiKey: string,
  model: string,
  prompt: string,
  options?: AiGenerationOptions,
) {
  const response = await fetch(`${DEEPSEEK_API_BASE_URL}/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify(buildDeepSeekChatRequestBody(model, prompt, options)),
  });

  const data = await readJsonObject(response);

  if (!response.ok) {
    throw new Error(`DeepSeek API error: ${response.status} ${response.statusText} - ${JSON.stringify(data)}`);
  }

  if (getRecordProperty(data, 'error')) {
    throw new Error(`DeepSeek API error: ${getAiApiErrorMessage(data)}`);
  }

  const text = getOpenAiGeneratedText(data);
  if (text.trim()) {
    return text;
  }

  throw new Error('No content generated by DeepSeek');
}

export async function fetchDeepSeekModels(apiKey: string): Promise<AiModelInfo[]> {
  try {
    const response = await fetch(`${DEEPSEEK_API_BASE_URL}/models`, {
      method: 'GET',
      headers: {
        Authorization: `Bearer ${apiKey}`,
      },
    });

    if (!response.ok) {
      return getFallbackModels('deepseek');
    }

    const models = buildDeepSeekModelList(await readJsonObject(response));

    return models.length ? models : getFallbackModels('deepseek');
  } catch (error) {
    console.error('[AI] Failed to fetch DeepSeek models:', error);
    return getFallbackModels('deepseek');
  }
}
