export type EmailTemplateAttribute = {
  key: string;
  description: string;
};

const common = {
  recipientName: 'Name of the person receiving the email',
  companyName: 'Organization name',
};

const descriptions: Record<string, string> = {
  ...common,
  applicantName: "Applicant's full name",
  ApplicantName: "Applicant's full name",
  candidateName: "Candidate's full name",
  employeeName: "Employee's full name",
  managerName: "Manager's full name",
  interviewerName: "Interviewer's full name",
  positionTitle: 'Job position title',
  jobTitle: 'Offered job title',
  applicationDate: 'Date the application was received',
  applicantProfileUrl: "Link to the applicant's profile",
  previousStatus: 'Previous application status',
  applicationStatus: 'Current application status',
  interviewDate: 'Formatted interview date',
  interviewTime: 'Formatted interview time',
  interviewLocation: 'Interview location or meeting link',
  evaluationLink: 'Link to the applicant evaluation form',
  qrCodeBase64: 'QR code image for the evaluation link',
  newInterviewDate: 'New formatted interview date',
  newInterviewTime: 'New formatted interview time',
  cancellationReason: 'Reason the interview was cancelled',
  salary: 'Offered compensation',
  startDate: 'Employment start date',
  acceptUrl: 'Link to review and accept the offer',
  offerExpiryDate: 'Date the offer expires',
  setupUrl: 'Link to set up the employee account password',
  activationExpiryDate: 'Date the account activation link expires',
  onboardingUrl: 'Link to the onboarding workspace',
  onboardingStartDate: 'Date onboarding begins',
  taskName: 'Name of the assigned task',
  taskDueDate: 'Due date of the assigned task',
  taskUrl: 'Link to view or complete the task',
  documentName: 'Name of the employee document',
  documentUrl: 'Link to view the document',
  documentExpiryDate: 'Date the document expires',
  profileUrl: 'Link to review or update the employee profile',
  missingInformation: 'Profile information that must be updated',
  surveyName: 'Name of the survey',
  surveyUrl: 'Link to complete the survey',
  surveyDeadline: 'Survey response deadline',
  leaveType: 'Type of leave requested',
  leaveStartDate: 'First day of leave',
  leaveEndDate: 'Last day of leave',
  leaveStatus: 'Current leave request status',
  leaveBalance: 'Available leave balance',
  requestedDays: 'Number of leave days requested',
  attendanceDate: 'Date of the attendance exception',
  attendanceIssue: 'Type of attendance exception',
  attendanceUrl: 'Link to review the attendance record',
  timesheetPeriod: 'Pay period covered by the timesheet',
  timesheetStatus: 'Current timesheet status',
  timesheetUrl: 'Link to view or submit the timesheet',
  schedulePeriod: 'Date range covered by the work schedule',
  scheduleUrl: 'Link to view the work schedule',
  shiftDate: 'Date of the assigned shift',
  shiftTime: 'Start and end time of the assigned shift',
  payslipPeriod: 'Pay period shown on the payslip',
  payslipUrl: 'Link to view the payslip',
  payrollInformation: 'Payroll information that is required',
  payrollProfileUrl: 'Link to update payroll information',
  reviewCycleName: 'Name of the performance review cycle',
  reviewDueDate: 'Performance review due date',
  reviewUrl: 'Link to view or complete the review',
  goalName: 'Name of the goal',
  checkinDueDate: 'Goal check-in due date',
  goalUrl: 'Link to update the goal',
  trainingName: 'Name of the course or learning path',
  trainingDueDate: 'Training completion due date',
  trainingUrl: 'Link to open the training',
  certificateUrl: 'Link to view the completion certificate',
  expenseTitle: 'Title or reference of the expense request',
  expenseAmount: 'Total expense amount',
  expenseStatus: 'Current expense request status',
  expenseUrl: 'Link to view the expense request',
  announcementTitle: 'Title of the company announcement',
  announcementContent: 'Approved announcement content',
  policyName: 'Name of the company policy',
  policyUrl: 'Link to review the policy',
  acknowledgementDueDate: 'Policy acknowledgement due date',
  lastWorkingDate: "Employee's final working date",
  exitInterviewUrl: 'Link to the exit interview or survey',
  offboardingUrl: 'Link to the offboarding workspace',
  terminationDate: 'Effective date of termination',
  verificationCode: 'One-time email verification code',
  verificationExpiry: 'Time when the verification code expires',
  unlockUrl: 'Link to unlock or recover the account',
  lockedAt: 'Date and time the account was locked',
};

const attributesByTemplate: Record<string, string[]> = {
  application_received: ['applicantName', 'positionTitle', 'applicationDate', 'companyName'],
  new_application_alert: ['recipientName', 'applicantName', 'positionTitle', 'applicationDate', 'applicantProfileUrl'],
  applicant_status_changed: ['applicantName', 'positionTitle', 'previousStatus', 'applicationStatus', 'companyName'],
  candidate_shortlisted: ['applicantName', 'positionTitle', 'companyName'],
  interview_invitation: ['ApplicantName', 'positionTitle', 'interviewDate', 'interviewTime', 'interviewLocation', 'evaluationLink', 'qrCodeBase64', 'interviewerName'],
  interview_rescheduled: ['applicantName', 'positionTitle', 'newInterviewDate', 'newInterviewTime', 'interviewLocation', 'interviewerName'],
  interview_cancelled: ['applicantName', 'positionTitle', 'interviewDate', 'interviewTime', 'cancellationReason'],
  offer_letter: ['candidateName', 'jobTitle', 'salary', 'startDate', 'acceptUrl', 'companyName'],
  offer_reminder: ['candidateName', 'jobTitle', 'offerExpiryDate', 'acceptUrl', 'companyName'],
  employee_password_setup: ['employeeName', 'setupUrl', 'activationExpiryDate', 'companyName'],
  onboarding_invitation: ['employeeName', 'onboardingStartDate', 'onboardingUrl', 'companyName'],
  onboarding_task_reminder: ['recipientName', 'employeeName', 'taskName', 'taskDueDate', 'taskUrl'],
  document_issued: ['employeeName', 'documentName', 'documentUrl', 'companyName'],
  document_expiry_reminder: ['employeeName', 'documentName', 'documentExpiryDate', 'documentUrl'],
  employee_profile_update_required: ['employeeName', 'missingInformation', 'profileUrl'],
  employee_survey_invitation: ['employeeName', 'surveyName', 'surveyDeadline', 'surveyUrl'],
  employee_survey_reminder: ['employeeName', 'surveyName', 'surveyDeadline', 'surveyUrl'],
  employee_survey_completed: ['employeeName', 'surveyName', 'companyName'],
  leave_status_changed: ['employeeName', 'leaveType', 'leaveStartDate', 'leaveEndDate', 'leaveStatus'],
  leave_balance_warning: ['employeeName', 'leaveType', 'leaveBalance', 'requestedDays'],
  attendance_exception: ['employeeName', 'attendanceDate', 'attendanceIssue', 'attendanceUrl'],
  timesheet_submission_reminder: ['employeeName', 'timesheetPeriod', 'timesheetUrl'],
  timesheet_status_changed: ['employeeName', 'timesheetPeriod', 'timesheetStatus', 'timesheetUrl'],
  shift_schedule_published: ['employeeName', 'schedulePeriod', 'scheduleUrl'],
  shift_schedule_changed: ['employeeName', 'shiftDate', 'shiftTime', 'scheduleUrl'],
  payslip_available: ['employeeName', 'payslipPeriod', 'payslipUrl', 'companyName'],
  payroll_information_required: ['employeeName', 'payrollInformation', 'payrollProfileUrl'],
  performance_review_assigned: ['recipientName', 'reviewCycleName', 'reviewDueDate', 'reviewUrl'],
  performance_review_reminder: ['recipientName', 'reviewCycleName', 'reviewDueDate', 'reviewUrl'],
  performance_review_completed: ['employeeName', 'reviewCycleName', 'reviewUrl'],
  goal_checkin_reminder: ['employeeName', 'goalName', 'checkinDueDate', 'goalUrl'],
  training_assigned: ['employeeName', 'trainingName', 'trainingDueDate', 'trainingUrl'],
  training_due_reminder: ['employeeName', 'trainingName', 'trainingDueDate', 'trainingUrl'],
  training_completed: ['employeeName', 'trainingName', 'certificateUrl'],
  expense_status_changed: ['employeeName', 'expenseTitle', 'expenseAmount', 'expenseStatus', 'expenseUrl'],
  company_announcement: ['recipientName', 'announcementTitle', 'announcementContent', 'companyName'],
  policy_acknowledgement_required: ['employeeName', 'policyName', 'policyUrl', 'acknowledgementDueDate'],
  resignation_acknowledged: ['employeeName', 'lastWorkingDate', 'companyName'],
  exit_interview_invitation: ['employeeName', 'lastWorkingDate', 'exitInterviewUrl'],
  offboarding_task_reminder: ['recipientName', 'employeeName', 'taskName', 'taskDueDate', 'offboardingUrl'],
  termination_notice: ['employeeName', 'terminationDate', 'companyName'],
  email_verification_code: ['recipientName', 'verificationCode', 'verificationExpiry'],
  account_locked_alert: ['recipientName', 'lockedAt', 'unlockUrl'],
};

export function getEmailTemplateAttributes(templateCode: string): EmailTemplateAttribute[] {
  return (attributesByTemplate[templateCode] || []).map(key => ({
    key,
    description: descriptions[key] || key,
  }));
}

export function formatEmailTemplateAttribute(key: string): string {
  return `{{${key}}}`;
}

