import { v4 as uuidv4 } from 'uuid';

/**
 * Sanitizes a filename for safe storage by removing/replacing special characters
 * @param filename The original filename
 * @returns Sanitized filename safe for storage
 */
export function sanitizeFilename(filename: string): string {
  return filename
    .replace(/[^a-zA-Z0-9._-]/g, '_') // Replace special characters with underscores
    .replace(/_{2,}/g, '_') // Replace multiple consecutive underscores with single
    .replace(/^_+|_+$/g, ''); // Remove leading/trailing underscores
}

/**
 * Generates a unique filename that preserves the original name while avoiding conflicts
 * @param originalFilename The original filename
 * @param jobId Optional job ID to include in the filename
 * @returns Unique filename with original name preserved
 */
export function generateUniqueFilename(originalFilename: string, jobId?: string): string {
  const sanitizedFileName = sanitizeFilename(originalFilename);
  const timestamp = Date.now();
  const ext = originalFilename.split('.').pop() || 'pdf';
  const baseName = sanitizedFileName.replace(`.${ext}`, '');
  const uniqueId = jobId || uuidv4();
  
  return `${baseName}_${timestamp}_${uniqueId}.${ext}`;
}

/**
 * Extracts the original filename from a unique filename generated by generateUniqueFilename
 * @param uniqueFilename The unique filename
 * @returns The original filename (approximate, as special characters were sanitized)
 */
export function extractOriginalFilename(uniqueFilename: string): string {
  // Remove timestamp and UUID from the end
  const parts = uniqueFilename.split('_');
  if (parts.length < 3) {
    return uniqueFilename; // Not a generated filename, return as is
  }
  
  // Remove the last two parts (timestamp and UUID)
  const originalParts = parts.slice(0, -2);
  return originalParts.join('_');
}
