import { v4 as uuidv4 } from 'uuid';

/**
 * Sanitizes a filename for safe storage by removing/replacing special characters
 * @param filename The original filename
 * @returns Sanitized filename safe for storage
 */
export function sanitizeFilename(filename: string): string {
  // First, handle multiple consecutive dots by replacing them with a single dot
  let sanitized = filename.replace(/\.{2,}/g, '.');
  
  // Then replace other special characters with underscores
  sanitized = sanitized.replace(/[^a-zA-Z0-9._-]/g, '_');
  
  // Replace multiple consecutive underscores with single
  sanitized = sanitized.replace(/_{2,}/g, '_');
  
  // Remove leading/trailing underscores
  sanitized = sanitized.replace(/^_+|_+$/g, '');
  
  return sanitized;
}

/**
 * Generates a unique filename that preserves the original name while avoiding conflicts
 * @param originalFilename The original filename
 * @param jobId Optional job ID to include in the filename
 * @returns Unique filename with original name preserved
 */
export function generateUniqueFilename(originalFilename: string, jobId?: string): string {
  const sanitizedFileName = sanitizeFilename(originalFilename);
  const timestamp = Date.now();
  
  // Extract extension more robustly - handle cases where filename might not have extension
  const lastDotIndex = originalFilename.lastIndexOf('.');
  const ext = lastDotIndex > 0 ? originalFilename.substring(lastDotIndex + 1) : 'pdf';
  
  // Get base name by removing the extension from the sanitized filename
  const sanitizedExt = sanitizeFilename(ext);
  const baseName = sanitizedFileName.endsWith(`.${sanitizedExt}`) 
    ? sanitizedFileName.slice(0, -sanitizedExt.length - 1)
    : sanitizedFileName;
  
  const uniqueId = jobId || uuidv4();
  
  return `${baseName}_${timestamp}_${uniqueId}.${sanitizedExt}`;
}

/**
 * Extracts the original filename from a unique filename generated by generateUniqueFilename
 * @param uniqueFilename The unique filename
 * @returns The original filename (approximate, as special characters were sanitized)
 */
export function extractOriginalFilename(uniqueFilename: string): string {
  // Remove timestamp and UUID from the end
  const parts = uniqueFilename.split('_');
  if (parts.length < 3) {
    return uniqueFilename; // Not a generated filename, return as is
  }
  
  // Remove the last two parts (timestamp and UUID)
  const originalParts = parts.slice(0, -2);
  return originalParts.join('_');
}
