// Version constant - auto-generated from package.json
// DO NOT EDIT THIS FILE MANUALLY - it is generated by scripts/sync-version.js
// To update the version, edit package.json and run: npm run sync-version
<<<<<<< HEAD
export const APP_VERSION = '2.1.23-beta.2';
=======
export const APP_VERSION = '1.2.1';
>>>>>>> ca51ac36
