// Version constant - auto-generated from package.json
// DO NOT EDIT THIS FILE MANUALLY - it is generated by scripts/sync-version.js
// To update the version, edit package.json and run: npm run sync-version
export const APP_VERSION = '1.2.6';
