-- Example Data SQL Script for FitScan
-- This script creates sample data for candidates, positions, and upload queue
-- Run this after the initial database setup and seeding

-- ==============================================
-- PREREQUISITES
-- ==============================================
-- Make sure the following are already created:
-- 1. Admin user (admin@qsncc.com)
-- 2. Recruitment stages
-- 3. User groups
-- 4. Grades
-- 5. Position levels
-- 6. Candidate sources

-- ==============================================
-- CREATE EXAMPLE POSITIONS
-- ==============================================

-- Insert example positions
INSERT INTO "Position" (
    id,
    title,
    department,
    description,
    "matchCriteria",
    "isOpen",
    "positionLevel",
    "recruiterId",
    "customAttributes",
    "createdAt",
    "updatedAt",
    "gradeId",
    "requestDate",
    "positionAttribute"
) VALUES 
-- Software Development Positions
(
    'pos-001-software-engineer',
    'Senior Software Engineer',
    'Engineering',
    'We are looking for a Senior Software Engineer to join our development team. The ideal candidate will have strong experience in full-stack development and be able to work independently on complex projects.',
    '<h2>Required Skills & Experience</h2><ul><li>Bachelor''s degree in Computer Science or related field</li><li>5+ years of software development experience</li><li>Proficiency in JavaScript, React, Node.js</li><li>Experience with databases (PostgreSQL, MongoDB)</li><li>Strong problem-solving and communication skills</li></ul><h2>Preferred Qualifications</h2><ul><li>Experience with cloud platforms (AWS, Azure)</li><li>Knowledge of DevOps practices</li><li>Experience with microservices architecture</li><li>Agile/Scrum experience</li></ul>',
    true,
    'Senior',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '{"location": "Bangkok", "salary_range": "80,000-120,000 THB", "benefits": ["Health Insurance", "Flexible Hours", "Remote Work"]}',
    NOW(),
    NOW(),
    (SELECT id FROM "Grade" WHERE name = 'G6' LIMIT 1),
    '2024-03-15',
    'Full-time'
),
(
    'pos-002-frontend-developer',
    'Frontend Developer',
    'Engineering',
    'Join our frontend team to build beautiful and responsive user interfaces. We need someone passionate about modern web technologies and user experience.',
    '<h2>Required Skills & Experience</h2><ul><li>3+ years of frontend development experience</li><li>Strong knowledge of React, TypeScript, and CSS</li><li>Experience with state management (Redux, Zustand)</li><li>Understanding of responsive design principles</li><li>Experience with testing frameworks (Jest, Cypress)</li></ul><h2>Preferred Qualifications</h2><ul><li>Experience with Next.js or similar frameworks</li><li>Knowledge of design systems</li><li>Experience with performance optimization</li><li>UI/UX design skills</li></ul>',
    true,
    'Mid Level',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '{"location": "Bangkok", "salary_range": "60,000-90,000 THB", "benefits": ["Health Insurance", "Learning Budget"]}',
    NOW(),
    NOW(),
    (SELECT id FROM "Grade" WHERE name = 'G4' LIMIT 1),
    '2024-02-28',
    'Full-time'
),
(
    'pos-003-data-scientist',
    'Data Scientist',
    'Analytics',
    'We are seeking a Data Scientist to help us extract insights from our data and build predictive models. The role involves working with large datasets and collaborating with cross-functional teams.',
    '<h2>Required Skills & Experience</h2><ul><li>Master''s degree in Data Science, Statistics, or related field</li><li>3+ years of experience in data science</li><li>Proficiency in Python, R, and SQL</li><li>Experience with machine learning frameworks (scikit-learn, TensorFlow)</li><li>Strong statistical analysis skills</li></ul><h2>Preferred Qualifications</h2><ul><li>Experience with big data tools (Spark, Hadoop)</li><li>Knowledge of deep learning</li><li>Experience with cloud ML platforms</li><li>Strong business acumen</li></ul>',
    true,
    'Senior',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '{"location": "Bangkok", "salary_range": "90,000-130,000 THB", "benefits": ["Health Insurance", "Research Budget"]}',
    NOW(),
    NOW(),
    (SELECT id FROM "Grade" WHERE name = 'G6' LIMIT 1),
    '2024-04-01',
    'Full-time'
),
(
    'pos-004-product-manager',
    'Product Manager',
    'Product',
    'Lead product development initiatives and work closely with engineering, design, and business teams to deliver exceptional user experiences.',
    '<h2>Required Skills & Experience</h2><ul><li>Bachelor''s degree in Business, Engineering, or related field</li><li>4+ years of product management experience</li><li>Strong analytical and problem-solving skills</li><li>Experience with agile development methodologies</li><li>Excellent communication and leadership skills</li></ul><h2>Preferred Qualifications</h2><ul><li>Experience in B2B SaaS products</li><li>Technical background or understanding</li><li>Experience with user research and A/B testing</li><li>MBA or advanced degree</li></ul>',
    true,
    'Senior',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '{"location": "Bangkok", "salary_range": "100,000-150,000 THB", "benefits": ["Health Insurance", "Stock Options"]}',
    NOW(),
    NOW(),
    (SELECT id FROM "Grade" WHERE name = 'G7' LIMIT 1),
    '2024-03-30',
    'Full-time'
),
(
    'pos-005-ux-designer',
    'UX Designer',
    'Design',
    'Create intuitive and engaging user experiences for our products. Work with cross-functional teams to understand user needs and translate them into design solutions.',
    '<h2>Required Skills & Experience</h2><ul><li>Bachelor''s degree in Design, HCI, or related field</li><li>3+ years of UX design experience</li><li>Proficiency in design tools (Figma, Sketch, Adobe Creative Suite)</li><li>Experience with user research and usability testing</li><li>Strong portfolio demonstrating UX design skills</li></ul><h2>Preferred Qualifications</h2><ul><li>Experience with design systems</li><li>Knowledge of frontend development</li><li>Experience with accessibility standards</li><li>Experience in B2B products</li></ul>',
    true,
    'Mid Level',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '{"location": "Bangkok", "salary_range": "70,000-100,000 THB", "benefits": ["Health Insurance", "Design Tools Budget"]}',
    NOW(),
    NOW(),
    (SELECT id FROM "Grade" WHERE name = 'G5' LIMIT 1),
    '2024-03-20',
    'Full-time'
),
-- Additional positions for more variety
(
    'pos-006-devops-engineer',
    'DevOps Engineer',
    'Engineering',
    'Join our DevOps team to build and maintain our cloud infrastructure. You will work with cutting-edge technologies to ensure our systems are scalable, reliable, and secure.',
    '<h2>Required Skills & Experience</h2><ul><li>3+ years of DevOps/Infrastructure experience</li><li>Strong knowledge of AWS, Azure, or GCP</li><li>Experience with containerization (Docker, Kubernetes)</li><li>Proficiency in Infrastructure as Code (Terraform, CloudFormation)</li><li>Experience with CI/CD pipelines</li></ul><h2>Preferred Qualifications</h2><ul><li>Experience with monitoring tools (Prometheus, Grafana)</li><li>Knowledge of security best practices</li><li>Experience with microservices architecture</li><li>Scripting skills (Python, Bash)</li></ul>',
    true,
    'Mid Level',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '{"location": "Bangkok", "salary_range": "70,000-110,000 THB", "benefits": ["Health Insurance", "Learning Budget", "Remote Work"]}',
    NOW(),
    NOW(),
    (SELECT id FROM "Grade" WHERE name = 'G5' LIMIT 1),
    '2024-04-15',
    'Full-time'
),
(
    'pos-007-marketing-manager',
    'Marketing Manager',
    'Marketing',
    'Lead our marketing initiatives and drive brand awareness. You will develop and execute marketing strategies to support business growth and customer acquisition.',
    '<h2>Required Skills & Experience</h2><ul><li>Bachelor''s degree in Marketing, Business, or related field</li><li>4+ years of marketing experience</li><li>Experience with digital marketing channels</li><li>Strong analytical and project management skills</li><li>Excellent communication and leadership abilities</li></ul><h2>Preferred Qualifications</h2><ul><li>Experience with marketing automation tools</li><li>Knowledge of SEO/SEM and social media marketing</li><li>Experience in B2B marketing</li><li>MBA or advanced degree</li></ul>',
    true,
    'Senior',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '{"location": "Bangkok", "salary_range": "80,000-120,000 THB", "benefits": ["Health Insurance", "Marketing Budget"]}',
    NOW(),
    NOW(),
    (SELECT id FROM "Grade" WHERE name = 'G6' LIMIT 1),
    '2024-03-25',
    'Full-time'
),
(
    'pos-008-sales-representative',
    'Sales Representative',
    'Sales',
    'Join our sales team to drive revenue growth and build strong customer relationships. You will be responsible for identifying new business opportunities and closing deals.',
    '<h2>Required Skills & Experience</h2><ul><li>Bachelor''s degree in Business, Sales, or related field</li><li>2+ years of sales experience</li><li>Strong communication and negotiation skills</li><li>Goal-oriented and self-motivated</li><li>Experience with CRM systems</li></ul><h2>Preferred Qualifications</h2><ul><li>Experience in B2B sales</li><li>Knowledge of the tech industry</li><li>Experience with consultative selling</li><li>Track record of meeting/exceeding sales targets</li></ul>',
    true,
    'Junior',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '{"location": "Bangkok", "salary_range": "40,000-70,000 THB", "benefits": ["Health Insurance", "Commission", "Sales Training"]}',
    NOW(),
    NOW(),
    (SELECT id FROM "Grade" WHERE name = 'G3' LIMIT 1),
    '2024-04-10',
    'Full-time'
),
(
    'pos-009-hr-specialist',
    'HR Specialist',
    'Human Resources',
    'Support our human resources operations and help create a positive work environment. You will handle recruitment, employee relations, and HR administration.',
    '<h2>Required Skills & Experience</h2><ul><li>Bachelor''s degree in HR, Psychology, or related field</li><li>2+ years of HR experience</li><li>Knowledge of labor laws and regulations</li><li>Strong interpersonal and communication skills</li><li>Experience with HRIS systems</li></ul><h2>Preferred Qualifications</h2><ul><li>HR certification (PHR, SHRM-CP)</li><li>Experience with recruitment and onboarding</li><li>Knowledge of performance management</li><li>Bilingual (English/Thai)</li></ul>',
    true,
    'Mid Level',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '{"location": "Bangkok", "salary_range": "50,000-80,000 THB", "benefits": ["Health Insurance", "Professional Development"]}',
    NOW(),
    NOW(),
    (SELECT id FROM "Grade" WHERE name = 'G4' LIMIT 1),
    '2024-04-05',
    'Full-time'
),
(
    'pos-010-financial-analyst',
    'Financial Analyst',
    'Finance',
    'Join our finance team to provide financial analysis and support business decision-making. You will prepare financial reports, analyze trends, and support budgeting processes.',
    '<h2>Required Skills & Experience</h2><ul><li>Bachelor''s degree in Finance, Accounting, or related field</li><li>3+ years of financial analysis experience</li><li>Strong Excel and financial modeling skills</li><li>Knowledge of accounting principles</li><li>Excellent analytical and problem-solving abilities</li></ul><h2>Preferred Qualifications</h2><ul><li>CPA or CFA certification</li><li>Experience with financial software (SAP, Oracle)</li><li>Knowledge of investment analysis</li><li>MBA or advanced degree</li></ul>',
    true,
    'Mid Level',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '{"location": "Bangkok", "salary_range": "60,000-90,000 THB", "benefits": ["Health Insurance", "Professional Certification Support"]}',
    NOW(),
    NOW(),
    (SELECT id FROM "Grade" WHERE name = 'G5' LIMIT 1),
    '2024-04-20',
    'Full-time'
),
(
    'pos-011-qa-engineer',
    'QA Engineer',
    'Engineering',
    'Ensure the quality of our software products through comprehensive testing. You will design and execute test plans, identify bugs, and work with development teams to improve product quality.',
    '<h2>Required Skills & Experience</h2><ul><li>Bachelor''s degree in Computer Science or related field</li><li>2+ years of QA/testing experience</li><li>Knowledge of testing methodologies and tools</li><li>Experience with automated testing frameworks</li><li>Strong attention to detail and problem-solving skills</li></ul><h2>Preferred Qualifications</h2><ul><li>Experience with Selenium, Cypress, or similar tools</li><li>Knowledge of API testing</li><li>Experience with performance testing</li><li>ISTQB certification</li></ul>',
    true,
    'Mid Level',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '{"location": "Bangkok", "salary_range": "55,000-85,000 THB", "benefits": ["Health Insurance", "Testing Tools Budget"]}',
    NOW(),
    NOW(),
    (SELECT id FROM "Grade" WHERE name = 'G4' LIMIT 1),
    '2024-04-12',
    'Full-time'
),
(
    'pos-012-customer-success-manager',
    'Customer Success Manager',
    'Customer Success',
    'Help our customers achieve their goals and ensure their success with our products. You will build strong relationships, identify growth opportunities, and drive customer satisfaction.',
    '<h2>Required Skills & Experience</h2><ul><li>Bachelor''s degree in Business, Marketing, or related field</li><li>3+ years of customer success or account management experience</li><li>Strong communication and relationship-building skills</li><li>Experience with CRM systems</li><li>Analytical mindset with focus on customer metrics</li></ul><h2>Preferred Qualifications</h2><ul><li>Experience in SaaS or technology industry</li><li>Knowledge of customer success tools</li><li>Experience with upselling and cross-selling</li><li>Bilingual (English/Thai)</li></ul>',
    true,
    'Mid Level',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '{"location": "Bangkok", "salary_range": "65,000-95,000 THB", "benefits": ["Health Insurance", "Customer Success Tools"]}',
    NOW(),
    NOW(),
    (SELECT id FROM "Grade" WHERE name = 'G5' LIMIT 1),
    '2024-04-18',
    'Full-time'
);

-- ==============================================
-- CREATE EXAMPLE CANDIDATES
-- ==============================================

-- Insert example candidates
INSERT INTO "Candidate" (
    id,
    name,
    email,
    phone,
    "positionId",
    "recruiterId",
    "fitScore",
    "applicationDate",
    "parsedData",
    "customAttributes",
    "resumePath",
    "createdAt",
    "updatedAt",
    "avatarUrl",
    "dataAiHint",
    "assignmentJustification",
    "educationData",
    "experienceData",
    "companyId",
    "sourceId",
    "subSource",
    "statusId",
    "isPinned",
    "pinnedAt"
) VALUES 
-- Candidate 1: Senior Software Engineer
(
    'cand-001-john-smith',
    'John Smith',
    'john.smith@email.com',
    '+66-81-234-5678',
    'pos-001-software-engineer',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    0.85,
    '2024-01-15',
    '{"skills": ["JavaScript", "React", "Node.js", "PostgreSQL", "AWS"], "experience_years": 6, "education": "Bachelor of Computer Science", "languages": ["English", "Thai"], "certifications": ["AWS Certified Developer"]}',
    '{"expected_salary": "100,000 THB", "availability": "2 weeks notice", "preferred_location": "Bangkok", "remote_work": true}',
    '/uploads/resumes/john_smith_resume.pdf',
    '2024-01-15',
    NOW(),
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    'Experienced full-stack developer with strong React and Node.js skills. Has AWS certification and 6 years of experience.',
    'Strong technical background with relevant experience in our tech stack. AWS certification is a plus.',
    '[{"degree": "Bachelor of Computer Science", "university": "Chulalongkorn University", "year": 2018, "gpa": "3.5"}]',
    '[{"company": "TechCorp Thailand", "position": "Senior Software Engineer", "duration": "2021-2024", "description": "Led development of microservices architecture and improved system performance by 40%"}, {"company": "StartupXYZ", "position": "Software Engineer", "duration": "2018-2021", "description": "Developed full-stack applications using React and Node.js"}]',
    null,
    (SELECT id FROM "CandidateSource" WHERE name = 'Linkedin' LIMIT 1),
    'Direct Application',
    (SELECT id FROM "RecruitmentStage" WHERE name = 'Interview Scheduled' LIMIT 1),
    false,
    null
),
-- Candidate 2: Frontend Developer
(
    'cand-002-sarah-johnson',
    'Sarah Johnson',
    'sarah.johnson@email.com',
    '+66-82-345-6789',
    'pos-002-frontend-developer',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    0.78,
    '2024-01-20',
    '{"skills": ["React", "TypeScript", "CSS", "Jest", "Figma"], "experience_years": 4, "education": "Bachelor of Information Technology", "languages": ["English", "Thai"], "certifications": []}',
    '{"expected_salary": "75,000 THB", "availability": "1 month notice", "preferred_location": "Bangkok", "remote_work": false}',
    '/uploads/resumes/sarah_johnson_resume.pdf',
    '2024-01-20',
    NOW(),
    'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
    'Frontend specialist with strong React and TypeScript skills. Has experience with testing and design tools.',
    'Good frontend skills with modern technologies. Experience with testing frameworks is valuable.',
    '[{"degree": "Bachelor of Information Technology", "university": "KMITL", "year": 2020, "gpa": "3.7"}]',
    '[{"company": "Digital Agency Co.", "position": "Frontend Developer", "duration": "2022-2024", "description": "Built responsive web applications and improved user experience metrics"}, {"company": "WebStudio", "position": "Junior Frontend Developer", "duration": "2020-2022", "description": "Developed user interfaces using React and CSS frameworks"}]',
    null,
    (SELECT id FROM "CandidateSource" WHERE name = 'JobsDB' LIMIT 1),
    'Job Portal',
    (SELECT id FROM "RecruitmentStage" WHERE name = 'Shortlisted' LIMIT 1),
    true,
    '2024-01-25'
),
-- Candidate 3: Data Scientist
(
    'cand-003-michael-chen',
    'Michael Chen',
    'michael.chen@email.com',
    '+66-83-456-7890',
    'pos-003-data-scientist',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    0.92,
    '2024-01-18',
    '{"skills": ["Python", "R", "SQL", "Machine Learning", "TensorFlow", "Spark"], "experience_years": 5, "education": "Master of Data Science", "languages": ["English", "Chinese", "Thai"], "certifications": ["Google Cloud ML Engineer"]}',
    '{"expected_salary": "120,000 THB", "availability": "3 weeks notice", "preferred_location": "Bangkok", "remote_work": true}',
    '/uploads/resumes/michael_chen_resume.pdf',
    '2024-01-18',
    NOW(),
    'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    'Highly qualified data scientist with advanced degree and strong ML background. Google Cloud certification.',
    'Excellent candidate with advanced degree and relevant experience. Strong technical skills and certifications.',
    '[{"degree": "Master of Data Science", "university": "Stanford University", "year": 2019, "gpa": "3.8"}, {"degree": "Bachelor of Statistics", "university": "Chulalongkorn University", "year": 2017, "gpa": "3.6"}]',
    '[{"company": "DataTech Solutions", "position": "Senior Data Scientist", "duration": "2021-2024", "description": "Led ML model development and improved prediction accuracy by 25%"}, {"company": "Analytics Pro", "position": "Data Scientist", "duration": "2019-2021", "description": "Built predictive models and performed statistical analysis"}]',
    null,
    (SELECT id FROM "CandidateSource" WHERE name = 'Referral' LIMIT 1),
    'Employee Referral',
    (SELECT id FROM "RecruitmentStage" WHERE name = 'Interviewing' LIMIT 1),
    false,
    null
),
-- Candidate 4: Product Manager
(
    'cand-004-emily-wilson',
    'Emily Wilson',
    'emily.wilson@email.com',
    '+66-84-567-8901',
    'pos-004-product-manager',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    0.88,
    '2024-01-22',
    '{"skills": ["Product Management", "Agile", "Analytics", "User Research", "A/B Testing"], "experience_years": 5, "education": "MBA", "languages": ["English", "Thai"], "certifications": ["Certified Scrum Product Owner"]}',
    '{"expected_salary": "130,000 THB", "availability": "1 month notice", "preferred_location": "Bangkok", "remote_work": false}',
    '/uploads/resumes/emily_wilson_resume.pdf',
    '2024-01-22',
    NOW(),
    'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    'Experienced product manager with MBA and strong analytical skills. Has experience with agile methodologies.',
    'Strong product management background with MBA. Experience with user research and analytics.',
    '[{"degree": "MBA", "university": "INSEAD", "year": 2020, "gpa": "3.9"}, {"degree": "Bachelor of Business Administration", "university": "Thammasat University", "year": 2018, "gpa": "3.8"}]',
    '[{"company": "ProductCorp", "position": "Senior Product Manager", "duration": "2022-2024", "description": "Led product strategy and increased user engagement by 35%"}, {"company": "TechStartup", "position": "Product Manager", "duration": "2020-2022", "description": "Managed product roadmap and coordinated with engineering teams"}]',
    null,
    (SELECT id FROM "CandidateSource" WHERE name = 'Linkedin' LIMIT 1),
    'Professional Network',
    (SELECT id FROM "RecruitmentStage" WHERE name = 'Offer Extended' LIMIT 1),
    true,
    '2024-01-28'
),
-- Candidate 5: UX Designer
(
    'cand-005-david-brown',
    'David Brown',
    'david.brown@email.com',
    '+66-85-678-9012',
    'pos-005-ux-designer',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    0.75,
    '2024-01-25',
    '{"skills": ["Figma", "Sketch", "User Research", "Prototyping", "Design Systems"], "experience_years": 3, "education": "Bachelor of Design", "languages": ["English", "Thai"], "certifications": []}',
    '{"expected_salary": "85,000 THB", "availability": "2 weeks notice", "preferred_location": "Bangkok", "remote_work": true}',
    '/uploads/resumes/david_brown_resume.pdf',
    '2024-01-25',
    NOW(),
    'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
    'Creative UX designer with strong portfolio and user research experience. Proficient in modern design tools.',
    'Good UX skills with experience in user research. Portfolio shows strong design capabilities.',
    '[{"degree": "Bachelor of Design", "university": "Silpakorn University", "year": 2021, "gpa": "3.6"}]',
    '[{"company": "Design Studio", "position": "UX Designer", "duration": "2022-2024", "description": "Designed user interfaces and conducted user research studies"}, {"company": "Creative Agency", "position": "Junior UX Designer", "duration": "2021-2022", "description": "Created wireframes and prototypes for web applications"}]',
    null,
    (SELECT id FROM "CandidateSource" WHERE name = 'JobThai' LIMIT 1),
    'Job Portal',
    (SELECT id FROM "RecruitmentStage" WHERE name = 'Applied' LIMIT 1),
    false,
    null
),
-- Candidate 6: Additional Software Engineer (for variety)
(
    'cand-006-lisa-garcia',
    'Lisa Garcia',
    'lisa.garcia@email.com',
    '+66-86-789-0123',
    'pos-001-software-engineer',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    0.72,
    '2024-01-30',
    '{"skills": ["Java", "Spring Boot", "MySQL", "Docker", "Kubernetes"], "experience_years": 4, "education": "Bachelor of Computer Engineering", "languages": ["English", "Spanish", "Thai"], "certifications": ["Oracle Java Certified"]}',
    '{"expected_salary": "90,000 THB", "availability": "1 month notice", "preferred_location": "Bangkok", "remote_work": false}',
    '/uploads/resumes/lisa_garcia_resume.pdf',
    '2024-01-30',
    NOW(),
    'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face',
    'Backend-focused developer with Java and Spring Boot experience. Has containerization knowledge.',
    'Good backend skills with Java stack. Experience with DevOps tools is valuable.',
    '[{"degree": "Bachelor of Computer Engineering", "university": "Kasetsart University", "year": 2020, "gpa": "3.4"}]',
    '[{"company": "Enterprise Solutions", "position": "Software Engineer", "duration": "2022-2024", "description": "Developed backend services using Java and Spring Boot"}, {"company": "TechConsulting", "position": "Junior Developer", "duration": "2020-2022", "description": "Worked on web applications and database design"}]',
    null,
    (SELECT id FROM "CandidateSource" WHERE name = 'Facebook' LIMIT 1),
    'Social Media',
    (SELECT id FROM "RecruitmentStage" WHERE name = 'Screening' LIMIT 1),
    false,
    null
),
-- Additional candidates for the new positions
-- Candidate 7: DevOps Engineer
(
    'cand-007-alex-kumar',
    'Alex Kumar',
    'alex.kumar@email.com',
    '+66-87-890-1234',
    'pos-006-devops-engineer',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    0.82,
    '2024-02-01',
    '{"skills": ["AWS", "Docker", "Kubernetes", "Terraform", "Python", "Jenkins"], "experience_years": 4, "education": "Bachelor of Computer Engineering", "languages": ["English", "Hindi", "Thai"], "certifications": ["AWS Certified Solutions Architect"]}',
    '{"expected_salary": "95,000 THB", "availability": "2 weeks notice", "preferred_location": "Bangkok", "remote_work": true}',
    '/uploads/resumes/alex_kumar_resume.pdf',
    '2024-02-01',
    NOW(),
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    'Experienced DevOps engineer with strong AWS and containerization skills. Has infrastructure automation experience.',
    'Strong DevOps background with AWS certification and containerization expertise.',
    '[{"degree": "Bachelor of Computer Engineering", "university": "King Mongkut Institute of Technology", "year": 2020, "gpa": "3.6"}]',
    '[{"company": "CloudTech Solutions", "position": "DevOps Engineer", "duration": "2022-2024", "description": "Managed AWS infrastructure and implemented CI/CD pipelines"}, {"company": "TechStartup", "position": "Junior DevOps Engineer", "duration": "2020-2022", "description": "Assisted with infrastructure setup and monitoring"}]',
    null,
    (SELECT id FROM "CandidateSource" WHERE name = 'Linkedin' LIMIT 1),
    'Professional Network',
    (SELECT id FROM "RecruitmentStage" WHERE name = 'Screening' LIMIT 1),
    false,
    null
),
-- Candidate 8: Marketing Manager
(
    'cand-008-maria-rodriguez',
    'Maria Rodriguez',
    'maria.rodriguez@email.com',
    '+66-88-901-2345',
    'pos-007-marketing-manager',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    0.79,
    '2024-02-03',
    '{"skills": ["Digital Marketing", "SEO", "Social Media", "Analytics", "Campaign Management"], "experience_years": 5, "education": "Master of Marketing", "languages": ["English", "Spanish", "Thai"], "certifications": ["Google Analytics Certified", "HubSpot Marketing Certified"]}',
    '{"expected_salary": "110,000 THB", "availability": "1 month notice", "preferred_location": "Bangkok", "remote_work": false}',
    '/uploads/resumes/maria_rodriguez_resume.pdf',
    '2024-02-03',
    NOW(),
    'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
    'Experienced marketing professional with strong digital marketing background and analytics skills.',
    'Strong marketing background with digital expertise and analytics knowledge.',
    '[{"degree": "Master of Marketing", "university": "Thammasat University", "year": 2019, "gpa": "3.8"}, {"degree": "Bachelor of Business Administration", "university": "University of Barcelona", "year": 2017, "gpa": "3.7"}]',
    '[{"company": "Digital Marketing Agency", "position": "Senior Marketing Manager", "duration": "2021-2024", "description": "Led digital marketing campaigns and increased brand awareness by 60%"}, {"company": "E-commerce Company", "position": "Marketing Specialist", "duration": "2019-2021", "description": "Managed social media and content marketing strategies"}]',
    null,
    (SELECT id FROM "CandidateSource" WHERE name = 'JobsDB' LIMIT 1),
    'Job Portal',
    (SELECT id FROM "RecruitmentStage" WHERE name = 'Shortlisted' LIMIT 1),
    true,
    '2024-02-05'
),
-- Candidate 9: Sales Representative
(
    'cand-009-james-wilson',
    'James Wilson',
    'james.wilson@email.com',
    '+66-89-012-3456',
    'pos-008-sales-representative',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    0.68,
    '2024-02-05',
    '{"skills": ["Sales", "CRM", "Negotiation", "Customer Relations", "Lead Generation"], "experience_years": 3, "education": "Bachelor of Business Administration", "languages": ["English", "Thai"], "certifications": ["Salesforce Certified"]}',
    '{"expected_salary": "55,000 THB", "availability": "2 weeks notice", "preferred_location": "Bangkok", "remote_work": false}',
    '/uploads/resumes/james_wilson_resume.pdf',
    '2024-02-05',
    NOW(),
    'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    'Motivated sales professional with strong communication skills and CRM experience.',
    'Good sales background with CRM experience and strong communication skills.',
    '[{"degree": "Bachelor of Business Administration", "university": "Assumption University", "year": 2021, "gpa": "3.4"}]',
    '[{"company": "Tech Sales Co.", "position": "Sales Representative", "duration": "2022-2024", "description": "Achieved 120% of sales targets and managed key accounts"}, {"company": "Retail Company", "position": "Sales Associate", "duration": "2021-2022", "description": "Provided customer service and product recommendations"}]',
    null,
    (SELECT id FROM "CandidateSource" WHERE name = 'Referral' LIMIT 1),
    'Employee Referral',
    (SELECT id FROM "RecruitmentStage" WHERE name = 'Applied' LIMIT 1),
    false,
    null
),
-- Candidate 10: HR Specialist
(
    'cand-010-sophie-taylor',
    'Sophie Taylor',
    'sophie.taylor@email.com',
    '+66-90-123-4567',
    'pos-009-hr-specialist',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    0.74,
    '2024-02-07',
    '{"skills": ["HR Administration", "Recruitment", "Employee Relations", "HRIS", "Labor Law"], "experience_years": 3, "education": "Bachelor of Psychology", "languages": ["English", "Thai"], "certifications": ["PHR Certification"]}',
    '{"expected_salary": "65,000 THB", "availability": "3 weeks notice", "preferred_location": "Bangkok", "remote_work": false}',
    '/uploads/resumes/sophie_taylor_resume.pdf',
    '2024-02-07',
    NOW(),
    'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    'Experienced HR professional with strong recruitment and employee relations background.',
    'Good HR background with recruitment experience and PHR certification.',
    '[{"degree": "Bachelor of Psychology", "university": "Chulalongkorn University", "year": 2021, "gpa": "3.5"}]',
    '[{"company": "HR Consulting Firm", "position": "HR Specialist", "duration": "2022-2024", "description": "Handled recruitment, onboarding, and employee relations for multiple clients"}, {"company": "Manufacturing Company", "position": "HR Assistant", "duration": "2021-2022", "description": "Assisted with HR administration and recruitment processes"}]',
    null,
    (SELECT id FROM "CandidateSource" WHERE name = 'JobThai' LIMIT 1),
    'Job Portal',
    (SELECT id FROM "RecruitmentStage" WHERE name = 'Screening' LIMIT 1),
    false,
    null
),
-- Candidate 11: Financial Analyst
(
    'cand-011-robert-kim',
    'Robert Kim',
    'robert.kim@email.com',
    '+66-91-234-5678',
    'pos-010-financial-analyst',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    0.86,
    '2024-02-09',
    '{"skills": ["Financial Analysis", "Excel", "Financial Modeling", "SAP", "Investment Analysis"], "experience_years": 4, "education": "Bachelor of Finance", "languages": ["English", "Korean", "Thai"], "certifications": ["CFA Level 1"]}',
    '{"expected_salary": "80,000 THB", "availability": "1 month notice", "preferred_location": "Bangkok", "remote_work": false}',
    '/uploads/resumes/robert_kim_resume.pdf',
    '2024-02-09',
    NOW(),
    'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
    'Strong financial analyst with CFA certification and SAP experience.',
    'Excellent financial background with CFA certification and strong analytical skills.',
    '[{"degree": "Bachelor of Finance", "university": "Korea University", "year": 2020, "gpa": "3.7"}]',
    '[{"company": "Investment Bank", "position": "Financial Analyst", "duration": "2022-2024", "description": "Conducted financial analysis and prepared investment reports"}, {"company": "Accounting Firm", "position": "Junior Financial Analyst", "duration": "2020-2022", "description": "Assisted with financial modeling and analysis"}]',
    null,
    (SELECT id FROM "CandidateSource" WHERE name = 'Linkedin' LIMIT 1),
    'Professional Network',
    (SELECT id FROM "RecruitmentStage" WHERE name = 'Interview Scheduled' LIMIT 1),
    true,
    '2024-02-10'
),
-- Candidate 12: QA Engineer
(
    'cand-012-anna-petrov',
    'Anna Petrov',
    'anna.petrov@email.com',
    '+66-92-345-6789',
    'pos-011-qa-engineer',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    0.71,
    '2024-02-11',
    '{"skills": ["Manual Testing", "Automated Testing", "Selenium", "API Testing", "Test Planning"], "experience_years": 3, "education": "Bachelor of Computer Science", "languages": ["English", "Russian", "Thai"], "certifications": ["ISTQB Foundation Level"]}',
    '{"expected_salary": "70,000 THB", "availability": "2 weeks notice", "preferred_location": "Bangkok", "remote_work": true}',
    '/uploads/resumes/anna_petrov_resume.pdf',
    '2024-02-11',
    NOW(),
    'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face',
    'Experienced QA engineer with both manual and automated testing skills.',
    'Good QA background with ISTQB certification and automation experience.',
    '[{"degree": "Bachelor of Computer Science", "university": "Moscow State University", "year": 2021, "gpa": "3.6"}]',
    '[{"company": "Software Company", "position": "QA Engineer", "duration": "2022-2024", "description": "Designed and executed test plans, identified and reported bugs"}, {"company": "Startup", "position": "Junior QA Tester", "duration": "2021-2022", "description": "Performed manual testing and created test cases"}]',
    null,
    (SELECT id FROM "CandidateSource" WHERE name = 'Facebook' LIMIT 1),
    'Social Media',
    (SELECT id FROM "RecruitmentStage" WHERE name = 'Applied' LIMIT 1),
    false,
    null
),
-- Candidate 13: Customer Success Manager
(
    'cand-013-kevin-lee',
    'Kevin Lee',
    'kevin.lee@email.com',
    '+66-93-456-7890',
    'pos-012-customer-success-manager',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    0.83,
    '2024-02-13',
    '{"skills": ["Customer Success", "Account Management", "CRM", "Upselling", "Customer Relations"], "experience_years": 4, "education": "Bachelor of Business Administration", "languages": ["English", "Chinese", "Thai"], "certifications": ["Customer Success Management Certification"]}',
    '{"expected_salary": "85,000 THB", "availability": "3 weeks notice", "preferred_location": "Bangkok", "remote_work": false}',
    '/uploads/resumes/kevin_lee_resume.pdf',
    '2024-02-13',
    NOW(),
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    'Experienced customer success manager with strong account management and upselling skills.',
    'Strong customer success background with account management experience and upselling track record.',
    '[{"degree": "Bachelor of Business Administration", "university": "National Taiwan University", "year": 2020, "gpa": "3.8"}]',
    '[{"company": "SaaS Company", "position": "Customer Success Manager", "duration": "2022-2024", "description": "Managed key accounts and achieved 95% customer retention rate"}, {"company": "Tech Company", "position": "Account Manager", "duration": "2020-2022", "description": "Handled customer relationships and identified growth opportunities"}]',
    null,
    (SELECT id FROM "CandidateSource" WHERE name = 'Referral' LIMIT 1),
    'Employee Referral',
    (SELECT id FROM "RecruitmentStage" WHERE name = 'Shortlisted' LIMIT 1),
    false,
    null
),
-- Additional candidates for existing positions
-- Candidate 14: Another Software Engineer
(
    'cand-014-raj-patel',
    'Raj Patel',
    'raj.patel@email.com',
    '+66-94-567-8901',
    'pos-001-software-engineer',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    0.77,
    '2024-02-15',
    '{"skills": ["Python", "Django", "PostgreSQL", "Redis", "Docker", "Git"], "experience_years": 5, "education": "Bachelor of Computer Science", "languages": ["English", "Hindi", "Thai"], "certifications": ["Python Institute Certification"]}',
    '{"expected_salary": "95,000 THB", "availability": "1 month notice", "preferred_location": "Bangkok", "remote_work": true}',
    '/uploads/resumes/raj_patel_resume.pdf',
    '2024-02-15',
    NOW(),
    'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    'Experienced Python developer with Django and database expertise.',
    'Strong Python background with Django experience and database skills.',
    '[{"degree": "Bachelor of Computer Science", "university": "Indian Institute of Technology", "year": 2019, "gpa": "3.6"}]',
    '[{"company": "Web Development Agency", "position": "Senior Python Developer", "duration": "2021-2024", "description": "Developed web applications using Django and PostgreSQL"}, {"company": "Startup", "position": "Python Developer", "duration": "2019-2021", "description": "Built backend services and APIs using Python"}]',
    null,
    (SELECT id FROM "CandidateSource" WHERE name = 'JobsDB' LIMIT 1),
    'Job Portal',
    (SELECT id FROM "RecruitmentStage" WHERE name = 'Screening' LIMIT 1),
    false,
    null
),
-- Candidate 15: Another Frontend Developer
(
    'cand-015-yuki-tanaka',
    'Yuki Tanaka',
    'yuki.tanaka@email.com',
    '+66-95-678-9012',
    'pos-002-frontend-developer',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    0.73,
    '2024-02-17',
    '{"skills": ["Vue.js", "JavaScript", "CSS", "Webpack", "Jest", "Figma"], "experience_years": 3, "education": "Bachelor of Information Technology", "languages": ["English", "Japanese", "Thai"], "certifications": []}',
    '{"expected_salary": "68,000 THB", "availability": "2 weeks notice", "preferred_location": "Bangkok", "remote_work": false}',
    '/uploads/resumes/yuki_tanaka_resume.pdf',
    '2024-02-17',
    NOW(),
    'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
    'Frontend developer with Vue.js expertise and design skills.',
    'Good frontend skills with Vue.js experience and design background.',
    '[{"degree": "Bachelor of Information Technology", "university": "Tokyo Institute of Technology", "year": 2021, "gpa": "3.5"}]',
    '[{"company": "Web Design Studio", "position": "Frontend Developer", "duration": "2022-2024", "description": "Developed user interfaces using Vue.js and CSS frameworks"}, {"company": "Digital Agency", "position": "Junior Frontend Developer", "duration": "2021-2022", "description": "Created responsive web designs and interactive components"}]',
    null,
    (SELECT id FROM "CandidateSource" WHERE name = 'University' LIMIT 1),
    'University Partnership',
    (SELECT id FROM "RecruitmentStage" WHERE name = 'Applied' LIMIT 1),
    false,
    null
);

-- ==============================================
-- CREATE EXAMPLE UPLOAD QUEUE ITEMS
-- ==============================================

-- Insert example upload queue items
INSERT INTO "upload_queue" (
    id,
    "file_name",
    "file_size",
    status,
    error,
    "error_details",
    source,
    "source_id",
    "sub_source",
    "upload_date",
    "completed_date",
    "upload_id",
    "created_by",
    "updated_at",
    "file_path",
    "webhook_payload",
    "position_id",
    "process_date"
) VALUES 
-- Successful uploads
(
    'upload-001-success',
    'john_doe_resume.pdf',
    2048576,
    'completed',
    null,
    null,
    'manual',
    (SELECT id FROM "CandidateSource" WHERE name = 'Linkedin' LIMIT 1),
    'Direct Upload',
    '2024-01-15 10:30:00',
    '2024-01-15 10:32:15',
    'upload_12345',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-01-15 10:32:15',
    '/uploads/queue/john_doe_resume.pdf',
    '{"candidate_name": "John Doe", "email": "john.doe@email.com", "position": "Software Engineer"}',
    'pos-001-software-engineer',
    '2024-01-15 10:32:00'
),
(
    'upload-002-success',
    'jane_smith_cv.pdf',
    1536000,
    'completed',
    null,
    null,
    'webhook',
    (SELECT id FROM "CandidateSource" WHERE name = 'JobsDB' LIMIT 1),
    'Job Portal API',
    '2024-01-16 14:20:00',
    '2024-01-16 14:22:30',
    'upload_12346',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-01-16 14:22:30',
    '/uploads/queue/jane_smith_cv.pdf',
    '{"candidate_name": "Jane Smith", "email": "jane.smith@email.com", "position": "Frontend Developer", "source": "JobsDB"}',
    'pos-002-frontend-developer',
    '2024-01-16 14:22:00'
),
-- Processing uploads
(
    'upload-003-processing',
    'mike_johnson_resume.pdf',
    1873408,
    'processing',
    null,
    null,
    'manual',
    (SELECT id FROM "CandidateSource" WHERE name = 'Referral' LIMIT 1),
    'Employee Referral',
    '2024-01-17 09:15:00',
    null,
    'upload_12347',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-01-17 09:15:00',
    '/uploads/queue/mike_johnson_resume.pdf',
    '{"candidate_name": "Mike Johnson", "email": "mike.johnson@email.com", "position": "Data Scientist"}',
    'pos-003-data-scientist',
    '2024-01-17 09:15:00'
),
-- Pending uploads
(
    'upload-004-pending',
    'sarah_williams_cv.pdf',
    1234567,
    'pending',
    null,
    null,
    'webhook',
    (SELECT id FROM "CandidateSource" WHERE name = 'JobThai' LIMIT 1),
    'Job Portal',
    '2024-01-18 16:45:00',
    null,
    'upload_12348',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-01-18 16:45:00',
    '/uploads/queue/sarah_williams_cv.pdf',
    '{"candidate_name": "Sarah Williams", "email": "sarah.williams@email.com", "position": "Product Manager"}',
    'pos-004-product-manager',
    null
),
-- Failed uploads
(
    'upload-005-failed',
    'corrupted_file.pdf',
    512000,
    'failed',
    'File parsing error',
    'Unable to extract text from PDF. File appears to be corrupted or password protected.',
    'manual',
    (SELECT id FROM "CandidateSource" WHERE name = 'Linkedin' LIMIT 1),
    'Direct Upload',
    '2024-01-19 11:20:00',
    null,
    'upload_12349',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-01-19 11:25:00',
    '/uploads/queue/corrupted_file.pdf',
    '{"candidate_name": "Unknown", "email": "unknown@email.com", "position": "UX Designer"}',
    'pos-005-ux-designer',
    '2024-01-19 11:25:00'
),
(
    'upload-006-failed',
    'invalid_format.docx',
    1024000,
    'failed',
    'Unsupported file format',
    'File format .docx is not supported. Please upload PDF files only.',
    'webhook',
    (SELECT id FROM "CandidateSource" WHERE name = 'Facebook' LIMIT 1),
    'Social Media',
    '2024-01-20 13:30:00',
    null,
    'upload_12350',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-01-20 13:35:00',
    '/uploads/queue/invalid_format.docx',
    '{"candidate_name": "Alex Brown", "email": "alex.brown@email.com", "position": "Software Engineer"}',
    'pos-001-software-engineer',
    '2024-01-20 13:35:00'
),
-- Large file upload
(
    'upload-007-large',
    'comprehensive_portfolio.pdf',
    10485760,
    'completed',
    null,
    null,
    'manual',
    (SELECT id FROM "CandidateSource" WHERE name = 'University' LIMIT 1),
    'University Partnership',
    '2024-01-21 08:00:00',
    '2024-01-21 08:05:45',
    'upload_12351',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-01-21 08:05:45',
    '/uploads/queue/comprehensive_portfolio.pdf',
    '{"candidate_name": "Emma Davis", "email": "emma.davis@email.com", "position": "UX Designer", "university": "Chulalongkorn University"}',
    'pos-005-ux-designer',
    '2024-01-21 08:05:00'
),
-- Bulk upload
(
    'upload-008-bulk',
    'bulk_candidates_2024_01.zip',
    5242880,
    'processing',
    null,
    null,
    'bulk',
    (SELECT id FROM "CandidateSource" WHERE name = 'JobExpo' LIMIT 1),
    'Job Fair',
    '2024-01-22 15:00:00',
    null,
    'upload_12352',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-01-22 15:00:00',
    '/uploads/queue/bulk_candidates_2024_01.zip',
    '{"event": "Tech Job Fair 2024", "location": "Bangkok", "date": "2024-01-20", "total_files": 25}',
    null,
    '2024-01-22 15:00:00'
),
-- Additional upload queue items for more variety
-- Recent successful uploads
(
    'upload-009-recent-success',
    'alex_kumar_devops_resume.pdf',
    1892345,
    'completed',
    null,
    null,
    'manual',
    (SELECT id FROM "CandidateSource" WHERE name = 'Linkedin' LIMIT 1),
    'Direct Upload',
    '2024-02-01 14:30:00',
    '2024-02-01 14:32:45',
    'upload_12353',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-01 14:32:45',
    '/uploads/queue/alex_kumar_devops_resume.pdf',
    '{"candidate_name": "Alex Kumar", "email": "alex.kumar@email.com", "position": "DevOps Engineer"}',
    'pos-006-devops-engineer',
    '2024-02-01 14:32:00'
),
(
    'upload-010-marketing-success',
    'maria_rodriguez_marketing_cv.pdf',
    1654321,
    'completed',
    null,
    null,
    'webhook',
    (SELECT id FROM "CandidateSource" WHERE name = 'JobsDB' LIMIT 1),
    'Job Portal API',
    '2024-02-03 10:15:00',
    '2024-02-03 10:17:30',
    'upload_12354',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-03 10:17:30',
    '/uploads/queue/maria_rodriguez_marketing_cv.pdf',
    '{"candidate_name": "Maria Rodriguez", "email": "maria.rodriguez@email.com", "position": "Marketing Manager", "source": "JobsDB"}',
    'pos-007-marketing-manager',
    '2024-02-03 10:17:00'
),
-- Processing uploads
(
    'upload-011-sales-processing',
    'james_wilson_sales_resume.pdf',
    1456789,
    'processing',
    null,
    null,
    'manual',
    (SELECT id FROM "CandidateSource" WHERE name = 'Referral' LIMIT 1),
    'Employee Referral',
    '2024-02-05 16:20:00',
    null,
    'upload_12355',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-05 16:20:00',
    '/uploads/queue/james_wilson_sales_resume.pdf',
    '{"candidate_name": "James Wilson", "email": "james.wilson@email.com", "position": "Sales Representative"}',
    'pos-008-sales-representative',
    '2024-02-05 16:20:00'
),
(
    'upload-012-hr-processing',
    'sophie_taylor_hr_cv.pdf',
    1234567,
    'processing',
    null,
    null,
    'webhook',
    (SELECT id FROM "CandidateSource" WHERE name = 'JobThai' LIMIT 1),
    'Job Portal',
    '2024-02-07 11:45:00',
    null,
    'upload_12356',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-07 11:45:00',
    '/uploads/queue/sophie_taylor_hr_cv.pdf',
    '{"candidate_name": "Sophie Taylor", "email": "sophie.taylor@email.com", "position": "HR Specialist"}',
    'pos-009-hr-specialist',
    '2024-02-07 11:45:00'
),
-- Pending uploads
(
    'upload-013-finance-pending',
    'robert_kim_finance_resume.pdf',
    1876543,
    'pending',
    null,
    null,
    'manual',
    (SELECT id FROM "CandidateSource" WHERE name = 'Linkedin' LIMIT 1),
    'Professional Network',
    '2024-02-09 09:30:00',
    null,
    'upload_12357',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-09 09:30:00',
    '/uploads/queue/robert_kim_finance_resume.pdf',
    '{"candidate_name": "Robert Kim", "email": "robert.kim@email.com", "position": "Financial Analyst"}',
    'pos-010-financial-analyst',
    null
),
(
    'upload-014-qa-pending',
    'anna_petrov_qa_cv.pdf',
    1567890,
    'pending',
    null,
    null,
    'webhook',
    (SELECT id FROM "CandidateSource" WHERE name = 'Facebook' LIMIT 1),
    'Social Media',
    '2024-02-11 13:15:00',
    null,
    'upload_12358',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-11 13:15:00',
    '/uploads/queue/anna_petrov_qa_cv.pdf',
    '{"candidate_name": "Anna Petrov", "email": "anna.petrov@email.com", "position": "QA Engineer"}',
    'pos-011-qa-engineer',
    null
),
-- Failed uploads with different error types
(
    'upload-015-failed-large',
    'huge_portfolio.pdf',
    52428800,
    'failed',
    'File too large',
    'File size exceeds maximum allowed limit of 10MB. Please compress the file or split it into smaller parts.',
    'manual',
    (SELECT id FROM "CandidateSource" WHERE name = 'University' LIMIT 1),
    'University Partnership',
    '2024-02-13 15:45:00',
    null,
    'upload_12359',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-13 15:50:00',
    '/uploads/queue/huge_portfolio.pdf',
    '{"candidate_name": "Kevin Lee", "email": "kevin.lee@email.com", "position": "Customer Success Manager"}',
    'pos-012-customer-success-manager',
    '2024-02-13 15:50:00'
),
(
    'upload-016-failed-empty',
    'empty_file.pdf',
    0,
    'failed',
    'Empty file',
    'Uploaded file is empty or contains no readable content. Please check the file and try again.',
    'webhook',
    (SELECT id FROM "CandidateSource" WHERE name = 'JobsDB' LIMIT 1),
    'Job Portal API',
    '2024-02-15 12:00:00',
    null,
    'upload_12360',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-15 12:05:00',
    '/uploads/queue/empty_file.pdf',
    '{"candidate_name": "Unknown", "email": "unknown@email.com", "position": "Software Engineer"}',
    'pos-001-software-engineer',
    '2024-02-15 12:05:00'
),
-- Recent bulk uploads
(
    'upload-017-bulk-recent',
    'february_candidates_2024.zip',
    8388608,
    'processing',
    null,
    null,
    'bulk',
    (SELECT id FROM "CandidateSource" WHERE name = 'JobExpo' LIMIT 1),
    'Career Fair',
    '2024-02-17 14:00:00',
    null,
    'upload_12361',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-17 14:00:00',
    '/uploads/queue/february_candidates_2024.zip',
    '{"event": "Tech Career Fair 2024", "location": "Bangkok", "date": "2024-02-15", "total_files": 30}',
    null,
    '2024-02-17 14:00:00'
),
-- Duplicate detection
(
    'upload-018-duplicate',
    'john_smith_resume_duplicate.pdf',
    2048576,
    'failed',
    'Duplicate candidate detected',
    'A candidate with the same email address (john.smith@email.com) already exists in the system.',
    'manual',
    (SELECT id FROM "CandidateSource" WHERE name = 'Linkedin' LIMIT 1),
    'Direct Upload',
    '2024-02-19 10:30:00',
    null,
    'upload_12362',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-19 10:32:00',
    '/uploads/queue/john_smith_resume_duplicate.pdf',
    '{"candidate_name": "John Smith", "email": "john.smith@email.com", "position": "Software Engineer"}',
    'pos-001-software-engineer',
    '2024-02-19 10:32:00'
);

-- ==============================================
-- CREATE EXAMPLE TRANSITION RECORDS
-- ==============================================

-- Insert example transition records to show candidate progression
INSERT INTO "TransitionRecord" (
    id,
    "candidateId",
    "positionId",
    date,
    stage,
    notes,
    "actingUserId",
    "createdAt",
    "updatedAt"
) VALUES 
-- John Smith's progression
(
    'trans-001-john-1',
    'cand-001-john-smith',
    'pos-001-software-engineer',
    '2024-01-15',
    'Applied',
    'Initial application received',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-01-15',
    '2024-01-15'
),
(
    'trans-002-john-2',
    'cand-001-john-smith',
    'pos-001-software-engineer',
    '2024-01-16',
    'Screening',
    'Resume review completed - strong technical background',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-01-16',
    '2024-01-16'
),
(
    'trans-003-john-3',
    'cand-001-john-smith',
    'pos-001-software-engineer',
    '2024-01-18',
    'Shortlisted',
    'Technical skills match requirements well',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-01-18',
    '2024-01-18'
),
(
    'trans-004-john-4',
    'cand-001-john-smith',
    'pos-001-software-engineer',
    '2024-01-20',
    'Interview Scheduled',
    'Technical interview scheduled for Jan 25',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-01-20',
    '2024-01-20'
),
-- Sarah Johnson's progression
(
    'trans-005-sarah-1',
    'cand-002-sarah-johnson',
    'pos-002-frontend-developer',
    '2024-01-20',
    'Applied',
    'Application received via JobsDB',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-01-20',
    '2024-01-20'
),
(
    'trans-006-sarah-2',
    'cand-002-sarah-johnson',
    'pos-002-frontend-developer',
    '2024-01-22',
    'Screening',
    'Frontend skills look good, portfolio reviewed',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-01-22',
    '2024-01-22'
),
(
    'trans-007-sarah-3',
    'cand-002-sarah-johnson',
    'pos-002-frontend-developer',
    '2024-01-25',
    'Shortlisted',
    'Strong React and TypeScript experience, pinned for priority review',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-01-25',
    '2024-01-25'
),
-- Michael Chen's progression
(
    'trans-008-michael-1',
    'cand-003-michael-chen',
    'pos-003-data-scientist',
    '2024-01-18',
    'Applied',
    'Application via employee referral',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-01-18',
    '2024-01-18'
),
(
    'trans-009-michael-2',
    'cand-003-michael-chen',
    'pos-003-data-scientist',
    '2024-01-19',
    'Screening',
    'Excellent qualifications - Master degree and Google Cloud certification',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-01-19',
    '2024-01-19'
),
(
    'trans-010-michael-3',
    'cand-003-michael-chen',
    'pos-003-data-scientist',
    '2024-01-22',
    'Shortlisted',
    'Top candidate - advanced degree and relevant experience',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-01-22',
    '2024-01-22'
),
(
    'trans-011-michael-4',
    'cand-003-michael-chen',
    'pos-003-data-scientist',
    '2024-01-24',
    'Interview Scheduled',
    'Technical interview scheduled for Jan 26',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-01-24',
    '2024-01-24'
),
(
    'trans-012-michael-5',
    'cand-003-michael-chen',
    'pos-003-data-scientist',
    '2024-01-26',
    'Interviewing',
    'Technical interview completed - excellent performance',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-01-26',
    '2024-01-26'
),
-- Additional transition records for new candidates
-- Alex Kumar's progression (DevOps Engineer)
(
    'trans-013-alex-1',
    'cand-007-alex-kumar',
    'pos-006-devops-engineer',
    '2024-02-01',
    'Applied',
    'Application received via LinkedIn',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-01',
    '2024-02-01'
),
(
    'trans-014-alex-2',
    'cand-007-alex-kumar',
    'pos-006-devops-engineer',
    '2024-02-02',
    'Screening',
    'Strong DevOps background with AWS certification',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-02',
    '2024-02-02'
),
-- Maria Rodriguez's progression (Marketing Manager)
(
    'trans-015-maria-1',
    'cand-008-maria-rodriguez',
    'pos-007-marketing-manager',
    '2024-02-03',
    'Applied',
    'Application via JobsDB portal',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-03',
    '2024-02-03'
),
(
    'trans-016-maria-2',
    'cand-008-maria-rodriguez',
    'pos-007-marketing-manager',
    '2024-02-04',
    'Screening',
    'Excellent marketing background with digital expertise',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-04',
    '2024-02-04'
),
(
    'trans-017-maria-3',
    'cand-008-maria-rodriguez',
    'pos-007-marketing-manager',
    '2024-02-05',
    'Shortlisted',
    'Strong portfolio and analytics skills - pinned for priority review',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-05',
    '2024-02-05'
),
-- James Wilson's progression (Sales Representative)
(
    'trans-018-james-1',
    'cand-009-james-wilson',
    'pos-008-sales-representative',
    '2024-02-05',
    'Applied',
    'Application via employee referral',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-05',
    '2024-02-05'
),
-- Sophie Taylor's progression (HR Specialist)
(
    'trans-019-sophie-1',
    'cand-010-sophie-taylor',
    'pos-009-hr-specialist',
    '2024-02-07',
    'Applied',
    'Application via JobThai portal',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-07',
    '2024-02-07'
),
(
    'trans-020-sophie-2',
    'cand-010-sophie-taylor',
    'pos-009-hr-specialist',
    '2024-02-08',
    'Screening',
    'Good HR background with PHR certification',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-08',
    '2024-02-08'
),
-- Robert Kim's progression (Financial Analyst)
(
    'trans-021-robert-1',
    'cand-011-robert-kim',
    'pos-010-financial-analyst',
    '2024-02-09',
    'Applied',
    'Application via LinkedIn professional network',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-09',
    '2024-02-09'
),
(
    'trans-022-robert-2',
    'cand-011-robert-kim',
    'pos-010-financial-analyst',
    '2024-02-10',
    'Screening',
    'Excellent financial background with CFA certification - pinned for priority review',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-10',
    '2024-02-10'
),
(
    'trans-023-robert-3',
    'cand-011-robert-kim',
    'pos-010-financial-analyst',
    '2024-02-12',
    'Shortlisted',
    'Strong analytical skills and SAP experience',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-12',
    '2024-02-12'
),
(
    'trans-024-robert-4',
    'cand-011-robert-kim',
    'pos-010-financial-analyst',
    '2024-02-14',
    'Interview Scheduled',
    'Technical interview scheduled for Feb 16',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-14',
    '2024-02-14'
),
-- Anna Petrov's progression (QA Engineer)
(
    'trans-025-anna-1',
    'cand-012-anna-petrov',
    'pos-011-qa-engineer',
    '2024-02-11',
    'Applied',
    'Application via Facebook social media',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-11',
    '2024-02-11'
),
-- Kevin Lee's progression (Customer Success Manager)
(
    'trans-026-kevin-1',
    'cand-013-kevin-lee',
    'pos-012-customer-success-manager',
    '2024-02-13',
    'Applied',
    'Application via employee referral',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-13',
    '2024-02-13'
),
(
    'trans-027-kevin-2',
    'cand-013-kevin-lee',
    'pos-012-customer-success-manager',
    '2024-02-14',
    'Screening',
    'Strong customer success background with upselling experience',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-14',
    '2024-02-14'
),
(
    'trans-028-kevin-3',
    'cand-013-kevin-lee',
    'pos-012-customer-success-manager',
    '2024-02-16',
    'Shortlisted',
    'Excellent account management track record',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-16',
    '2024-02-16'
),
-- Raj Patel's progression (Software Engineer)
(
    'trans-029-raj-1',
    'cand-014-raj-patel',
    'pos-001-software-engineer',
    '2024-02-15',
    'Applied',
    'Application via JobsDB portal',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-15',
    '2024-02-15'
),
(
    'trans-030-raj-2',
    'cand-014-raj-patel',
    'pos-001-software-engineer',
    '2024-02-16',
    'Screening',
    'Strong Python background with Django experience',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-16',
    '2024-02-16'
),
-- Yuki Tanaka's progression (Frontend Developer)
(
    'trans-031-yuki-1',
    'cand-015-yuki-tanaka',
    'pos-002-frontend-developer',
    '2024-02-17',
    'Applied',
    'Application via university partnership program',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    '2024-02-17',
    '2024-02-17'
);

-- ==============================================
-- CREATE EXAMPLE CANDIDATE COMMENTS
-- ==============================================

-- Insert example candidate comments
INSERT INTO "CandidateComment" (
    id,
    "candidateId",
    "authorId",
    content,
    "createdAt",
    "updatedAt",
    "attachmentIds"
) VALUES 
(
    'comment-001-john',
    'cand-001-john-smith',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    'Strong technical background with 6 years of experience. AWS certification is a definite plus. Should proceed to technical interview.',
    '2024-01-16 10:30:00',
    '2024-01-16 10:30:00',
    '{}'
),
(
    'comment-002-sarah',
    'cand-002-sarah-johnson',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    'Excellent frontend skills with modern React and TypeScript. Portfolio shows good attention to detail. Pinned for priority consideration.',
    '2024-01-22 14:15:00',
    '2024-01-22 14:15:00',
    '{}'
),
(
    'comment-003-michael',
    'cand-003-michael-chen',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    'Outstanding candidate with Master degree from Stanford and Google Cloud certification. Strong ML background with 5 years experience. Top choice for the role.',
    '2024-01-19 16:45:00',
    '2024-01-19 16:45:00',
    '{}'
),
(
    'comment-004-emily',
    'cand-004-emily-wilson',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    'Strong product management background with MBA from INSEAD. Experience with user research and analytics. Ready to make offer.',
    '2024-01-28 11:20:00',
    '2024-01-28 11:20:00',
    '{}'
),
(
    'comment-005-david',
    'cand-005-david-brown',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    'Good UX design skills with experience in user research. Portfolio shows creative thinking. Need to schedule initial screening.',
    '2024-01-25 09:30:00',
    '2024-01-25 09:30:00',
    '{}'
),
-- Additional candidate comments for new candidates
(
    'comment-006-alex',
    'cand-007-alex-kumar',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    'Strong DevOps engineer with AWS certification and containerization expertise. Good infrastructure automation experience.',
    '2024-02-02 11:15:00',
    '2024-02-02 11:15:00',
    '{}'
),
(
    'comment-007-maria',
    'cand-008-maria-rodriguez',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    'Excellent marketing professional with strong digital marketing background and analytics skills. Pinned for priority consideration.',
    '2024-02-05 15:30:00',
    '2024-02-05 15:30:00',
    '{}'
),
(
    'comment-008-james',
    'cand-009-james-wilson',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    'Motivated sales professional with strong communication skills and CRM experience. Good track record of meeting targets.',
    '2024-02-05 16:45:00',
    '2024-02-05 16:45:00',
    '{}'
),
(
    'comment-009-sophie',
    'cand-010-sophie-taylor',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    'Experienced HR professional with strong recruitment and employee relations background. PHR certification is a plus.',
    '2024-02-08 10:20:00',
    '2024-02-08 10:20:00',
    '{}'
),
(
    'comment-010-robert',
    'cand-011-robert-kim',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    'Outstanding financial analyst with CFA certification and strong analytical skills. SAP experience is valuable. Top candidate for the role.',
    '2024-02-10 14:10:00',
    '2024-02-10 14:10:00',
    '{}'
),
(
    'comment-011-anna',
    'cand-012-anna-petrov',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    'Good QA engineer with both manual and automated testing skills. ISTQB certification shows commitment to quality.',
    '2024-02-11 13:45:00',
    '2024-02-11 13:45:00',
    '{}'
),
(
    'comment-012-kevin',
    'cand-013-kevin-lee',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    'Strong customer success manager with excellent account management and upselling track record. High customer retention rate.',
    '2024-02-16 09:30:00',
    '2024-02-16 09:30:00',
    '{}'
),
(
    'comment-013-raj',
    'cand-014-raj-patel',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    'Experienced Python developer with strong Django and database expertise. Good backend development skills.',
    '2024-02-16 11:15:00',
    '2024-02-16 11:15:00',
    '{}'
),
(
    'comment-014-yuki',
    'cand-015-yuki-tanaka',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    'Good frontend developer with Vue.js expertise and design skills. University partnership candidate shows potential.',
    '2024-02-17 16:00:00',
    '2024-02-17 16:00:00',
    '{}'
),
-- Additional comments for existing candidates
(
    'comment-015-lisa',
    'cand-006-lisa-garcia',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    'Backend-focused developer with Java and Spring Boot experience. Good DevOps knowledge with Docker and Kubernetes.',
    '2024-01-30 14:20:00',
    '2024-01-30 14:20:00',
    '{}'
),
(
    'comment-016-michael-followup',
    'cand-003-michael-chen',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    'Follow-up: Technical interview went exceptionally well. Candidate demonstrated deep ML knowledge and practical experience. Ready for final interview.',
    '2024-01-27 10:30:00',
    '2024-01-27 10:30:00',
    '{}'
),
(
    'comment-017-emily-followup',
    'cand-004-emily-wilson',
    (SELECT id FROM "User" WHERE email = 'admin@qsncc.com' LIMIT 1),
    'Follow-up: Offer has been extended and accepted. Candidate will start on March 1st. Excellent addition to the product team.',
    '2024-01-30 16:45:00',
    '2024-01-30 16:45:00',
    '{}'
);

-- ==============================================
-- VERIFICATION QUERIES
-- ==============================================

-- Verify the data was inserted correctly
SELECT 'Positions Created' as table_name, COUNT(*) as count FROM "Position"
UNION ALL
SELECT 'Candidates Created', COUNT(*) FROM "Candidate"
UNION ALL
SELECT 'Upload Queue Items', COUNT(*) FROM "upload_queue"
UNION ALL
SELECT 'Transition Records', COUNT(*) FROM "TransitionRecord"
UNION ALL
SELECT 'Candidate Comments', COUNT(*) FROM "CandidateComment";

-- Show sample data
SELECT 'Sample Positions:' as info;
SELECT id, title, department, "isOpen", "positionLevel" FROM "Position" LIMIT 3;

SELECT 'Sample Candidates:' as info;
SELECT id, name, email, "fitScore", "applicationDate" FROM "Candidate" LIMIT 3;

SELECT 'Sample Upload Queue:' as info;
SELECT id, "file_name", status, "upload_date" FROM "upload_queue" LIMIT 3;

-- ==============================================
-- END OF SCRIPT
-- ==============================================
