import { PLATFORM_MODULE_CATEGORIES, type PlatformModule } from './platform-module-types';

export const HR_PLATFORM_MODULES: PlatformModule[] = [
  {
    id: 'HR_PEOPLE_VIEW',
    label: 'View People',
    category: PLATFORM_MODULE_CATEGORIES.HR_OPERATIONS,
    description: 'View employee records, departments, onboarding, and documents.',
    detailedDescription: 'Allows access to core HR employee data and people operations pages.',
    impact: 'Read-only access to HR people records.',
    riskLevel: 'LOW',
  },
  {
    id: 'HR_PEOPLE_MANAGE',
    label: 'Manage People',
    category: PLATFORM_MODULE_CATEGORIES.HR_OPERATIONS,
    description: 'Create and update employee records, departments, onboarding, and documents.',
    detailedDescription: 'Allows HR operators to maintain employee master data and people operations workflow data.',
    impact: 'Can modify employee HR records and onboarding/document state.',
    riskLevel: 'HIGH',
    requiresApproval: true,
  },
  {
    id: 'HR_WORKFORCE_VIEW',
    label: 'View Workforce',
    category: PLATFORM_MODULE_CATEGORIES.HR_OPERATIONS,
    description: 'View attendance, leave, schedules, and holidays.',
    detailedDescription: 'Allows access to workforce management records including attendance and leave data.',
    impact: 'Read-only access to workforce operations records.',
    riskLevel: 'LOW',
  },
  {
    id: 'HR_WORKFORCE_MANAGE',
    label: 'Manage Workforce',
    category: PLATFORM_MODULE_CATEGORIES.HR_OPERATIONS,
    description: 'Create and update attendance, leave, schedules, and holidays.',
    detailedDescription: 'Allows HR operators to maintain time, attendance, leave, and schedule records.',
    impact: 'Can modify records that may feed payroll and compliance reporting.',
    riskLevel: 'HIGH',
    requiresApproval: true,
  },
  {
    id: 'HR_PAYROLL_VIEW',
    label: 'View Payroll',
    category: PLATFORM_MODULE_CATEGORIES.HR_OPERATIONS,
    description: 'View payroll periods, runs, payslips, compensation, and benefits.',
    detailedDescription: 'Allows access to compensation and payroll records without modification rights.',
    impact: 'Read-only access to sensitive payroll information.',
    riskLevel: 'MEDIUM',
  },
  {
    id: 'HR_PAYROLL_MANAGE',
    label: 'Manage Payroll',
    category: PLATFORM_MODULE_CATEGORIES.HR_OPERATIONS,
    description: 'Create and update payroll periods, runs, payslips, compensation, and benefits.',
    detailedDescription: 'Allows payroll operators to maintain payroll setup, calculations, compensation, benefits, payments, accounting outputs, and reconciliation.',
    impact: 'Can modify sensitive payroll and compensation data and advance controlled payroll workflows.',
    riskLevel: 'CRITICAL',
    requiresApproval: true,
  },
  {
    id: 'HR_PERFORMANCE_VIEW',
    label: 'View Performance',
    category: PLATFORM_MODULE_CATEGORIES.HR_OPERATIONS,
    description: 'View performance cycles, reviews, and goals.',
    detailedDescription: 'Allows access to employee performance records and goal progress.',
    impact: 'Read-only access to sensitive performance records.',
    riskLevel: 'MEDIUM',
  },
  {
    id: 'HR_PERFORMANCE_MANAGE',
    label: 'Manage Performance',
    category: PLATFORM_MODULE_CATEGORIES.HR_OPERATIONS,
    description: 'Create and update performance cycles, reviews, and goals.',
    detailedDescription: 'Allows HR and managers to maintain performance review records and goals.',
    impact: 'Can modify performance records that may affect talent decisions.',
    riskLevel: 'HIGH',
    requiresApproval: true,
  },
  {
    id: 'HR_LEARNING_VIEW',
    label: 'View Learning',
    category: PLATFORM_MODULE_CATEGORIES.HR_OPERATIONS,
    description: 'View learning courses, enrollments, and certifications.',
    detailedDescription: 'Allows access to learning and compliance training records.',
    impact: 'Read-only access to employee learning data.',
    riskLevel: 'LOW',
  },
  {
    id: 'HR_LEARNING_MANAGE',
    label: 'Manage Learning',
    category: PLATFORM_MODULE_CATEGORIES.HR_OPERATIONS,
    description: 'Create and update learning courses, enrollments, and certifications.',
    detailedDescription: 'Allows HR operators to maintain learning catalog and employee training progress.',
    impact: 'Can modify learning and compliance training records.',
    riskLevel: 'MEDIUM',
  },
  {
    id: 'SURVEY_VIEW',
    label: 'View Surveys',
    category: PLATFORM_MODULE_CATEGORIES.HR_OPERATIONS,
    description: 'View Survey workspaces, templates, assigned surveys, and permitted results.',
    detailedDescription: 'Allows access to the Survey module. Record and response visibility remains scoped by ownership, audience, privacy mode, and result release.',
    impact: 'Read-only access to permitted survey records.',
    riskLevel: 'LOW',
  },
  {
    id: 'SURVEY_CREATE',
    label: 'Create Surveys',
    category: PLATFORM_MODULE_CATEGORIES.HR_OPERATIONS,
    description: 'Create surveys from a blank definition or an approved template.',
    detailedDescription: 'Allows users to create owned survey drafts without publishing them.',
    impact: 'Can create survey drafts and audience rules.',
    riskLevel: 'MEDIUM',
  },
  {
    id: 'SURVEY_MANAGE',
    label: 'Manage Surveys',
    category: PLATFORM_MODULE_CATEGORIES.HR_OPERATIONS,
    description: 'Build, schedule, publish, pause, close, and remind survey audiences.',
    detailedDescription: 'Allows end-to-end survey operations, including population snapshots and notification distribution.',
    impact: 'Can contact employee populations and control survey availability.',
    riskLevel: 'HIGH',
    requiresApproval: true,
  },
  {
    id: 'SURVEY_ANALYZE',
    label: 'Analyze Survey Results',
    category: PLATFORM_MODULE_CATEGORIES.HR_OPERATIONS,
    description: 'View privacy-safe participation and answer analytics.',
    detailedDescription: 'Allows aggregate survey analysis. Anonymous reporting thresholds remain enforced by backend queries.',
    impact: 'Can access sensitive aggregate employee feedback.',
    riskLevel: 'HIGH',
    requiresApproval: true,
  },
  {
    id: 'SURVEY_EXPORT',
    label: 'Export Survey Results',
    category: PLATFORM_MODULE_CATEGORIES.HR_OPERATIONS,
    description: 'Export authorized survey participation and result datasets.',
    detailedDescription: 'Allows audited exports after privacy, result-release, and minimum-response checks.',
    impact: 'Can move sensitive survey data outside the application.',
    riskLevel: 'CRITICAL',
    requiresApproval: true,
  },
  {
    id: 'SURVEY_RESPONSE_CONFIDENTIAL',
    label: 'View Confidential Responses',
    category: PLATFORM_MODULE_CATEGORIES.HR_OPERATIONS,
    description: 'View respondent identity for confidential surveys where explicitly authorized.',
    detailedDescription: 'Grants field-level access to confidential respondent identity. It does not reveal identity for anonymous surveys.',
    impact: 'Can access highly sensitive employee response identity.',
    riskLevel: 'CRITICAL',
    requiresApproval: true,
  },
  {
    id: 'SURVEY_ADMIN',
    label: 'Administer Surveys',
    category: PLATFORM_MODULE_CATEGORIES.HR_OPERATIONS,
    description: 'Manage survey types, templates, thresholds, releases, and module settings.',
    detailedDescription: 'Provides Survey administration without bypassing anonymous-response separation or minimum reporting thresholds.',
    impact: 'Can configure organization-wide survey governance.',
    riskLevel: 'CRITICAL',
    requiresApproval: true,
  },
];
