import { PositionApplicantsPanel } from './PositionDetailDrawerTabPanels';
import type { PositionDetailDrawerContentProps } from './PositionDetailDrawerContentTypes';

export function PositionApplicantsPanelBranch({
  activeApplicantTab,
  applicantFilters,
  appliedApplicants,
  appliedApplicantsOpenMenu,
  appliedApplicantsPage,
  appliedApplicantsPageSize,
  appliedApplicantsSearchTerm,
  appliedApplicantsSortColumn,
  appliedApplicantsSortDirection,
  appliedApplicantsTotal,
  appliedApplicantsCount,
  availableRecruiters,
  availableSources,
  isAiSearchingApplicants,
  isJobMatchEnabled,
  isMobile,
  onActiveApplicantTabChange,
  onAiSearch,
  onApplicantClick,
  onApplicantFilterChange,
  onAppliedApplicantPinToggle,
  onAppliedApplicantsOpenMenuChange,
  onAppliedApplicantsPageChange,
  onAppliedApplicantsPageSizeChange,
  onAppliedApplicantsSearchChange,
  onAppliedApplicantsSort,
  onClearFilters,
  onPotentialApplicantPinToggle,
  onPotentialApplicantsOpenMenuChange,
  onPotentialApplicantsPageChange,
  onPotentialApplicantsPageSizeChange,
  onPotentialApplicantsSearchChange,
  onPotentialApplicantsSort,
  position,
  potentialApplicants,
  potentialApplicantsOpenMenu,
  potentialApplicantsPage,
  potentialApplicantsPageSize,
  potentialApplicantsSearchTerm,
  potentialApplicantsSortColumn,
  potentialApplicantsSortDirection,
  potentialApplicantsTotal,
  recruitmentStages,
  sortedAppliedApplicants,
  sortedPotentialApplicants,
  stageNames,
}: PositionDetailDrawerContentProps) {
  return (
    <PositionApplicantsPanel
      activeApplicantTab={activeApplicantTab}
      isMobile={isMobile}
      isJobMatchEnabled={isJobMatchEnabled}
      position={position}
      appliedApplicants={appliedApplicants}
      sortedAppliedApplicants={sortedAppliedApplicants}
      appliedApplicantsSearchTerm={appliedApplicantsSearchTerm}
      appliedApplicantsSortColumn={appliedApplicantsSortColumn}
      appliedApplicantsSortDirection={appliedApplicantsSortDirection}
      appliedApplicantsOpenMenu={appliedApplicantsOpenMenu}
      appliedApplicantsPage={appliedApplicantsPage}
      appliedApplicantsPageSize={appliedApplicantsPageSize}
      appliedApplicantsTotal={appliedApplicantsTotal}
      appliedApplicantsCount={appliedApplicantsCount}
      potentialApplicants={potentialApplicants}
      sortedPotentialApplicants={sortedPotentialApplicants}
      potentialApplicantsSearchTerm={potentialApplicantsSearchTerm}
      potentialApplicantsSortColumn={potentialApplicantsSortColumn}
      potentialApplicantsSortDirection={potentialApplicantsSortDirection}
      potentialApplicantsOpenMenu={potentialApplicantsOpenMenu}
      potentialApplicantsPage={potentialApplicantsPage}
      potentialApplicantsPageSize={potentialApplicantsPageSize}
      potentialApplicantsTotal={potentialApplicantsTotal}
      applicantFilters={applicantFilters}
      isAiSearchingApplicants={isAiSearchingApplicants}
      stageNames={stageNames}
      availableRecruiters={availableRecruiters}
      availableSources={availableSources}
      recruitmentStages={recruitmentStages}
      onActiveApplicantTabChange={onActiveApplicantTabChange}
      onAppliedApplicantsSearchChange={onAppliedApplicantsSearchChange}
      onAppliedApplicantsSort={onAppliedApplicantsSort}
      onAppliedApplicantsOpenMenuChange={onAppliedApplicantsOpenMenuChange}
      onAppliedApplicantsPageChange={onAppliedApplicantsPageChange}
      onAppliedApplicantsPageSizeChange={onAppliedApplicantsPageSizeChange}
      onAppliedApplicantPinToggle={onAppliedApplicantPinToggle}
      onPotentialApplicantsSearchChange={onPotentialApplicantsSearchChange}
      onPotentialApplicantsSort={onPotentialApplicantsSort}
      onPotentialApplicantsOpenMenuChange={onPotentialApplicantsOpenMenuChange}
      onPotentialApplicantsPageChange={onPotentialApplicantsPageChange}
      onPotentialApplicantsPageSizeChange={onPotentialApplicantsPageSizeChange}
      onPotentialApplicantPinToggle={onPotentialApplicantPinToggle}
      onApplicantClick={onApplicantClick}
      onApplicantFilterChange={onApplicantFilterChange}
      onAiSearch={onAiSearch}
      onClearFilters={onClearFilters}
    />
  );
}
