import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/lib/auth';
import { logAudit } from '@/lib/auditLog';
import { getPool } from '@/lib/db';
import { executeWithApiKeyFallback } from '@/lib/aiApiKeyManager';

export const dynamic = 'force-dynamic';


export async function POST(request: NextRequest) {
  const session = await getServerSession(authOptions);
  
  if (!session?.user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const body = await request.json();
    const { title, department, positionLevel } = body;

    if (!title || !department) {
      return NextResponse.json(
        { error: 'Title and department are required' },
        { status: 400 }
      );
    }



    // Create a comprehensive prompt for job description generation
    const prompt = `Generate a professional job description for a ${positionLevel || 'professional'} ${title} position in the ${department} department.

Please include:
1. Job Summary
2. Key Responsibilities (5-8 bullet points)
3. Required Qualifications
4. Preferred Qualifications
5. Key Competencies

Format the response in HTML with h2 and h3 headings and bullet points (ul, li). Make it professional and comprehensive.

Return ONLY the HTML-formatted job description without any additional text or explanations.`;

    // Call Google Gemini API with fallback
    const result = await executeWithApiKeyFallback(async (apiKey) => {
      const url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent";
      
      const fetchRes = await fetch(url, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-goog-api-key": apiKey,
        },
        body: JSON.stringify({
          contents: [
            {
              role: "user",
              parts: [{ text: prompt }]
            }
          ]
        }),
      });

      if (!fetchRes.ok) {
        const errorText = await fetchRes.text();
        throw new Error(`Gemini API error: ${fetchRes.status} ${fetchRes.statusText} - ${errorText}`);
      }

      const data = await fetchRes.json();
      
      // Check for API errors
      if (data.error) {
        console.error('Gemini API error:', data.error);
        throw new Error(`Gemini API error: ${data.error.message || JSON.stringify(data.error)}`);
      }
      
      let generatedDescription = data.candidates?.[0]?.content?.parts?.[0]?.text || "";

      if (!generatedDescription.trim()) {
        console.error('Empty response from Gemini API');
        throw new Error('No content generated by AI');
      }

      return generatedDescription;
    }, 'Generate Job Description');

    if (!result.success) {
      console.error('AI Job Description: All API keys failed');
      return NextResponse.json(
        { 
          error: 'AI features are not available due to API key failures. Please check your API key configuration.',
          attempts: result.attempts,
          lastError: result.error
        },
        { status: 503 }
      );
    }

    let generatedDescription = result.data;

    // Clean up the response - remove markdown code blocks if present
    generatedDescription = generatedDescription
      .replace(/```html\s*/gi, '')  // Remove opening ```html
      .replace(/```\s*$/gi, '')     // Remove closing ```
      .trim();

    // Log the AI generation activity
    await logAudit(
      'AUDIT',
      `AI job description generated for position: ${title} in ${department}`,
      'API:AI:GenerateJobDescription',
      session.user.id,
      { title, department, positionLevel }
    );

    return NextResponse.json({
      description: generatedDescription,
      success: true
    });

  } catch (error) {
    console.error('Error generating job description:', error);
    await logAudit(
      'ERROR',
      `Failed to generate job description: ${(error as Error).message}`,
      'API:AI:GenerateJobDescription',
      session.user?.id
    );
    
    return NextResponse.json(
      { error: `Failed to generate job description: ${(error as Error).message}` },
      { status: 500 }
    );
  }
} 