apiVersion: v1
kind: ConfigMap
metadata:
  name: fitscan-config
  namespace: ba-fitscan
data:
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  APP_TIMEZONE: "Asia/Bangkok"
  STORAGE_PROVIDER: "s3-compatible"
  STORAGE_BUCKET: "fitscan"
  SKIP_MIGRATIONS: "false"
  SKIP_SEED: "false"
