apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fitscan-app-pdb
  namespace: fitscan
  labels:
    app.kubernetes.io/name: fitscan
    app.kubernetes.io/component: app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: fitscan-app
  unhealthyPodEvictionPolicy: IfHealthyBudget

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-pdb
  namespace: fitscan
  labels:
    app.kubernetes.io/name: fitscan
    app.kubernetes.io/component: postgres
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: postgres
  unhealthyPodEvictionPolicy: IfHealthyBudget

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: minio-pdb
  namespace: fitscan
  labels:
    app.kubernetes.io/name: fitscan
    app.kubernetes.io/component: minio
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: minio
  unhealthyPodEvictionPolicy: IfHealthyBudget

