apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitscan-app
  namespace: fitscan
  labels:
    app.kubernetes.io/name: fitscan
    app.kubernetes.io/component: app
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitscan-processor
  namespace: fitscan
  labels:
    app.kubernetes.io/name: fitscan
    app.kubernetes.io/component: processor
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: fitscan
  labels:
    app.kubernetes.io/name: fitscan
    app.kubernetes.io/component: postgres
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio
  namespace: fitscan
  labels:
    app.kubernetes.io/name: fitscan
    app.kubernetes.io/component: minio
automountServiceAccountToken: false

