import { z } from "zod";

export const preferenceSchema = z.object({
  themePreference: z.enum(["light", "dark", "system"]).optional(),
  appName: z.string().optional(),
  appLogoDataUrl: z.string().nullable().optional(),
  appFaviconDataUrl: z.string().nullable().optional(),
  loginPageLogoLightMode: z.string().nullable().optional(),
  loginPageLogoDarkMode: z.string().nullable().optional(),
  sidebarLogoCollapsedLightMode: z.string().nullable().optional(),
  sidebarLogoExpandedLightMode: z.string().nullable().optional(),
  sidebarLogoCollapsedDarkMode: z.string().nullable().optional(),
  sidebarLogoExpandedDarkMode: z.string().nullable().optional(),
  showLogoOnly: z.boolean().optional(),
  loginBackgroundType: z.enum(["image", "gradient", "solid"]).optional(),
  loginBackgroundGradientStart: z.string().optional(),
  loginBackgroundGradientEnd: z.string().optional(),
  loginBackgroundColor: z.string().optional(),
  loginPageBackgroundImageUrl: z.string().nullable().optional(),
  sidebarBackgroundBlurPercent: z.coerce.number().min(0).max(100).optional(),
  sidebarBackgroundTranslucencyPercent: z.coerce.number().min(0).max(100).optional(),
  sidebarBgStartL: z.string().optional(),
  sidebarBgEndL: z.string().optional(),
  sidebarTextL: z.string().optional(),
  sidebarActiveBgStartL: z.string().optional(),
  sidebarActiveBgEndL: z.string().optional(),
  sidebarActiveTextL: z.string().optional(),
  sidebarHoverBgL: z.string().optional(),
  sidebarHoverTextL: z.string().optional(),
  sidebarBorderL: z.string().optional(),
  buttonTextColorL: z.string().optional(),
  buttonTextColorD: z.string().optional(),
  primaryButtonShadowL: z.string().nullable().optional(),
  primaryButtonShadowHoverL: z.string().nullable().optional(),
  primaryButtonShadowD: z.string().nullable().optional(),
  primaryButtonShadowHoverD: z.string().nullable().optional(),
  sidebarBgStartD: z.string().optional(),
  sidebarBgEndD: z.string().optional(),
  sidebarTextD: z.string().optional(),
  sidebarActiveBgStartD: z.string().optional(),
  sidebarActiveBgEndD: z.string().optional(),
  sidebarActiveTextD: z.string().optional(),
  sidebarHoverBgD: z.string().optional(),
  sidebarHoverTextD: z.string().optional(),
  sidebarBorderD: z.string().optional(),
}).and(z.record(z.string(), z.unknown().optional()));

export type SystemPreferenceInput = z.infer<typeof preferenceSchema>;
