export const essSidebarConfigData = {
  id: "ess",
  label: "ESS",
  icon: "Identification",
  items: [
    {
      label: "My Profile",
      icon: "Identification",
      href: "/ess/profile",
      description: "Personal details and profile change requests",
      section: "Employee service",
    },
    {
      label: "My Requests",
      icon: "ClipboardCheck",
      href: "/ess/requests",
      description: "Track profile and document approval requests",
      section: "Employee service",
    },
    {
      label: "My Onboarding",
      icon: "ListTodo",
      href: "/ess/onboarding",
      description: "Complete onboarding tasks and follow progress",
      section: "Employee service",
    },
    {
      label: "My Leave",
      icon: "CalendarDays",
      href: "/ess/leave",
      description: "Leave balances, requests, and history",
      section: "Employee service",
    },
    {
      label: "My Attendance",
      icon: "Calendar",
      href: "/ess/attendance",
      description: "Recent attendance, exceptions, and shift schedule",
      section: "Employee service",
    },
    {
      label: "Shift Requests",
      icon: "CalendarDays",
      href: "/ess/shift-requests",
      description: "Request schedule changes, swaps, or open shifts",
      section: "Employee service",
    },
    {
      label: "Attendance Corrections",
      icon: "Clock",
      href: "/ess/attendance-corrections",
      description: "Correct missing or inaccurate attendance records",
      section: "Employee service",
    },
    {
      label: "Overtime Requests",
      icon: "Clock",
      href: "/ess/overtime",
      description: "Submit and track overtime requests",
      section: "Employee service",
    },
    {
      label: "My Documents",
      icon: "Folder",
      href: "/ess/documents",
      description: "Employee documents and requested uploads",
      section: "Employee service",
    },
    {
      label: "Expenses",
      icon: "Banknotes",
      href: "/ess/expenses",
      description: "Create and track your expense claims",
      section: "Employee service",
    },
    {
      label: "Payslips",
      icon: "FileText",
      href: "/ess/payslips",
      description: "View released payroll statements",
      section: "Employee service",
    },
    {
      label: "My Benefits",
      icon: "Heart",
      href: "/ess/benefits",
      description: "Browse available plans and apply for benefit coverage",
      section: "Employee service",
    },
    {
      label: "My Performance",
      icon: "BarChart3",
      href: "/ess/performance",
      description: "Goals, reviews, and employee acknowledgements",
      section: "Growth",
    },
    {
      label: "Career Opportunities",
      icon: "Briefcase",
      href: "/ess/opportunities",
      description: "Explore and apply for published internal opportunities",
      section: "Growth",
    },
    {
      label: "My Surveys",
      icon: "ListTodo",
      href: "/ess/surveys",
      description: "Assigned surveys and response history",
      section: "Growth",
    },
    {
      label: "My Team",
      icon: "Users",
      href: "/ess/team",
      description: "Manager approvals and direct reports",
      section: "Manager service",
    },
  ],
};
