import {
  APP_BRANDING_SETTING_KEYS,
  AUTH_AND_LOGIN_SETTING_KEYS,
  EVALUATE_REPORT_SETTING_KEYS,
  THEME_AND_HEADER_SETTING_KEYS,
} from "./system-settings-route-keys-core";
import {
  AI_PROCESSING_SETTING_KEYS,
  FEATURE_AND_SECURITY_SETTING_KEYS,
  INTERVIEW_AND_EMAIL_SETTING_KEYS,
  LOCKOUT_SETTING_KEYS,
  PWA_AND_SPLASH_SETTING_KEYS,
} from "./system-settings-route-keys-processing";
import {
  SIDEBAR_CONTAINER_SETTING_KEYS,
  SIDEBAR_ICON_AND_GROUP_SETTING_KEYS,
  SIDEBAR_MENU_ITEM_SETTING_KEYS,
} from "./system-settings-route-keys-sidebar";

export const SYSTEM_SETTING_KEYS = [
  ...APP_BRANDING_SETTING_KEYS,
  ...AUTH_AND_LOGIN_SETTING_KEYS,
  ...THEME_AND_HEADER_SETTING_KEYS,
  ...EVALUATE_REPORT_SETTING_KEYS,
  ...SIDEBAR_CONTAINER_SETTING_KEYS,
  "buttonTextColorL",
  "buttonTextColorD",
  ...SIDEBAR_MENU_ITEM_SETTING_KEYS,
  ...SIDEBAR_ICON_AND_GROUP_SETTING_KEYS,
  ...AI_PROCESSING_SETTING_KEYS,
  ...FEATURE_AND_SECURITY_SETTING_KEYS,
  ...PWA_AND_SPLASH_SETTING_KEYS,
  ...INTERVIEW_AND_EMAIL_SETTING_KEYS,
  ...LOCKOUT_SETTING_KEYS,
] as const;
