export const APP_BRANDING_SETTING_KEYS = [
  "appName",
  "appLogoDataUrl",
  "appFaviconDataUrl",
  "appThemePreference",
  "defaultMatchCriteria",
  "organizationName",
  "organizationAddress",
  "organizationContact",
  "organizationLogoDataUrl",
  "qrCodeLogo",
  "appFontFamily",
] as const;

export const AUTH_AND_LOGIN_SETTING_KEYS = [
  "azureAdClientId",
  "azureAdClientSecret",
  "azureAdTenantId",
  "basicAuthEnabled",
  "globalTwoFactorEnabled",
  "loginPageDevToolsProtectionEnabled",
  "loginPageLogoLightMode",
  "loginPageLogoDarkMode",
  "loginPageBackgroundType",
  "loginPageBackgroundImageUrl",
  "loginPageBackgroundColor1",
  "loginPageBackgroundColor2",
  "loginPageLayoutType",
  "themePreference",
  "loginBackgroundType",
  "loginBackgroundGradientStart",
  "loginBackgroundGradientEnd",
  "loginBackgroundGradient",
  "loginBackgroundColor",
  "showLogoOnly",
  "loginPageLogoSize",
  "loginPageContent",
  "loginPageFooter",
  "loginBackgroundTypeMobile",
  "loginPageBackgroundImageUrlMobile",
  "loginBackgroundGradientStartMobile",
  "loginBackgroundGradientEndMobile",
  "loginBackgroundColorMobile",
  "loginBackgroundGradientMobile",
  "mobileLoginLogoDataUrl",
] as const;

export const THEME_AND_HEADER_SETTING_KEYS = [
  "primaryGradientStart",
  "primaryGradientEnd",
  "primaryGradient",
  "primaryButtonShadowL",
  "primaryButtonShadowHoverL",
  "primaryButtonShadowD",
  "primaryButtonShadowHoverD",
  "mobileHeaderGradient1",
  "mobileHeaderGradient2",
  "mobileHeaderGradient3",
  "mobileHeaderGradient4",
  "mobileHeaderFontColor",
  "mobileHeaderBackgroundType",
  "headerBackgroundType",
  "headerBackgroundGradient",
  "headerBackgroundColor",
  "headerBackgroundImageUrl",
  "headerTextColor",
] as const;

export const EVALUATE_REPORT_SETTING_KEYS = [
  "evaluateHeaderBackgroundType",
  "evaluateHeaderBackgroundGradientStart",
  "evaluateHeaderBackgroundGradientEnd",
  "evaluateHeaderBackgroundGradient",
  "evaluateHeaderBackgroundColor",
  "evaluateHeaderBackgroundImageUrl",
  "evaluateHeaderTextColor",
  "evaluatePlatformLogoDataUrl",
  "evaluateReportLogoDataUrl",
] as const;
