export const AI_PROCESSING_SETTING_KEYS = [
  "resumeProcessingWebhookUrl",
  "resumeProcessingWebhookToken",
  "resumeProcessingWebhookResponseMode",
  "resumeProcessingWebhookTimeout",
  "webhookConnectionTimeout",
  "preventDuplicateWebhookProcessing",
  "geminiApiKey",
  "openaiApiKey",
  "aiPowerSearchSystemPrompt",
  "jobDescriptionSystemPrompt",
  "applicantEvaluationCriteriaPrompt",
  "aiProviderSelection",
  "geminiModelSelection",
  "openaiModelSelection",
  "geminiApiKey_1",
  "geminiApiKey_2",
  "geminiApiKey_3",
  "geminiApiKey_4",
  "geminiApiKey_5",
  "geminiApiKey_1_errorCount",
  "geminiApiKey_2_errorCount",
  "geminiApiKey_3_errorCount",
  "geminiApiKey_4_errorCount",
  "geminiApiKey_5_errorCount",
  "geminiApiKey_1_lastError",
  "geminiApiKey_2_lastError",
  "geminiApiKey_3_lastError",
  "geminiApiKey_4_lastError",
  "geminiApiKey_5_lastError",
  "geminiApiKey_1_lastUsed",
  "geminiApiKey_2_lastUsed",
  "geminiApiKey_3_lastUsed",
  "geminiApiKey_4_lastUsed",
  "geminiApiKey_5_lastUsed",
  "openaiApiKey_1",
  "openaiApiKey_2",
  "openaiApiKey_3",
  "openaiApiKey_4",
  "openaiApiKey_5",
  "openaiApiKey_1_errorCount",
  "openaiApiKey_2_errorCount",
  "openaiApiKey_3_errorCount",
  "openaiApiKey_4_errorCount",
  "openaiApiKey_5_errorCount",
  "openaiApiKey_1_lastError",
  "openaiApiKey_2_lastError",
  "openaiApiKey_3_lastError",
  "openaiApiKey_4_lastError",
  "openaiApiKey_5_lastError",
  "openaiApiKey_1_lastUsed",
  "openaiApiKey_2_lastUsed",
  "openaiApiKey_3_lastUsed",
  "openaiApiKey_4_lastUsed",
  "openaiApiKey_5_lastUsed",
  "maxConcurrentProcessors",
  "processorIntervalMs",
  "processorQuietMode",
  "processorConnectionTimeoutMs",
  "processorRequestTimeoutMs",
  "processQueueEnabled",
] as const;

export const FEATURE_AND_SECURITY_SETTING_KEYS = [
  "jobMatchFeatureEnabled",
  "pwaEnabled",
  "exportImportFeatureEnabled",
  "warningCriteriaEnabled",
  "screenCaptureProtectionEnabled",
  "rightClickProtectionEnabled",
] as const;

export const PWA_AND_SPLASH_SETTING_KEYS = [
  "splashBackgroundColor",
  "splashLogoDataUrl",
  "splashAnimationType",
  "pwaName",
  "pwaShortName",
  "pwaDescription",
  "pwaThemeColor",
  "pwaBackgroundColor",
  "pwaAppleMobileWebAppTitle",
  "pwaAppleMobileWebAppStatusBarStyle",
] as const;

export const INTERVIEW_AND_EMAIL_SETTING_KEYS = [
  "interviewerSelectedBackgroundColor",
  "interviewerSelectedTextColor",
  "interviewerSelectedBorderColor",
  "interviewerSelectedBorderWidth",
  "interviewerNonSelectedBackgroundColor",
  "interviewerNonSelectedTextColor",
  "interviewerNonSelectedBorderColor",
  "interviewerNonSelectedBorderWidth",
  "interviewerNameColor",
  "generativeAICanvasMode",
  "drawerStyle",
  "emailServiceEnabled",
  "emailSmtpHost",
  "emailSmtpPort",
  "emailSmtpSecure",
  "emailSmtpUser",
  "emailSmtpPassword",
  "emailFromAddress",
  "emailFromName",
  "emailTemplateInterviewInvitation",
  "emailTemplateInterviewInvitationSubject",
  "emailTemplateInterviewInvitationEditorMode",
  "interviewInvitationFeatureEnabled",
  "hiringManagerRestrictToAssignedPositions",
  "azureMeetingRoomsEnabled",
  "icsDescriptionTemplate",
] as const;

export const LOCKOUT_SETTING_KEYS = [
  "lockoutAlertEmails",
  "lockoutWebhookUrl",
] as const;
