"use client";

import * as React from "react";
import Link from "next/link";
import { ArrowRight, CheckCircle2, ClipboardList, Clock3, Loader2, LockKeyhole } from "lucide-react";
import toast from "react-hot-toast";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

type AssignedSurvey = { id: string; title: string; description?: string | null; privacyMode: string; estimatedMinutes: number; isRequired: boolean; closesAt?: string | null; participationStatus: string };

export function AssignedSurveysWorkspace() {
  const [surveys,setSurveys] = React.useState<AssignedSurvey[]>([]); const [loading,setLoading] = React.useState(true);
  React.useEffect(() => { void (async () => { try { const response = await fetch("/api/surveys/assigned", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.message || "Unable to load assigned surveys."); setSurveys(body.surveys || []); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to load assigned surveys."); } finally { setLoading(false); } })(); }, []);
  const open = surveys.filter(item => item.participationStatus !== "completed"); const completed = surveys.filter(item => item.participationStatus === "completed");
  return <main className="min-h-screen bg-muted/20 p-4 sm:p-6"><div className="mx-auto max-w-5xl space-y-5"><header className="border-b border-border pb-5"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Employee service</p><h1 className="mt-1 text-2xl font-bold">My surveys</h1><p className="mt-1 text-sm text-muted-foreground">Complete required and optional surveys assigned to you.</p></header>{loading ? <div className="grid min-h-64 place-items-center"><Loader2 className="h-6 w-6 animate-spin" /></div> : <><section className="rounded-2xl border border-border bg-background"><div className="border-b border-border p-5"><h2 className="font-semibold">Needs your response</h2><p className="text-sm text-muted-foreground">{open.length} open assignment{open.length === 1 ? "" : "s"}</p></div><div className="divide-y divide-border">{open.map(item => <SurveyCard key={item.id} survey={item} />)}{open.length === 0 && <div className="p-12 text-center"><CheckCircle2 className="mx-auto h-9 w-9 text-emerald-600" /><h3 className="mt-3 font-semibold">You’re all caught up</h3><p className="mt-1 text-sm text-muted-foreground">No surveys currently need your response.</p></div>}</div></section>{completed.length > 0 && <section className="rounded-2xl border border-border bg-background"><div className="border-b border-border p-5"><h2 className="font-semibold">Completed</h2></div><div className="divide-y divide-border">{completed.map(item => <SurveyCard key={item.id} survey={item} />)}</div></section>}</>}</div></main>;
}
function SurveyCard({ survey }: { survey: AssignedSurvey }) { const complete = survey.participationStatus === "completed"; return <article className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><span className="grid h-11 w-11 shrink-0 place-items-center bg-primary/10 text-primary">{complete ? <CheckCircle2 className="h-5 w-5" /> : <ClipboardList className="h-5 w-5" />}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{survey.title}</h3>{survey.isRequired && <Badge>Required</Badge>}<Badge variant="outline" className="capitalize"><LockKeyhole className="mr-1 h-3 w-3" />{survey.privacyMode}</Badge></div>{survey.description && <p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{survey.description}</p>}<p className="mt-2 flex items-center gap-1 text-xs text-muted-foreground"><Clock3 className="h-3.5 w-3.5" />About {survey.estimatedMinutes} min{survey.closesAt ? ` · Due ${new Date(survey.closesAt).toLocaleDateString()}` : ""}</p></div><Button asChild variant={complete ? "outline" : "default"}><Link href={`/survey/${survey.id}/respond`}>{complete ? "View completion" : survey.participationStatus === "in_progress" ? "Continue" : "Start survey"}<ArrowRight className="ml-2 h-4 w-4" /></Link></Button></article>; }
