"use client";

import * as React from "react";
import { BarChart3, Download, Loader2, LockKeyhole, TrendingUp, Users } from "lucide-react";
import toast from "react-hot-toast";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { SurveyAnalytics, SurveyDetail } from "./survey-workspace-types";

export function SurveyReportTab({ survey }: { survey: SurveyDetail }) {
  const [analytics, setAnalytics] = React.useState<SurveyAnalytics | null>(null);
  const [loading, setLoading] = React.useState(true);
  React.useEffect(() => { let cancelled = false; void (async () => { try { const response = await fetch(`/api/surveys/${survey.id}/analytics`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.message || "Unable to load report."); if (!cancelled) setAnalytics(body.analytics); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to load report."); } finally { if (!cancelled) setLoading(false); } })(); return () => { cancelled = true; }; }, [survey.id]);
  if (loading) return <div className="grid min-h-80 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-muted-foreground" /></div>;
  if (!analytics) return <div className="rounded-2xl border border-border bg-background p-10 text-center">Report unavailable.</div>;
  const { participation } = analytics;
  return <div className="space-y-5">
    <section className="flex flex-col justify-between gap-4 border-b border-border pb-5 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Live report</p><h2 className="mt-1 text-2xl font-bold">What your people said</h2><p className="mt-1 text-sm text-muted-foreground">Results update as responses arrive. Privacy suppression is applied before this screen receives data.</p></div><div className="flex gap-2"><Button asChild variant="outline"><a href={`/api/surveys/${survey.id}/export?format=csv`}><Download className="mr-2 h-4 w-4" />CSV</a></Button><Button asChild variant="outline"><a href={`/api/surveys/${survey.id}/export?format=xlsx`}><Download className="mr-2 h-4 w-4" />Excel</a></Button></div></section>
    <section className="grid overflow-hidden rounded-2xl border border-border bg-background sm:grid-cols-4"><Metric label="Invited" value={participation.invited} icon={Users} /><Metric label="Completed" value={participation.completed} icon={BarChart3} /><Metric label="In progress" value={participation.inProgress} icon={TrendingUp} /><Metric label="Response rate" value={participation.responseRate === null ? "—" : `${participation.responseRate}%`} icon={TrendingUp} /></section>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_390px]">
      <section className="rounded-2xl border border-border bg-background"><div className="border-b border-border p-5"><h3 className="font-semibold">Question results</h3><p className="text-sm text-muted-foreground">Distribution and averages across submitted responses.</p></div><div className="divide-y divide-border">{analytics.questionResults.map((question,index) => <article key={question.questionId} className="p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold text-muted-foreground">QUESTION {index + 1}</p><h4 className="mt-1 font-semibold">{question.text}</h4></div><Badge variant="outline">{question.responseCount} answers</Badge></div>{question.suppressed ? <div className="mt-4 flex items-center gap-2 bg-muted/50 p-4 text-sm text-muted-foreground"><LockKeyhole className="h-4 w-4" />{question.suppressionReason}</div> : <div className="mt-4 space-y-3">{question.average !== null && question.average !== undefined && <p className="text-sm">Average <strong className="ml-2 text-2xl">{question.average}</strong></p>}{question.distribution?.slice(0,12).map(item => { const max = Math.max(...(question.distribution?.map(value => value.value) || [1])); return <div key={item.label} className="grid grid-cols-[minmax(90px,180px)_1fr_36px] items-center gap-3 text-sm"><span className="truncate" title={item.label}>{item.label}</span><div className="h-2 bg-muted"><div className="h-full w-full origin-left bg-primary transition-transform" style={{ transform: `scaleX(${Math.max(3,(item.value/max)*100) / 100})` }} /></div><strong className="text-right">{item.value}</strong></div>; })}</div>}</article>)}</div></section>
      <aside className="rounded-2xl border border-border bg-background"><div className="border-b border-border p-5"><h3 className="font-semibold">Participation by department</h3><p className="text-sm text-muted-foreground">Small anonymous groups remain hidden.</p></div><div className="divide-y divide-border">{analytics.departmentBreakdown.map(row => <div key={row.department} className="p-4"><div className="flex items-center justify-between gap-3"><span className="font-medium">{row.department}</span>{row.suppressed ? <Badge variant="secondary"><LockKeyhole className="mr-1 h-3 w-3" />Protected</Badge> : <strong>{row.responseRate ?? 0}%</strong>}</div><p className="mt-1 text-xs text-muted-foreground">{row.completed} of {row.invited} completed</p>{!row.suppressed && <div className="mt-2 h-1.5 bg-muted"><div className="h-full bg-emerald-600" style={{ width: `${row.responseRate || 0}%` }} /></div>}</div>)}</div></aside>
    </div>
  </div>;
}

function Metric({ label, value, icon: Icon }: { label: string; value: string | number; icon: React.ComponentType<{ className?: string }> }) { return <div className="border-b border-border p-5 last:border-b-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">{label}</p><Icon className="h-4 w-4 text-primary" /></div><p className="mt-2 text-3xl font-bold tracking-tight">{value}</p></div>; }
