import type { OrganizationProfile } from '@/lib/organization-profile';

export type EmailEditorMode = 'wysiwyg' | 'html';
export type EmailProvider = 'smtp' | 'resend' | 'mailersend' | 'brevo' | 'sendgrid' | 'mailgun' | 'postmark';
export type ResumeProcessingMode = 'built-in' | 'external';
export type PublicApplicationMode = 'ai' | 'manual' | 'choice';
export type BroadcastBannerId = 'none' | 'one' | 'two' | 'three';
export type BroadcastBannerTone = 'info' | 'success' | 'warning' | 'critical';
export type BroadcastSmsProvider = 'webhook' | 'twilio';

export interface SystemSettingsViewState {
  resumeProcessingMode: ResumeProcessingMode;
  builtInProcessorNodeName: string;
  builtInResumeExtractionPrompt: string;
  builtInApplicantMappingPrompt: string;
  builtInJobMatchingPrompt: string;
  maxConcurrentProcessors: number;
  dataOperationsMaxConcurrentJobs: number;
  dataOperationsMaxQueuedJobsPerUser: number;
  dataOperationsMaxImportFileSizeMb: number;
  dataOperationsJobRetentionDays: number;
  resumeProcessingWebhookUrl: string;
  resumeProcessingWebhookToken: string;
  resumeProcessingWebhookResponseMode: string;
  resumeProcessingWebhookTimeout: number;
  processQueueEnabled: boolean;
  processorIntervalMs: number;
  processorQuietMode: boolean;
  processorConnectionTimeoutMs: number;
  processorRequestTimeoutMs: number;
  emailServiceEnabled: boolean;
  emailProvider: EmailProvider;
  emailApiKey: string;
  emailMailgunDomain: string;
  emailSmtpHost: string;
  emailSmtpPort: number;
  emailSmtpSecure: boolean;
  emailSmtpUser: string;
  emailSmtpPassword: string;
  emailFromAddress: string;
  emailFromName: string;
  emailTemplateInterviewInvitation: string;
  emailTemplateInterviewInvitationSubject: string;
  emailTemplateInterviewInvitationEditorMode: EmailEditorMode;
  emailTemplateOfferLetter: string;
  emailTemplateOfferLetterSubject: string;
  emailTemplateOfferLetterEditorMode: EmailEditorMode;
  icsDescriptionTemplate: string;
  organizationName: string;
  organizationAddress: string;
  organizationContact: string;
  organizationProfile: OrganizationProfile;
  organizationLogoPreviewUrl: string | null;
  savedOrganizationLogoUrl: string | null;
  interviewInvitationFeatureEnabled: boolean;
  azureMeetingRoomsEnabled: boolean;
  azureAdClientId: string;
  azureAdClientSecret: string;
  azureAdTenantId: string;
  basicAuthEnabled: boolean;
  jobDescriptionSystemPrompt: string;
  applicantEvaluationCriteriaPrompt: string;
  defaultMatchCriteria: string;
  showLogoOnly: boolean;
  jobMatchFeatureEnabled: boolean;
  publicApplicationsEnabled: boolean;
  publicApplicationMode: PublicApplicationMode;
  publicApplicationsRequireCaptcha: boolean;
  publicApplicationsSendApplicantConfirmation: boolean;
  publicApplicationsNotifyRecruiter: boolean;
  pwaEnabled: boolean;
  pwaName: string;
  pwaShortName: string;
  pwaDescription: string;
  pwaThemeColor: string;
  pwaBackgroundColor: string;
  pwaAppleMobileWebAppTitle: string;
  pwaAppleMobileWebAppStatusBarStyle: string;
  exportImportFeatureEnabled: boolean;
  hiringManagerRestrictToAssignedPositions: boolean;
  screenCaptureProtectionEnabled: boolean;
  rightClickProtectionEnabled: boolean;
  loginPageDevToolsProtectionEnabled: boolean;
  globalTwoFactorEnabled: boolean;
  passwordSetupLinkExpiryHours: number;
  faultDetectionDeviceChangeEnabled: boolean;
  faultDetectionDeviceChangeThreshold: number;
  faultDetectionDeviceChangeWindowHours: number;
  faultDetectionLocationSpoofingEnabled: boolean;
  faultDetectionLocationMaxSpeedKmh: number;
  faultDetectionLocationMinDistanceKm: number;
  lockoutAlertEmails: string[];
  lockoutWebhookUrl: string;
  serviceDeskKnowledgeBaseUrl: string;
  serviceDeskKnowledgeBaseApiKey: string;
  serviceDeskKnowledgeBaseCollectionName: string;
  serviceDeskKnowledgeBaseRequestTimeoutMs: number;
  broadcastEmailEnabled: boolean;
  broadcastSmsEnabled: boolean;
  broadcastSmsProvider: BroadcastSmsProvider;
  broadcastSmsWebhookUrl: string;
  broadcastSmsWebhookToken: string;
  broadcastSmsTwilioAccountSid: string;
  broadcastSmsTwilioAuthToken: string;
  broadcastSmsTwilioFromNumber: string;
  broadcastBannerActiveId: BroadcastBannerId;
  broadcastBannerOneTitle: string;
  broadcastBannerOneMessage: string;
  broadcastBannerOneTone: BroadcastBannerTone;
  broadcastBannerTwoTitle: string;
  broadcastBannerTwoMessage: string;
  broadcastBannerTwoTone: BroadcastBannerTone;
  broadcastBannerThreeTitle: string;
  broadcastBannerThreeMessage: string;
  broadcastBannerThreeTone: BroadcastBannerTone;
}

export type SystemSettingsSavePayload = Array<{ key: string; value: string }>;

export type SystemSettingsSaveState = Pick<
  SystemSettingsViewState,
  | 'maxConcurrentProcessors'
  | 'dataOperationsMaxConcurrentJobs'
  | 'dataOperationsMaxQueuedJobsPerUser'
  | 'dataOperationsMaxImportFileSizeMb'
  | 'dataOperationsJobRetentionDays'
  | 'resumeProcessingMode'
  | 'builtInProcessorNodeName'
  | 'builtInResumeExtractionPrompt'
  | 'builtInApplicantMappingPrompt'
  | 'builtInJobMatchingPrompt'
  | 'resumeProcessingWebhookUrl'
  | 'resumeProcessingWebhookToken'
  | 'resumeProcessingWebhookResponseMode'
  | 'resumeProcessingWebhookTimeout'
  | 'defaultMatchCriteria'
  | 'jobMatchFeatureEnabled'
  | 'publicApplicationsEnabled'
  | 'publicApplicationMode'
  | 'publicApplicationsRequireCaptcha'
  | 'publicApplicationsSendApplicantConfirmation'
  | 'publicApplicationsNotifyRecruiter'
  | 'processQueueEnabled'
  | 'pwaEnabled'
  | 'pwaName'
  | 'pwaShortName'
  | 'pwaDescription'
  | 'pwaThemeColor'
  | 'pwaBackgroundColor'
  | 'pwaAppleMobileWebAppTitle'
  | 'pwaAppleMobileWebAppStatusBarStyle'
  | 'exportImportFeatureEnabled'
  | 'hiringManagerRestrictToAssignedPositions'
  | 'processorIntervalMs'
  | 'processorQuietMode'
  | 'processorConnectionTimeoutMs'
  | 'processorRequestTimeoutMs'
  | 'emailServiceEnabled'
  | 'emailProvider'
  | 'emailApiKey'
  | 'emailMailgunDomain'
  | 'emailSmtpHost'
  | 'emailSmtpPort'
  | 'emailSmtpSecure'
  | 'emailSmtpUser'
  | 'emailSmtpPassword'
  | 'emailFromAddress'
  | 'emailFromName'
  | 'emailTemplateInterviewInvitation'
  | 'emailTemplateInterviewInvitationSubject'
  | 'emailTemplateInterviewInvitationEditorMode'
  | 'emailTemplateOfferLetter'
  | 'emailTemplateOfferLetterSubject'
  | 'emailTemplateOfferLetterEditorMode'
  | 'icsDescriptionTemplate'
  | 'organizationName'
  | 'organizationAddress'
  | 'organizationContact'
  | 'organizationProfile'
  | 'organizationLogoPreviewUrl'
  | 'screenCaptureProtectionEnabled'
  | 'rightClickProtectionEnabled'
  | 'loginPageDevToolsProtectionEnabled'
  | 'globalTwoFactorEnabled'
  | 'passwordSetupLinkExpiryHours'
  | 'faultDetectionDeviceChangeEnabled'
  | 'faultDetectionDeviceChangeThreshold'
  | 'faultDetectionDeviceChangeWindowHours'
  | 'faultDetectionLocationSpoofingEnabled'
  | 'faultDetectionLocationMaxSpeedKmh'
  | 'faultDetectionLocationMinDistanceKm'
  | 'azureAdClientId'
  | 'azureAdClientSecret'
  | 'azureAdTenantId'
  | 'basicAuthEnabled'
  | 'lockoutAlertEmails'
  | 'lockoutWebhookUrl'
  | 'serviceDeskKnowledgeBaseUrl'
  | 'serviceDeskKnowledgeBaseApiKey'
  | 'serviceDeskKnowledgeBaseCollectionName'
  | 'serviceDeskKnowledgeBaseRequestTimeoutMs'
  | 'jobDescriptionSystemPrompt'
  | 'applicantEvaluationCriteriaPrompt'
  | 'broadcastEmailEnabled'
  | 'broadcastSmsEnabled'
  | 'broadcastSmsProvider'
  | 'broadcastSmsWebhookUrl'
  | 'broadcastSmsWebhookToken'
  | 'broadcastSmsTwilioAccountSid'
  | 'broadcastSmsTwilioAuthToken'
  | 'broadcastSmsTwilioFromNumber'
  | 'broadcastBannerActiveId'
  | 'broadcastBannerOneTitle'
  | 'broadcastBannerOneMessage'
  | 'broadcastBannerOneTone'
  | 'broadcastBannerTwoTitle'
  | 'broadcastBannerTwoMessage'
  | 'broadcastBannerTwoTone'
  | 'broadcastBannerThreeTitle'
  | 'broadcastBannerThreeMessage'
  | 'broadcastBannerThreeTone'
>;
