import type { ApplicantsPageClientController } from './hooks/use-applicants-page-client-controller';

export function buildHeaderProps({
  ai,
  available,
  filters,
  importExport,
  layout,
  modals,
  scoring,
  settings,
  table,
}: ApplicantsPageClientController) {
  return {
    applicantSettings: settings.applicantSettings,
    isMobile: layout.isMobile,
    isLoading: table.isLoading,
    tableLoading: table.tableLoading,
    horizontalSelectedFitScoreGrades: filters.horizontalSelectedFitScoreGrades,
    horizontalSelectedMatchingFitScoreGrades: filters.horizontalSelectedMatchingFitScoreGrades,
    onGradeToggle: filters.onAppliedGradeToggle,
    onMatchingGradeToggle: filters.onMatchingGradeToggle,
    onClearAllHorizontalFitScoreFilters: filters.onClearHorizontalFitScores,
    applicantScoreCounts: scoring.applicantScoreCounts,
    aiSearchReasoning: ai.aiSearchReasoning,
    aiRecordCount: ai.aiRecordCount,
    isAiSearchActive: ai.isAiSearchActive,
    exportImportFeatureEnabled: settings.exportImportFeatureEnabled,
    onAddApplicant: () => modals.setIsAddModalOpen(true),
    onBulkUpload: () => modals.setIsBulkUploadModalOpen(true),
    onExport: importExport.handleExportApplicants,
    onImport: importExport.handleImportApplicants,
    onSettings: () => modals.setIsSettingsDrawerOpen(true),
    filters: filters.values,
    onFilterChange: filters.onFilterChange,
    onAiSearch: ai.handleAiSearch,
    onCancelAiSearch: ai.cancelAiSearch,
    onClearAllFilters: filters.onClearAll,
    availablePositions: available.positions,
    availableStages: available.stages,
    availableRecruiter: available.recruiters,
    availableSources: available.sources,
    isFilterDataLoading: scoring.isFilterDataLoading,
    advancedQuery: filters.advancedQuery,
    activeFilterCount: filters.activeFilterCount,
    isFilterPinned: layout.isFilterPinned,
    onToggleFilterPin: filters.onTogglePinned,
  };
}
