import type { ApplicantsPageClientController } from './hooks/use-applicants-page-client-controller';

export function buildTableAreaProps({
  ai,
  available,
  bulk,
  filters,
  modals,
  permissions,
  rows,
  settings,
  table,
}: ApplicantsPageClientController) {
  return {
    applicantsToRender: table.applicantsToRender,
    allPinnedApplicants: table.allPinnedApplicants,
    displayedApplicants: table.displayedApplicants,
    isLoading: table.isLoading,
    tableLoading: table.tableLoading,
    updateApplicantStatus: rows.updateApplicantStatus,
    handleDeleteApplicant: rows.handleDeleteApplicant,
    handleAssignRecruiter: rows.handleAssignRecruiter,
    handleAssignSource: rows.handleAssignSource,
    availablePositions: available.positions,
    availableStages: available.stages,
    availableRecruiter: available.recruiters,
    availableSources: available.sources,
    canEditApplicants: permissions.canEditApplicants,
    canDeleteApplicants: permissions.canDeleteApplicants,
    canChangeStatus: permissions.canChangeStatus,
    canBulkChangeStatus: permissions.canBulkChangeStatus,
    canViewDetailed: permissions.canViewDetailed,
    canAssignSource: permissions.canAssignSource,
    canAssignRecruiter: permissions.canAssignRecruiter,
    sortColumn: settings.sortColumn,
    sortDirection: settings.sortDirection,
    handleSortChange: settings.onSortChange,
    setSelectedPositionForEdit: modals.setSelectedPositionForEdit,
    refreshApplicantInList: table.refreshApplicantInList,
    fetchAllPinnedApplicants: table.fetchAllPinnedApplicants,
    selectedApplicantIds: bulk.selectedApplicantIds,
    setSelectedApplicantIds: bulk.setSelectedApplicantIds,
    handleBulkDelete: bulk.handleBulkDelete,
    handleBulkChangeStatus: bulk.handleBulkChangeStatus,
    handleBulkAssignRecruiter: bulk.handleBulkAssignRecruiter,
    handleBulkReprocess: bulk.handleBulkReprocess,
    setBulkNewStatus: modals.setBulkNewStatus,
    setBulkTransitionNotes: modals.setBulkTransitionNotes,
    setIsBulkStatusModalOpen: modals.setIsBulkStatusModalOpen,
    setBulkNewRecruiterId: modals.setBulkNewRecruiterId,
    setIsBulkRecruiterModalOpen: modals.setIsBulkRecruiterModalOpen,
    applicantSettings: settings.applicantSettings,
    tableHeight: table.tableHeight,
    page: table.page,
    setPage: table.setPage,
    pageSize: settings.pageSize,
    handlePageSizeChange: settings.onPageSizeChange,
    total: table.total,
    totalPages: table.totalPages,
    isAiSearchActive: ai.isAiSearchActive,
    aiMatchedApplicantIds: ai.aiMatchedApplicantIds,
    aiRecordCount: ai.aiRecordCount,
    filters: filters.values,
    fetchTableData: table.fetchTableData,
    aiMatchedApplicantIdsForRefresh: ai.aiMatchedApplicantIds,
  };
}
