import type { ApplicantsPageClientController } from './hooks/use-applicants-page-client-controller';

export function buildModalsProps({
  available,
  bulk,
  modals,
  refreshCurrentApplicantsPage,
  settings,
}: ApplicantsPageClientController) {
  return {
    isAddModalOpen: modals.isAddModalOpen,
    setIsAddModalOpen: modals.setIsAddModalOpen,
    availableStages: available.rawStages,
    availableSources: available.sources,
    onApplicantCreated: refreshCurrentApplicantsPage,
    isBulkUploadModalOpen: modals.isBulkUploadModalOpen,
    setIsBulkUploadModalOpen: modals.setIsBulkUploadModalOpen,
    onBulkUploadSuccess: refreshCurrentApplicantsPage,
    isImportModalOpen: modals.isImportModalOpen,
    setIsImportModalOpen: modals.setIsImportModalOpen,
    onImportSuccess: refreshCurrentApplicantsPage,
    isPositionDrawerOpen: modals.isPositionDrawerOpen,
    setIsPositionDrawerOpen: modals.setIsPositionDrawerOpen,
    selectedPositionForEdit: modals.selectedPositionForEdit,
    isSettingsDrawerOpen: modals.isSettingsDrawerOpen,
    setIsSettingsDrawerOpen: modals.setIsSettingsDrawerOpen,
    applicantSettings: settings.applicantSettings,
    onSettingsChange: settings.onSettingsChange,
    settingsLoading: settings.settingsLoading,
    settingsError: settings.settingsError,
    clearSettingsError: settings.clearSettingsError,
    isBulkStatusModalOpen: modals.isBulkStatusModalOpen,
    setIsBulkStatusModalOpen: modals.setIsBulkStatusModalOpen,
    bulkNewStatus: modals.bulkNewStatus,
    setBulkNewStatus: modals.setBulkNewStatus,
    bulkTransitionNotes: modals.bulkTransitionNotes,
    setBulkTransitionNotes: modals.setBulkTransitionNotes,
    selectedApplicantIds: bulk.selectedApplicantIds,
    handleBulkChangeStatus: bulk.handleBulkChangeStatus,
    availableStagesForBulk: available.rawStages,
    isBulkRecruiterModalOpen: modals.isBulkRecruiterModalOpen,
    setIsBulkRecruiterModalOpen: modals.setIsBulkRecruiterModalOpen,
    bulkNewRecruiterId: modals.bulkNewRecruiterId,
    setBulkNewRecruiterId: modals.setBulkNewRecruiterId,
    handleBulkAssignRecruiter: bulk.handleBulkAssignRecruiter,
    availableRecruiter: available.recruiters,
  };
}
