#!/usr/bin/env node
/**
 * Sync version from package.json to src/lib/version.ts
 * This ensures a single source of truth for the version number
 */

const fs = require('fs');
const path = require('path');

const packageJsonPath = path.join(__dirname, '..', 'package.json');
const versionTsPath = path.join(__dirname, '..', 'src', 'lib', 'version.ts');

try {
  // Read version from package.json
  const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
  const version = packageJson.version;

  if (!version) {
    throw new Error('Version not found in package.json');
  }

  // Generate version.ts content
  const versionTsContent = `// Version constant - auto-generated from package.json
// DO NOT EDIT THIS FILE MANUALLY - it is generated by scripts/sync-version.js
// To update the version, edit package.json and run: npm run sync-version
export const APP_VERSION = '${version}';
`;

  // Write to version.ts
  fs.writeFileSync(versionTsPath, versionTsContent, 'utf8');
  
  console.log(`✓ Version synced: ${version}`);
  console.log(`  package.json → src/lib/version.ts`);
} catch (error) {
  console.error('Error syncing version:', error.message);
  process.exit(1);
}

