-- Preserve only the query indexes that Prisma cannot fully represent, mapped
-- to the current Applicant/JobMatch schema. Basic single-column indexes are
-- already generated by the Prisma baseline and are intentionally not repeated.

CREATE INDEX IF NOT EXISTS "Applicant_fitScore_statusId_idx"
  ON "Applicant" ("fitScore", "statusId");

CREATE INDEX IF NOT EXISTS "JobMatch_applicant_id_fitScore_idx"
  ON "JobMatch" ("applicant_id", "fitScore");

-- GIN and partial indexes are not expressible in the Prisma datamodel but are
-- useful for applicant search/count workloads.
CREATE INDEX IF NOT EXISTS "Applicant_parsedData_gin_idx"
  ON "Applicant" USING GIN ("parsedData");

CREATE INDEX IF NOT EXISTS "Applicant_fitScore_not_null_idx"
  ON "Applicant" ("fitScore")
  WHERE "fitScore" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "Applicant_fitScore_null_idx"
  ON "Applicant" ("id")
  WHERE "fitScore" IS NULL OR "fitScore" = 0;
