import type { SystemPreferencesLoadedViewBuilderOptions } from "./system-preferences-loaded-view-types";

export function buildSystemPreferencesBrandingProps({
  canEdit,
  imageActions,
  state,
}: SystemPreferencesLoadedViewBuilderOptions) {
  return {
    canEdit,
    handleLogoFileChange: imageActions.handleLogoFileChange,
    logoPreviewUrl: state.logoPreviewUrl,
    removeSelectedLogo: imageActions.removeSelectedLogo,
    handleLoginPageLogoLightModeChange: imageActions.handleLoginPageLogoLightModeChange,
    loginPageLogoLightModePreviewUrl: state.loginPageLogoLightModePreviewUrl,
    setLoginPageLogoLightModePreviewUrl: state.setLoginPageLogoLightModePreviewUrl,
    setSavedLoginPageLogoLightModeUrl: state.setSavedLoginPageLogoLightModeUrl,
    handleLoginPageLogoDarkModeChange: imageActions.handleLoginPageLogoDarkModeChange,
    loginPageLogoDarkModePreviewUrl: state.loginPageLogoDarkModePreviewUrl,
    setLoginPageLogoDarkModePreviewUrl: state.setLoginPageLogoDarkModePreviewUrl,
    setSavedLoginPageLogoDarkModeUrl: state.setSavedLoginPageLogoDarkModeUrl,
    handleSidebarLogoCollapsedLightModeChange: imageActions.handleSidebarLogoCollapsedLightModeChange,
    sidebarLogoCollapsedLightModePreviewUrl: state.sidebarLogoCollapsedLightModePreviewUrl,
    setSidebarLogoCollapsedLightModePreviewUrl: state.setSidebarLogoCollapsedLightModePreviewUrl,
    setSavedSidebarLogoCollapsedLightModeUrl: state.setSavedSidebarLogoCollapsedLightModeUrl,
    handleSidebarLogoExpandedLightModeChange: imageActions.handleSidebarLogoExpandedLightModeChange,
    sidebarLogoExpandedLightModePreviewUrl: state.sidebarLogoExpandedLightModePreviewUrl,
    setSidebarLogoExpandedLightModePreviewUrl: state.setSidebarLogoExpandedLightModePreviewUrl,
    setSavedSidebarLogoExpandedLightModeUrl: state.setSavedSidebarLogoExpandedLightModeUrl,
    handleSidebarLogoCollapsedDarkModeChange: imageActions.handleSidebarLogoCollapsedDarkModeChange,
    sidebarLogoCollapsedDarkModePreviewUrl: state.sidebarLogoCollapsedDarkModePreviewUrl,
    setSidebarLogoCollapsedDarkModePreviewUrl: state.setSidebarLogoCollapsedDarkModePreviewUrl,
    setSavedSidebarLogoCollapsedDarkModeUrl: state.setSavedSidebarLogoCollapsedDarkModeUrl,
    handleSidebarLogoExpandedDarkModeChange: imageActions.handleSidebarLogoExpandedDarkModeChange,
    sidebarLogoExpandedDarkModePreviewUrl: state.sidebarLogoExpandedDarkModePreviewUrl,
    setSidebarLogoExpandedDarkModePreviewUrl: state.setSidebarLogoExpandedDarkModePreviewUrl,
    setSavedSidebarLogoExpandedDarkModeUrl: state.setSavedSidebarLogoExpandedDarkModeUrl,
    splashBackgroundColor: state.splashBackgroundColor,
    setSplashBackgroundColor: state.setSplashBackgroundColor,
    splashAnimationType: state.splashAnimationType,
    setSplashAnimationType: state.setSplashAnimationType,
    handleSplashLogoChange: imageActions.handleSplashLogoChange,
    splashLogoPreviewUrl: state.splashLogoPreviewUrl,
    removeSplashLogo: imageActions.removeSplashLogo,
    loginPageLogoSize: state.loginPageLogoSize,
    setLoginPageLogoSize: state.setLoginPageLogoSize,
    headerBackgroundType: state.headerBackgroundType,
    setHeaderBackgroundType: state.setHeaderBackgroundType,
    headerImagePreviewUrl: state.headerImagePreviewUrl,
    removeSelectedHeaderImage: imageActions.removeSelectedHeaderImage,
    handleHeaderImageFileChange: imageActions.handleHeaderImageFileChange,
    headerBackgroundGradient: state.headerBackgroundGradient,
    setHeaderBackgroundGradient: state.setHeaderBackgroundGradient,
    headerBackgroundColor: state.headerBackgroundColor,
    setHeaderBackgroundColor: state.setHeaderBackgroundColor,
    headerTextColor: state.headerTextColor,
    setHeaderTextColor: state.setHeaderTextColor,
    loginBackgroundType: state.loginBackgroundType,
    setLoginBackgroundType: state.setLoginBackgroundType,
    loginImagePreviewUrl: state.loginImagePreviewUrl,
    removeSelectedLoginImage: imageActions.removeSelectedLoginImage,
    handleLoginImageFileChange: imageActions.handleLoginImageFileChange,
    loginBackgroundGradient: state.loginBackgroundGradient,
    setLoginBackgroundGradient: state.setLoginBackgroundGradient,
    loginBackgroundColor: state.loginBackgroundColor,
    setLoginBackgroundColor: state.setLoginBackgroundColor,
    loginBackgroundTypeMobile: state.loginBackgroundTypeMobile,
    setLoginBackgroundTypeMobile: state.setLoginBackgroundTypeMobile,
    loginImagePreviewUrlMobile: state.loginImagePreviewUrlMobile,
    removeSelectedLoginImageMobile: imageActions.removeSelectedLoginImageMobile,
    handleLoginImageFileChangeMobile: imageActions.handleLoginImageFileChangeMobile,
    loginBackgroundGradientMobile: state.loginBackgroundGradientMobile,
    setLoginBackgroundGradientMobile: state.setLoginBackgroundGradientMobile,
    loginBackgroundColorMobile: state.loginBackgroundColorMobile,
    setLoginBackgroundColorMobile: state.setLoginBackgroundColorMobile,
    loginLayoutType: state.loginLayoutType,
    setLoginLayoutType: state.setLoginLayoutType,
  };
}
