import type { Dispatch, SetStateAction } from "react";

export type NullableFileSetter = Dispatch<SetStateAction<File | null>>;
export type NullableStringSetter = Dispatch<SetStateAction<string | null>>;

export type UseSystemPreferenceImageActionsInput = {
  showError: (message: string) => void;
  logoPreviewUrl: string | null;
  savedLogoUrl: string | null;
  loginImagePreviewUrl: string | null;
  savedLoginImageDataUrl: string | null;
  loginImagePreviewUrlMobile: string | null;
  savedLoginImageDataUrlMobile: string | null;
  evaluateHeaderImagePreviewUrl: string | null;
  savedEvaluateHeaderImageDataUrl: string | null;
  headerImagePreviewUrl: string | null;
  savedHeaderImageDataUrl: string | null;
  sidebarImagePreviewUrl: string | null;
  savedSidebarImageUrl: string | null;
  splashLogoPreviewUrl: string | null;
  savedSplashLogoDataUrl: string | null;
  setSelectedLogoFile: NullableFileSetter;
  setLogoPreviewUrl: NullableStringSetter;
  setSavedLogoUrl: NullableStringSetter;
  setLoginPageLogoLightModePreviewUrl: NullableStringSetter;
  setSavedLoginPageLogoLightModeUrl: NullableStringSetter;
  setLoginPageLogoDarkModePreviewUrl: NullableStringSetter;
  setSavedLoginPageLogoDarkModeUrl: NullableStringSetter;
  setSidebarLogoCollapsedLightModePreviewUrl: NullableStringSetter;
  setSavedSidebarLogoCollapsedLightModeUrl: NullableStringSetter;
  setSidebarLogoExpandedLightModePreviewUrl: NullableStringSetter;
  setSavedSidebarLogoExpandedLightModeUrl: NullableStringSetter;
  setSidebarLogoCollapsedDarkModePreviewUrl: NullableStringSetter;
  setSavedSidebarLogoCollapsedDarkModeUrl: NullableStringSetter;
  setSidebarLogoExpandedDarkModePreviewUrl: NullableStringSetter;
  setSavedSidebarLogoExpandedDarkModeUrl: NullableStringSetter;
  setSelectedLoginImageFile: NullableFileSetter;
  setLoginImagePreviewUrl: NullableStringSetter;
  setSavedLoginImageDataUrl: NullableStringSetter;
  setSelectedLoginImageFileMobile: NullableFileSetter;
  setLoginImagePreviewUrlMobile: NullableStringSetter;
  setSavedLoginImageDataUrlMobile: NullableStringSetter;
  setSelectedEvaluateHeaderImageFile: NullableFileSetter;
  setEvaluateHeaderImagePreviewUrl: NullableStringSetter;
  setSavedEvaluateHeaderImageDataUrl: NullableStringSetter;
  setSelectedHeaderImageFile: NullableFileSetter;
  setHeaderImagePreviewUrl: NullableStringSetter;
  setSavedHeaderImageDataUrl: NullableStringSetter;
  setSelectedSidebarImageFile: NullableFileSetter;
  setSidebarImagePreviewUrl: NullableStringSetter;
  setSavedSidebarImageUrl: NullableStringSetter;
  setSelectedSplashLogoFile: NullableFileSetter;
  setSplashLogoPreviewUrl: NullableStringSetter;
  setSavedSplashLogoDataUrl: NullableStringSetter;
};
