"use client";

import * as React from 'react';
import Link from 'next/link';
import { ArrowLeft, BookOpen, ChevronDown, ChevronUp, Eye, FileQuestion, GripVertical, Plus, Save, Send, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { cn } from '@/lib/utils';

type BlockType = 'text'|'video'|'attachment'|'acknowledgement'|'break'|'quiz'|'assignment';
type Block = { type: BlockType; title: string; required: boolean; content: Record<string, unknown> };
type Lesson = { title:string;description:string;estimatedMinutes:number;minimumActiveSeconds:number;blocks:Block[] };
type Section = { title:string;lessons:Lesson[] };
const newBlock=(type:BlockType):Block=>({type,title:type==='text'?'Reading':type[0].toUpperCase()+type.slice(1),required:true,content:type==='text'?{text:''}:type==='break'?{minutes:5}:type==='quiz'?{questions:[]}:{url:'',instructions:''}});
const newLesson=():Lesson=>({title:'Untitled lesson',description:'',estimatedMinutes:5,minimumActiveSeconds:30,blocks:[newBlock('text')]});

export function CourseStudio({ courseId }: { courseId: string }) {
  const [course,setCourse]=React.useState<Record<string,unknown>>({});
  const [sections,setSections]=React.useState<Section[]>([{title:'Getting started',lessons:[newLesson()]}]);
  const [rules,setRules]=React.useState({passingScore:80,maxAttempts:3,requiredWatchPercent:90});
  const [tab,setTab]=React.useState<'curriculum'|'rules'|'assignments'|'preview'>('curriculum');
  const [saving,setSaving]=React.useState(false);
  const [message,setMessage]=React.useState('');
  React.useEffect(()=>{void(async()=>{const r=await fetch(`/api/learning/studio/courses/${courseId}`);const p=await r.json();if(!r.ok)return setMessage(p.message);setCourse(p.data.course);setRules({...rules,...p.data.rules});if(p.data.sections.length)setSections(p.data.sections.map((s:any)=>({title:s.title,lessons:s.lessons.map((l:any)=>({title:l.title,description:l.description||'',estimatedMinutes:l.estimated_minutes,minimumActiveSeconds:l.minimum_active_seconds,blocks:l.blocks.map((b:any)=>({type:b.type,title:b.title||'',required:b.required,content:b.content}))}))})));})()},[courseId]);
  const save=async(publish=false)=>{setSaving(true);setMessage('');const r=await fetch(`/api/learning/studio/courses/${courseId}`,{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({sections,rules,publish})});const p=await r.json();setSaving(false);setMessage(r.ok?(publish?'Course published. Existing enrollments remain on their assigned version.':'Draft version saved.'):p.message||'Unable to save');};
  const updateLesson=(si:number,li:number,patch:Partial<Lesson>)=>setSections(current=>current.map((s,i)=>i===si?{...s,lessons:s.lessons.map((l,j)=>j===li?{...l,...patch}:l)}:s));
  const updateBlock=(si:number,li:number,bi:number,patch:Partial<Block>)=>updateLesson(si,li,{blocks:sections[si].lessons[li].blocks.map((b,i)=>i===bi?{...b,...patch}:b)});
  return <main className="min-h-full text-slate-950 dark:text-zinc-50">
    <header className="sticky top-0 z-20 border-b border-slate-200 bg-white/95 px-4 py-3 backdrop-blur dark:border-zinc-800 dark:bg-zinc-950/95 sm:px-6 lg:px-8"><div className="mx-auto flex max-w-7xl flex-wrap items-center gap-3"><Link href="/learning/courses" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-slate-950 dark:text-zinc-300"><ArrowLeft className="h-4 w-4"/>Courses</Link><div className="min-w-[160px] flex-1 border-l border-slate-200 pl-3 dark:border-zinc-700"><p className="truncate text-sm font-bold">{String(course.title||'Course studio')}</p><p className="text-xs text-slate-500">Draft curriculum</p></div><div className="flex w-full items-center justify-end gap-2 sm:w-auto"><Button size="sm" variant="outline" asChild><Link href={`/learning/courses/${courseId}`}><Eye className="mr-2 h-4 w-4"/>Preview</Link></Button><Button size="sm" variant="outline" onClick={()=>void save()} disabled={saving}><Save className="mr-2 h-4 w-4"/>Save draft</Button><Button size="sm" onClick={()=>void save(true)} disabled={saving}><Send className="mr-2 h-4 w-4"/>Publish</Button></div></div></header>
    <div className="mx-auto grid max-w-7xl gap-6 px-4 py-6 sm:px-6 lg:grid-cols-[220px_minmax(0,1fr)] lg:px-8">
      <nav className="flex gap-1 overflow-x-auto rounded-[8px] border border-slate-200 bg-white p-1 shadow-sm dark:border-zinc-800 dark:bg-zinc-900/50 lg:block lg:space-y-1 lg:self-start">{(['curriculum','rules','assignments','preview'] as const).map(item=><button key={item} onClick={()=>setTab(item)} className={cn('shrink-0 rounded-[6px] px-4 py-2.5 text-left text-sm font-semibold capitalize lg:w-full',tab===item?'bg-indigo-50 text-indigo-700 dark:bg-indigo-500/20 dark:text-indigo-300':'text-slate-500 hover:bg-slate-50 dark:hover:bg-zinc-800')}>{item}</button>)}</nav>
      <div>{message&&<p role="status" className="mb-5 border border-slate-300 px-4 py-3 text-sm dark:border-zinc-700">{message}</p>}
      {tab==='curriculum'&&<section><div className="mb-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-indigo-700 dark:text-indigo-300">Course architecture</p><h1 className="mt-2 text-3xl font-bold tracking-[-.035em]">Build the syllabus</h1><p className="mt-2 text-sm text-slate-600 dark:text-zinc-300">Structure the learning journey, then add requirements inside each lesson.</p></div>
        <div className="space-y-10">{sections.map((section,si)=><div key={si}><div className="flex items-center gap-3 border-b border-slate-300 pb-3 dark:border-zinc-700"><span className="text-xs font-bold">{String(si+1).padStart(2,'0')}</span><Input value={section.title} onChange={e=>setSections(x=>x.map((s,i)=>i===si?{...s,title:e.target.value}:s))} className="border-0 bg-transparent text-lg font-bold shadow-none"/><Button variant="ghost" size="icon" onClick={()=>setSections(x=>x.filter((_,i)=>i!==si))}><Trash2 className="h-4 w-4"/></Button></div>
          <div className="ml-5 border-l border-slate-300 pl-5 dark:border-zinc-700">{section.lessons.map((lesson,li)=><details key={li} open className="group border-b border-slate-300 py-5 dark:border-zinc-700"><summary className="flex cursor-pointer list-none items-center gap-3"><GripVertical className="h-4 w-4 text-slate-400"/><span className="text-xs text-slate-500">{si+1}.{li+1}</span><span className="flex-1 font-bold">{lesson.title}</span><span className="text-xs text-slate-500">{lesson.blocks.length} blocks · {lesson.estimatedMinutes}m</span><ChevronDown className="h-4 w-4 group-open:rotate-180"/></summary>
            <div className="mt-5 space-y-5 pl-10"><div className="grid gap-4 sm:grid-cols-[1fr_140px]"><div><Label>Lesson title</Label><Input className="mt-2" value={lesson.title} onChange={e=>updateLesson(si,li,{title:e.target.value})}/></div><div><Label>Minutes</Label><Input className="mt-2" type="number" value={lesson.estimatedMinutes} onChange={e=>updateLesson(si,li,{estimatedMinutes:Number(e.target.value)})}/></div></div><div><Label>Description</Label><Textarea className="mt-2" value={lesson.description} onChange={e=>updateLesson(si,li,{description:e.target.value})}/></div>
              <div className="space-y-3">{lesson.blocks.map((block,bi)=><div key={bi} className="rounded-[8px] border border-slate-200 bg-white p-4 shadow-sm dark:border-zinc-700 dark:bg-zinc-900/50"><div className="flex items-center gap-3"><span className="text-xs font-bold uppercase tracking-wider text-indigo-700 dark:text-indigo-300">{block.type}</span><Input value={block.title} onChange={e=>updateBlock(si,li,bi,{title:e.target.value})} className="h-8 flex-1 border-0 bg-transparent font-semibold shadow-none"/><label className="text-xs"><input type="checkbox" checked={block.required} onChange={e=>updateBlock(si,li,bi,{required:e.target.checked})} className="mr-2"/>Required</label><Button variant="ghost" size="icon" onClick={()=>updateLesson(si,li,{blocks:lesson.blocks.filter((_,i)=>i!==bi)})}><Trash2 className="h-4 w-4"/></Button></div><BlockEditor block={block} onChange={content=>updateBlock(si,li,bi,{content})}/></div>)}</div>
              <div className="flex flex-wrap gap-2">{(['text','video','attachment','acknowledgement','break','quiz','assignment'] as BlockType[]).map(type=><Button key={type} size="sm" variant="outline" onClick={()=>updateLesson(si,li,{blocks:[...lesson.blocks,newBlock(type)]})}><Plus className="mr-1 h-3 w-3"/>{type}</Button>)}</div>
            </div></details>)}<Button variant="ghost" className="mt-3" onClick={()=>setSections(x=>x.map((s,i)=>i===si?{...s,lessons:[...s.lessons,newLesson()]}:s))}><Plus className="mr-2 h-4 w-4"/>Add lesson</Button></div></div>)}</div><Button variant="outline" className="mt-8" onClick={()=>setSections(x=>[...x,{title:'New section',lessons:[newLesson()]}])}><Plus className="mr-2 h-4 w-4"/>Add section</Button></section>}
      {tab==='rules'&&<section className="max-w-2xl"><h1 className="text-3xl font-bold">Completion rules</h1><p className="mt-2 text-sm text-slate-500">V1 courses always unlock sequentially.</p><div className="mt-8 grid gap-6 sm:grid-cols-3">{Object.entries(rules).map(([key,value])=><div key={key}><Label className="capitalize">{key.replace(/([A-Z])/g,' $1')}</Label><Input className="mt-2" type="number" value={value} onChange={e=>setRules(r=>({...r,[key]:Number(e.target.value)}))}/></div>)}</div></section>}
      {tab==='assignments'&&<section><h1 className="text-3xl font-bold">Assignments</h1><p className="mt-3 max-w-xl text-sm text-slate-500">Assign the published course from the existing Learning enrollments workspace. Employee, department, and role bulk assignment is ready for a follow-up release.</p><Button asChild className="mt-6"><Link href="/learning">Open enrollment workbench</Link></Button></section>}
      {tab==='preview'&&<section><h1 className="text-3xl font-bold">Employee preview</h1><p className="mt-3 text-sm text-slate-500">Preview uses the currently published version.</p><Button asChild className="mt-6"><Link href={`/learning/courses/${courseId}`}><Eye className="mr-2 h-4 w-4"/>Open course overview</Link></Button></section>}
      </div>
    </div>
  </main>;
}

function BlockEditor({block,onChange}:{block:Block;onChange:(content:Record<string,unknown>)=>void}) {
  if(block.type==='text')return <Textarea className="mt-3 min-h-28" value={String(block.content.text||'')} onChange={e=>onChange({...block.content,text:e.target.value})} placeholder="Write lesson content…"/>;
  if(block.type==='break')return <Input className="mt-3 max-w-32" type="number" value={Number(block.content.minutes||5)} onChange={e=>onChange({...block.content,minutes:Number(e.target.value)})}/>;
  if(block.type==='quiz')return <div className="mt-3"><p className="text-xs text-slate-500">Questions use prompt, options, and correct answer. Add a starter question and edit the generated JSON.</p><Textarea className="mt-2 min-h-28 font-mono text-xs" value={JSON.stringify(block.content.questions||[],null,2)} onChange={e=>{try{onChange({...block.content,questions:JSON.parse(e.target.value)})}catch{}}}/><Button size="sm" variant="outline" className="mt-2" onClick={()=>onChange({questions:[...((block.content.questions as any[])||[]),{id:crypto.randomUUID(),prompt:'New question',options:['True','False'],correctAnswer:'True'}]})}><FileQuestion className="mr-2 h-4 w-4"/>Add question</Button></div>;
  return <div className="mt-3 grid gap-3 sm:grid-cols-2"><Input value={String(block.content.url||'')} onChange={e=>onChange({...block.content,url:e.target.value})} placeholder={block.type==='assignment'?'Optional resource URL':'File or video URL'}/><Input value={String(block.content.instructions||block.content.description||'')} onChange={e=>onChange({...block.content,instructions:e.target.value,description:e.target.value})} placeholder="Instructions or description"/>{block.type==='video'&&<><Input type="number" value={Number(block.content.durationSeconds||0)} onChange={e=>onChange({...block.content,durationSeconds:Number(e.target.value)})} placeholder="Duration in seconds"/><Input type="number" value={Number(block.content.requiredWatchPercent||90)} onChange={e=>onChange({...block.content,requiredWatchPercent:Number(e.target.value)})} placeholder="Required watch %"/></>}</div>;
}
