"use client";

import * as React from "react";
import Link from "next/link";
import { ArrowLeft, BookOpen, Check, ChevronDown, Clock3, Eye, FileQuestion, GripVertical, LayoutList, Plus, Save, Send, Settings2, Trash2, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { cn } from "@/lib/utils";

type BlockType = "text"|"video"|"attachment"|"acknowledgement"|"break"|"quiz"|"assignment";
type Block = { type: BlockType; title: string; required: boolean; content: Record<string, unknown> };
type Lesson = { title:string; description:string; estimatedMinutes:number; minimumActiveSeconds:number; blocks:Block[] };
type Section = { title:string; lessons:Lesson[] };
type StudioTab = "curriculum"|"rules"|"assignments"|"preview";

const blockTypes:BlockType[]=["text","video","attachment","acknowledgement","break","quiz","assignment"];
const newBlock=(type:BlockType):Block=>({type,title:type==="text"?"Reading":type[0].toUpperCase()+type.slice(1),required:true,content:type==="text"?{text:""}:type==="break"?{minutes:5}:type==="quiz"?{questions:[]}:{url:"",instructions:""}});
const newLesson=():Lesson=>({title:"Untitled lesson",description:"",estimatedMinutes:5,minimumActiveSeconds:30,blocks:[newBlock("text")]});

export function CourseStudio({ courseId }: { courseId: string }) {
  const [course,setCourse]=React.useState<Record<string,unknown>>({});
  const [sections,setSections]=React.useState<Section[]>([{title:"Getting started",lessons:[newLesson()]}]);
  const [rules,setRules]=React.useState({passingScore:80,maxAttempts:3,requiredWatchPercent:90});
  const [tab,setTab]=React.useState<StudioTab>("curriculum");
  const [saving,setSaving]=React.useState(false);
  const [message,setMessage]=React.useState("");
  const [activeLesson,setActiveLesson]=React.useState({section:0,lesson:0});

  React.useEffect(()=>{void(async()=>{const r=await fetch(`/api/learning/studio/courses/${courseId}`);const p=await r.json();if(!r.ok)return setMessage(p.message);setCourse(p.data.course);setRules(current=>({...current,...p.data.rules}));if(p.data.sections.length)setSections(p.data.sections.map((s:any)=>({title:s.title,lessons:s.lessons.map((l:any)=>({title:l.title,description:l.description||"",estimatedMinutes:l.estimated_minutes,minimumActiveSeconds:l.minimum_active_seconds,blocks:l.blocks.map((b:any)=>({type:b.type,title:b.title||"",required:b.required,content:b.content}))}))})));})()},[courseId]);
  const save=async(publish=false)=>{setSaving(true);setMessage("");const r=await fetch(`/api/learning/studio/courses/${courseId}`,{method:"PUT",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({sections,rules,publish})});const p=await r.json();setSaving(false);setMessage(r.ok?(publish?"Course published. Existing enrollments remain on their assigned version.":"Draft version saved."):p.message||"Unable to save");};
  const updateLesson=(si:number,li:number,patch:Partial<Lesson>)=>setSections(current=>current.map((s,i)=>i===si?{...s,lessons:s.lessons.map((l,j)=>j===li?{...l,...patch}:l)}:s));
  const updateBlock=(si:number,li:number,bi:number,patch:Partial<Block>)=>updateLesson(si,li,{blocks:sections[si].lessons[li].blocks.map((b,i)=>i===bi?{...b,...patch}:b)});
  const lessonCount=sections.reduce((count,section)=>count+section.lessons.length,0);
  const totalMinutes=sections.reduce((count,section)=>count+section.lessons.reduce((sum,lesson)=>sum+lesson.estimatedMinutes,0),0);
  const navItems=[{id:"curriculum" as const,label:"Curriculum",icon:LayoutList},{id:"rules" as const,label:"Completion rules",icon:Settings2},{id:"assignments" as const,label:"Assignments",icon:Users},{id:"preview" as const,label:"Learner preview",icon:Eye}];
  const selectedLesson=sections[activeLesson.section]?.lessons[activeLesson.lesson]||sections[0]?.lessons[0];

  return <main className="min-h-full bg-[#f7f8fa] text-[#172033] dark:bg-[#10141d] dark:text-[#edf1f8]">
    <header className="sticky top-0 z-30 border-b border-[#dfe4de] bg-[#fbfcfa]/95 px-4 backdrop-blur-xl dark:border-white/10 dark:bg-[#151a16]/95 sm:px-6 lg:px-8"><div className="mx-auto flex min-h-16 max-w-[1500px] flex-wrap items-center gap-3 py-2">
      <Link href="/learning/courses" className="group inline-flex items-center gap-2 text-sm font-semibold text-[#66736b] hover:text-[#173f35] dark:text-[#aab5ad] dark:hover:text-white"><ArrowLeft className="h-4 w-4 transition-transform group-hover:-translate-x-0.5"/>Courses</Link><div className="h-5 w-px bg-[#d9ded9] dark:bg-white/10"/>
      <div className="min-w-[160px] flex-1"><div className="flex items-center gap-2"><p className="truncate text-sm font-semibold">{String(course.title||"Course studio")}</p><span className="rounded-full bg-[#e9eee9] px-2 py-0.5 text-[10px] font-bold uppercase tracking-[.12em] text-[#607067] dark:bg-white/10 dark:text-[#b9c4bc]">Draft</span></div><p className="text-xs text-[#7b877f]">{saving?"Saving your changes…":"Ready for your next edit"}</p></div>
      <div className="ml-auto flex items-center gap-2"><Button size="sm" variant="ghost" asChild className="hidden sm:inline-flex"><Link href={`/learning/courses/${courseId}`}><Eye className="mr-2 h-4 w-4"/>Preview</Link></Button><Button size="sm" variant="outline" onClick={()=>void save()} disabled={saving} className="border-[#cbd4e1] bg-transparent"><Save className="mr-2 h-4 w-4"/>Save</Button><Button size="sm" onClick={()=>void save(true)} disabled={saving} className="bg-[#102f55] px-4 text-white hover:bg-[#174373]"><Send className="mr-2 h-4 w-4"/>Publish</Button></div>
    </div></header>

    <div className="mx-auto max-w-[1500px]">
      <nav className="flex gap-7 overflow-x-auto border-b border-[#dfe4ea] bg-white px-4 dark:border-white/10 dark:bg-[#151a24] sm:px-8">{navItems.map(({id,label})=><button key={id} onClick={()=>setTab(id)} className={cn("relative shrink-0 py-3.5 text-sm font-semibold",tab===id?"text-[#174ea6] after:absolute after:inset-x-0 after:bottom-0 after:h-0.5 after:bg-[#2463c7]":"text-[#647085] hover:text-[#25334a]")}>{label}</button>)}</nav>
      <div className="min-w-0 px-4 py-6 sm:px-8">{message&&<div role="status" className="mb-5 flex items-center gap-3 rounded-md border border-[#cbd8cf] bg-[#edf5ef] px-4 py-3 text-sm text-[#28543f] dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-200"><Check className="h-4 w-4 shrink-0"/>{message}</div>}
        {tab==="curriculum"&&selectedLesson&&<section className="overflow-hidden rounded-lg border border-[#d9e0ea] bg-white dark:border-white/10 dark:bg-[#151a24]">
          <div className="grid min-h-[680px] xl:grid-cols-[280px_minmax(0,1fr)_250px]">
            <aside className="border-b border-[#d9e0ea] bg-[#fbfcfe] dark:border-white/10 dark:bg-[#121720] xl:border-b-0 xl:border-r"><div className="flex items-center justify-between border-b border-[#e3e8ef] px-4 py-3 dark:border-white/10"><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#657187]">Course outline</p><p className="mt-1 text-xs text-[#8290a5]">{lessonCount} lessons · {totalMinutes} min</p></div><Button size="sm" variant="ghost" onClick={()=>setSections(x=>[...x,{title:"New section",lessons:[newLesson()]}])}><Plus className="mr-1 h-3.5 w-3.5"/>Add</Button></div>
              <div className="max-h-[620px] overflow-y-auto p-3">{sections.map((section,si)=><div key={si} className="mb-5"><div className="flex items-center gap-2 px-2"><Input value={section.title} aria-label={`Section ${si+1} title`} onChange={e=>setSections(x=>x.map((s,i)=>i===si?{...s,title:e.target.value}:s))} className="h-8 border-0 bg-transparent px-0 text-xs font-bold shadow-none"/><span className="text-[10px] text-[#8b96a8]">{section.lessons.reduce((n,l)=>n+l.estimatedMinutes,0)}m</span></div><div className="mt-1 space-y-1">{section.lessons.map((lesson,li)=><button key={li} onClick={()=>setActiveLesson({section:si,lesson:li})} className={cn("flex w-full items-center gap-2 rounded-md px-2 py-2 text-left transition-colors",activeLesson.section===si&&activeLesson.lesson===li?"bg-[#e9f1ff] text-[#174ea6] dark:bg-blue-500/15 dark:text-blue-300":"hover:bg-[#f0f3f7]")}><GripVertical className="h-3.5 w-3.5 shrink-0 text-[#a0a9b8]"/><span className="w-7 text-[10px] font-bold">{si+1}.{li+1}</span><span className="min-w-0 flex-1 truncate text-xs font-medium">{lesson.title}</span><span className="text-[10px] text-[#8792a4]">{lesson.estimatedMinutes}m</span></button>)}</div><Button size="sm" variant="ghost" className="mt-1 h-7 text-xs text-[#2463c7]" onClick={()=>setSections(x=>x.map((s,i)=>i===si?{...s,lessons:[...s.lessons,newLesson()]}:s))}><Plus className="mr-1 h-3 w-3"/>Add lesson</Button></div>)}</div>
            </aside>

            <div className="min-w-0"><div className="flex items-center gap-3 border-b border-[#e3e8ef] px-5 py-3 dark:border-white/10"><span className="rounded bg-[#e9f1ff] px-2 py-1 text-[10px] font-bold text-[#174ea6]">Lesson {activeLesson.section+1}.{activeLesson.lesson+1}</span><p className="truncate text-sm font-semibold">{selectedLesson.title}</p><span className="ml-auto flex items-center gap-1 text-xs text-[#7b8799]"><Clock3 className="h-3.5 w-3.5"/>{selectedLesson.estimatedMinutes} min</span></div>
              <div className="border-b border-[#e3e8ef] px-5 dark:border-white/10"><button className="border-b-2 border-[#2463c7] py-3 text-xs font-bold text-[#174ea6]">Content</button><button className="ml-6 py-3 text-xs font-semibold text-[#7b8799]">Notes</button></div>
              <div className="max-h-[580px] space-y-6 overflow-y-auto p-5 sm:p-7"><div><Label>Lesson overview</Label><Textarea className="mt-2 min-h-28" value={selectedLesson.description} onChange={e=>updateLesson(activeLesson.section,activeLesson.lesson,{description:e.target.value})} placeholder="Explain what learners will take away from this lesson."/></div><div><div className="mb-3 flex items-center justify-between"><Label>Content blocks</Label><span className="text-xs text-[#7b8799]">{selectedLesson.blocks.length} blocks</span></div><div className="space-y-3">{selectedLesson.blocks.map((block,bi)=><div key={bi} className="border border-[#dce2eb] bg-[#fbfcfe] p-4 dark:border-white/10 dark:bg-[#111720]"><div className="flex flex-wrap items-center gap-3"><GripVertical className="h-4 w-4 text-[#9da7b6]"/><span className="grid h-7 w-7 place-items-center rounded bg-[#e9f1ff] text-[#2463c7]"><BookOpen className="h-3.5 w-3.5"/></span><span className="text-[10px] font-bold uppercase tracking-[.12em] text-[#2463c7]">{block.type}</span><Input value={block.title} onChange={e=>updateBlock(activeLesson.section,activeLesson.lesson,bi,{title:e.target.value})} className="h-8 min-w-40 flex-1 border-0 bg-transparent font-semibold shadow-none"/><Button variant="ghost" size="icon" aria-label="Delete block" onClick={()=>updateLesson(activeLesson.section,activeLesson.lesson,{blocks:selectedLesson.blocks.filter((_,i)=>i!==bi)})}><Trash2 className="h-4 w-4"/></Button></div><BlockEditor block={block} onChange={content=>updateBlock(activeLesson.section,activeLesson.lesson,bi,{content})}/></div>)}</div><div className="mt-3 flex flex-wrap gap-2">{blockTypes.map(type=><Button key={type} size="sm" variant="outline" className="capitalize" onClick={()=>updateLesson(activeLesson.section,activeLesson.lesson,{blocks:[...selectedLesson.blocks,newBlock(type)]})}><Plus className="mr-1 h-3 w-3"/>{type}</Button>)}</div></div></div>
            </div>

            <aside className="border-t border-[#d9e0ea] bg-[#fbfcfe] p-5 dark:border-white/10 dark:bg-[#121720] xl:border-l xl:border-t-0"><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#657187]">Lesson settings</p><div className="mt-5 space-y-5"><div><Label>Title</Label><Input className="mt-2" value={selectedLesson.title} onChange={e=>updateLesson(activeLesson.section,activeLesson.lesson,{title:e.target.value})}/></div><div><Label>Duration</Label><div className="mt-2 flex items-center gap-2"><Input type="number" value={selectedLesson.estimatedMinutes} onChange={e=>updateLesson(activeLesson.section,activeLesson.lesson,{estimatedMinutes:Number(e.target.value)})}/><span className="text-xs text-[#748095]">min</span></div></div><div><Label>Minimum active time</Label><div className="mt-2 flex items-center gap-2"><Input type="number" value={selectedLesson.minimumActiveSeconds} onChange={e=>updateLesson(activeLesson.section,activeLesson.lesson,{minimumActiveSeconds:Number(e.target.value)})}/><span className="text-xs text-[#748095]">sec</span></div></div><div className="border-t border-[#e0e5ed] pt-5 dark:border-white/10"><p className="text-xs font-semibold">Publishing status</p><div className="mt-3 space-y-2 text-xs"><p className="flex justify-between text-[#657187]"><span>Content</span><span className="font-semibold text-emerald-600">On track</span></p><p className="flex justify-between text-[#657187]"><span>Details</span><span className="font-semibold text-emerald-600">On track</span></p><p className="flex justify-between text-[#657187]"><span>Accessibility</span><span className="font-semibold text-amber-600">Review</span></p></div></div></div></aside>
          </div>
        </section>}
        {tab==="rules"&&<section className="mx-auto max-w-3xl"><PageHeading eyebrow="Course settings" title="Completion rules" description="Set the standards learners need to meet. Lessons unlock sequentially."/><div className="divide-y divide-[#d9ded9] border-y border-[#d9ded9] dark:divide-white/10 dark:border-white/10">{Object.entries(rules).map(([key,value])=><label key={key} className="flex items-center justify-between gap-6 py-5"><span><span className="block text-sm font-semibold capitalize">{key.replace(/([A-Z])/g," $1")}</span><span className="mt-1 block text-xs text-[#78847c]">{key==="passingScore"?"Minimum quiz score required to complete the course.":key==="maxAttempts"?"Number of attempts allowed for each assessment.":"Minimum percentage of each video that must be watched."}</span></span><Input className="w-24 text-right" type="number" value={value} onChange={e=>setRules(r=>({...r,[key]:Number(e.target.value)}))}/></label>)}</div></section>}
        {tab==="assignments"&&<EmptyStudioPanel icon={Users} eyebrow="Distribution" title="Put this course in front of the right people" description="Once published, assign it to employees from the Learning enrollment workbench. Department and role-based assignment will follow in a later release."><Button asChild className="bg-[#173f35] text-white hover:bg-[#245648]"><Link href="/learning">Open enrollment workbench</Link></Button></EmptyStudioPanel>}
        {tab==="preview"&&<EmptyStudioPanel icon={Eye} eyebrow="Learner experience" title="See the course through their eyes" description="Preview the currently published version, including its lesson order, progress states, and completion experience."><Button asChild className="bg-[#173f35] text-white hover:bg-[#245648]"><Link href={`/learning/courses/${courseId}`}><Eye className="mr-2 h-4 w-4"/>Open learner preview</Link></Button></EmptyStudioPanel>}
      </div>
    </div>
  </main>;
}

function PageHeading({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children?:React.ReactNode}) { return <div className="mb-10 flex flex-wrap items-end justify-between gap-5"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-[#b45f48]">{eyebrow}</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#66736b] dark:text-[#a9b4ac]">{description}</p></div>{children}</div>; }
function EmptyStudioPanel({icon:Icon,eyebrow,title,description,children}:{icon:React.ComponentType<{className?:string}>;eyebrow:string;title:string;description:string;children:React.ReactNode}) { return <section className="mx-auto max-w-3xl"><div className="border-y border-[#d8ded9] py-14 dark:border-white/10 sm:py-20"><Icon className="h-9 w-9 text-[#315f50] dark:text-[#b9cec1]"/><p className="mt-8 text-[11px] font-bold uppercase tracking-[.18em] text-[#b45f48]">{eyebrow}</p><h1 className="mt-3 max-w-2xl text-3xl font-semibold tracking-[-.04em] sm:text-4xl">{title}</h1><p className="mt-4 max-w-xl text-sm leading-6 text-[#66736b] dark:text-[#a9b4ac]">{description}</p><div className="mt-8">{children}</div></div></section>; }

function BlockEditor({block,onChange}:{block:Block;onChange:(content:Record<string,unknown>)=>void}) {
  if(block.type==="text")return <Textarea className="mt-3 min-h-28" value={String(block.content.text||"")} onChange={e=>onChange({...block.content,text:e.target.value})} placeholder="Write lesson content…"/>;
  if(block.type==="break")return <div className="mt-3"><Label>Break length (minutes)</Label><Input className="mt-2 max-w-32" type="number" value={Number(block.content.minutes||5)} onChange={e=>onChange({...block.content,minutes:Number(e.target.value)})}/></div>;
  if(block.type==="quiz")return <div className="mt-3"><p className="text-xs text-[#77837b]">Questions use a prompt, options, and correct answer.</p><Textarea className="mt-2 min-h-28 font-mono text-xs" value={JSON.stringify(block.content.questions||[],null,2)} onChange={e=>{try{onChange({...block.content,questions:JSON.parse(e.target.value)})}catch{}}}/><Button size="sm" variant="outline" className="mt-2 bg-transparent" onClick={()=>onChange({questions:[...((block.content.questions as any[])||[]),{id:crypto.randomUUID(),prompt:"New question",options:["True","False"],correctAnswer:"True"}]})}><FileQuestion className="mr-2 h-4 w-4"/>Add question</Button></div>;
  return <div className="mt-3 grid gap-3 sm:grid-cols-2"><Input value={String(block.content.url||"")} onChange={e=>onChange({...block.content,url:e.target.value})} placeholder={block.type==="assignment"?"Optional resource URL":"File or video URL"}/><Input value={String(block.content.instructions||block.content.description||"")} onChange={e=>onChange({...block.content,instructions:e.target.value,description:e.target.value})} placeholder="Instructions or description"/>{block.type==="video"&&<><Input type="number" value={Number(block.content.durationSeconds||0)} onChange={e=>onChange({...block.content,durationSeconds:Number(e.target.value)})} placeholder="Duration in seconds"/><Input type="number" value={Number(block.content.requiredWatchPercent||90)} onChange={e=>onChange({...block.content,requiredWatchPercent:Number(e.target.value)})} placeholder="Required watch %"/></>}</div>;
}
