import {
  DEFAULT_PRIMARY_GRADIENT_END,
  DEFAULT_PRIMARY_GRADIENT_START,
} from "./system-preference-defaults";

export const DEFAULT_SIDEBAR_COLORS_BASE = {
  sidebarBgStartL: "220 25% 97%",
  sidebarBgEndL: "220 20% 94%",
  sidebarTextL: "220 25% 30%",
  sidebarActiveBgStartL: DEFAULT_PRIMARY_GRADIENT_START,
  sidebarActiveBgEndL: DEFAULT_PRIMARY_GRADIENT_END,
  sidebarActiveTextL: "0 0% 100%",
  sidebarHoverBgL: "220 10% 92%",
  sidebarHoverTextL: "220 25% 25%",
  sidebarBorderL: "220 15% 85%",
  sidebarBgStartD: "220 15% 12%",
  sidebarBgEndD: "220 15% 9%",
  sidebarTextD: "210 30% 85%",
  sidebarActiveBgStartD: DEFAULT_PRIMARY_GRADIENT_START,
  sidebarActiveBgEndD: DEFAULT_PRIMARY_GRADIENT_END,
  sidebarActiveTextD: "0 0% 100%",
  sidebarHoverBgD: "220 15% 20%",
  sidebarHoverTextD: "210 30% 90%",
  sidebarBorderD: "220 15% 18%",
  buttonTextColorL: "0 0% 100%",
  buttonTextColorD: "0 0% 100%",
  sidebarFontFamilyL: "inherit",
  sidebarFontSizeL: "0.875rem",
  sidebarFontWeightL: "400",
  sidebarLineHeightL: "1.25rem",
  sidebarLetterSpacingL: "0",
  sidebarTextTransformL: "none",
  sidebarFontFamilyD: "inherit",
  sidebarFontSizeD: "0.875rem",
  sidebarFontWeightD: "400",
  sidebarLineHeightD: "1.25rem",
  sidebarLetterSpacingD: "0",
  sidebarTextTransformD: "none",
  sidebarBorderWidthL: "1px",
  sidebarBorderStyleL: "solid",
  sidebarBorderRadiusL: "0.5rem",
  sidebarShadowL: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
  sidebarShadowHoverL: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
  sidebarShadowActiveL: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
  sidebarBorderWidthD: "1px",
  sidebarBorderStyleD: "solid",
  sidebarBorderRadiusD: "0.5rem",
  sidebarShadowD: "0 1px 3px 0 rgb(0 0 0 / 0.3), 0 1px 2px -1px rgb(0 0 0 / 0.3)",
  sidebarShadowHoverD: "0 4px 6px -1px rgb(0 0 0 / 0.3), 0 2px 4px -2px rgb(0 0 0 / 0.3)",
  sidebarShadowActiveD: "0 10px 15px -3px rgb(0 0 0 / 0.3), 0 4px 6px -4px rgb(0 0 0 / 0.3)",
  sidebarPaddingXL: "0.75rem",
  sidebarPaddingYL: "0.5rem",
  sidebarMarginL: "0.25rem",
  sidebarGapL: "0.5rem",
  sidebarWidthL: "16rem",
  sidebarWidthCollapsedL: "3rem",
  sidebarTransitionDurationL: "0.2s",
  sidebarTransitionTimingL: "ease-in-out",
  sidebarItemSpacingL: "0.5rem",
  sidebarGroupSpacingL: "1rem",
  sidebarPaddingXD: "0.75rem",
  sidebarPaddingYD: "0.5rem",
  sidebarMarginD: "0.25rem",
  sidebarGapD: "0.5rem",
  sidebarWidthD: "16rem",
  sidebarWidthCollapsedD: "3rem",
  sidebarTransitionDurationD: "0.2s",
  sidebarTransitionTimingD: "ease-in-out",
  sidebarItemSpacingD: "0.5rem",
  sidebarGroupSpacingD: "1rem",
  sidebarMenuItemBgL: "transparent",
  sidebarMenuItemBgHoverL: "220 10% 92%",
  sidebarMenuItemBgActiveL: "179 67% 66%",
  sidebarMenuItemColorL: "220 25% 30%",
  sidebarMenuItemColorHoverL: "220 25% 25%",
  sidebarMenuItemColorActiveL: "0 0% 100%",
  sidebarMenuItemBorderL: "transparent",
  sidebarMenuItemBorderHoverL: "transparent",
  sidebarMenuItemBorderActiveL: "transparent",
  sidebarMenuItemBorderRadiusL: "0.375rem",
  sidebarMenuItemPaddingXL: "0.75rem",
  sidebarMenuItemPaddingYL: "0.5rem",
  sidebarMenuItemMarginL: "0.125rem",
  sidebarMenuItemFontWeightL: "400",
  sidebarMenuItemFontWeightActiveL: "600",
  sidebarMenuItemFontSizeL: "0.875rem",
  sidebarMenuItemLineHeightL: "1.25rem",
  sidebarMenuItemTransitionL: "all 0.2s ease-in-out",
  sidebarMenuItemBgD: "transparent",
  sidebarMenuItemBgHoverD: "220 15% 20%",
  sidebarMenuItemBgActiveD: "179 67% 66%",
  sidebarMenuItemColorD: "210 30% 85%",
  sidebarMenuItemColorHoverD: "210 30% 90%",
  sidebarMenuItemColorActiveD: "0 0% 100%",
  sidebarMenuItemBorderD: "transparent",
  sidebarMenuItemBorderHoverD: "transparent",
  sidebarMenuItemBorderActiveD: "transparent",
  sidebarMenuItemBorderRadiusD: "0.375rem",
  sidebarMenuItemPaddingXD: "0.75rem",
  sidebarMenuItemPaddingYD: "0.5rem",
  sidebarMenuItemMarginD: "0.125rem",
  sidebarMenuItemFontWeightD: "400",
  sidebarMenuItemFontWeightActiveD: "600",
  sidebarMenuItemFontSizeD: "0.875rem",
  sidebarMenuItemLineHeightD: "1.25rem",
  sidebarMenuItemTransitionD: "all 0.2s ease-in-out",
  sidebarIconSizeL: "1.25rem",
  sidebarIconColorL: "220 25% 30%",
  sidebarIconColorHoverL: "220 25% 25%",
  sidebarIconColorActiveL: "0 0% 100%",
  sidebarIconMarginRightL: "0.75rem",
  sidebarIconTransitionL: "color 0.2s ease-in-out",
  sidebarIconSizeD: "1.25rem",
  sidebarIconColorD: "210 30% 85%",
  sidebarIconColorHoverD: "210 30% 90%",
  sidebarIconColorActiveD: "0 0% 100%",
  sidebarIconMarginRightD: "0.75rem",
  sidebarIconTransitionD: "color 0.2s ease-in-out",
  sidebarGroupLabelColorL: "220 25% 40%",
  sidebarGroupLabelFontSizeL: "0.75rem",
  sidebarGroupLabelFontWeightL: "600",
  sidebarGroupLabelTextTransformL: "uppercase",
  sidebarGroupLabelLetterSpacingL: "0.05em",
  sidebarGroupLabelPaddingL: "0.5rem 0.75rem",
  sidebarGroupLabelMarginL: "1rem 0 0.5rem 0",
  sidebarGroupLabelColorD: "210 30% 70%",
  sidebarGroupLabelFontSizeD: "0.75rem",
  sidebarGroupLabelFontWeightD: "600",
  sidebarGroupLabelTextTransformD: "uppercase",
  sidebarGroupLabelLetterSpacingD: "0.05em",
  sidebarGroupLabelPaddingD: "0.5rem 0.75rem",
  sidebarGroupLabelMarginD: "1rem 0 0.5rem 0",
} satisfies SidebarColors;

export const SIDEBAR_COLOR_KEYS = [
  "sidebarBgStartL",
  "sidebarBgEndL",
  "sidebarTextL",
  "sidebarActiveBgStartL",
  "sidebarActiveBgEndL",
  "sidebarActiveTextL",
  "sidebarHoverBgL",
  "sidebarHoverTextL",
  "sidebarBorderL",
  "sidebarBgStartD",
  "sidebarBgEndD",
  "sidebarTextD",
  "sidebarActiveBgStartD",
  "sidebarActiveBgEndD",
  "sidebarActiveTextD",
  "sidebarHoverBgD",
  "sidebarHoverTextD",
  "sidebarBorderD",
  "buttonTextColorL",
  "buttonTextColorD",
  "sidebarFontFamilyL",
  "sidebarFontSizeL",
  "sidebarFontWeightL",
  "sidebarLineHeightL",
  "sidebarLetterSpacingL",
  "sidebarTextTransformL",
  "sidebarFontFamilyD",
  "sidebarFontSizeD",
  "sidebarFontWeightD",
  "sidebarLineHeightD",
  "sidebarLetterSpacingD",
  "sidebarTextTransformD",
  "sidebarBorderWidthL",
  "sidebarBorderStyleL",
  "sidebarBorderRadiusL",
  "sidebarShadowL",
  "sidebarShadowHoverL",
  "sidebarShadowActiveL",
  "sidebarBorderWidthD",
  "sidebarBorderStyleD",
  "sidebarBorderRadiusD",
  "sidebarShadowD",
  "sidebarShadowHoverD",
  "sidebarShadowActiveD",
  "sidebarPaddingXL",
  "sidebarPaddingYL",
  "sidebarMarginL",
  "sidebarGapL",
  "sidebarWidthL",
  "sidebarWidthCollapsedL",
  "sidebarTransitionDurationL",
  "sidebarTransitionTimingL",
  "sidebarItemSpacingL",
  "sidebarGroupSpacingL",
  "sidebarIconSizeL",
  "sidebarPaddingXD",
  "sidebarPaddingYD",
  "sidebarMarginD",
  "sidebarGapD",
  "sidebarWidthD",
  "sidebarWidthCollapsedD",
  "sidebarTransitionDurationD",
  "sidebarTransitionTimingD",
  "sidebarItemSpacingD",
  "sidebarGroupSpacingD",
  "sidebarIconSizeD",
  "sidebarMenuItemBgL",
  "sidebarMenuItemBgHoverL",
  "sidebarMenuItemBgActiveL",
  "sidebarMenuItemColorL",
  "sidebarMenuItemColorHoverL",
  "sidebarMenuItemColorActiveL",
  "sidebarMenuItemBorderL",
  "sidebarMenuItemBorderHoverL",
  "sidebarMenuItemBorderActiveL",
  "sidebarMenuItemBorderRadiusL",
  "sidebarMenuItemPaddingXL",
  "sidebarMenuItemPaddingYL",
  "sidebarMenuItemMarginL",
  "sidebarMenuItemFontWeightL",
  "sidebarMenuItemFontWeightActiveL",
  "sidebarMenuItemFontSizeL",
  "sidebarMenuItemLineHeightL",
  "sidebarMenuItemTransitionL",
  "sidebarMenuItemBgD",
  "sidebarMenuItemBgHoverD",
  "sidebarMenuItemBgActiveD",
  "sidebarMenuItemColorD",
  "sidebarMenuItemColorHoverD",
  "sidebarMenuItemColorActiveD",
  "sidebarMenuItemBorderD",
  "sidebarMenuItemBorderHoverD",
  "sidebarMenuItemBorderActiveD",
  "sidebarMenuItemBorderRadiusD",
  "sidebarMenuItemPaddingXD",
  "sidebarMenuItemPaddingYD",
  "sidebarMenuItemMarginD",
  "sidebarMenuItemFontWeightD",
  "sidebarMenuItemFontWeightActiveD",
  "sidebarMenuItemFontSizeD",
  "sidebarMenuItemLineHeightD",
  "sidebarMenuItemTransitionD",
  "sidebarIconColorL",
  "sidebarIconColorHoverL",
  "sidebarIconColorActiveL",
  "sidebarIconMarginRightL",
  "sidebarIconTransitionL",
  "sidebarIconColorD",
  "sidebarIconColorHoverD",
  "sidebarIconColorActiveD",
  "sidebarIconMarginRightD",
  "sidebarIconTransitionD",
  "sidebarGroupLabelColorL",
  "sidebarGroupLabelFontSizeL",
  "sidebarGroupLabelFontWeightL",
  "sidebarGroupLabelTextTransformL",
  "sidebarGroupLabelLetterSpacingL",
  "sidebarGroupLabelPaddingL",
  "sidebarGroupLabelMarginL",
  "sidebarGroupLabelColorD",
  "sidebarGroupLabelFontSizeD",
  "sidebarGroupLabelFontWeightD",
  "sidebarGroupLabelTextTransformD",
  "sidebarGroupLabelLetterSpacingD",
  "sidebarGroupLabelPaddingD",
  "sidebarGroupLabelMarginD",
] as const;

export type SidebarColorKey = typeof SIDEBAR_COLOR_KEYS[number];
export type SidebarColors = Record<SidebarColorKey, string> & Record<string, string>;

export function createInitialSidebarColors(): SidebarColors {
  return { ...DEFAULT_SIDEBAR_COLORS_BASE };
}
