import type {
  EvaluateHeaderBackgroundType,
  HeaderBackgroundType,
  LoginBackgroundType,
  SplashAnimationType,
} from "./system-preference-keys";

export const DEFAULT_PRIMARY_GRADIENT_START = "220 78% 28%";
export const DEFAULT_PRIMARY_GRADIENT_END = "222 72% 36%";

export const DEFAULT_SPLASH_ANIMATION_TYPE: SplashAnimationType = "spinner";
export const DEFAULT_SPLASH_BACKGROUND_COLOR = "#ffffff";

export const DEFAULT_DRAWER_STYLE = "classic";

export const DEFAULT_LOGIN_BACKGROUND_TYPE: LoginBackgroundType = "gradient";
export const DEFAULT_LOGIN_BACKGROUND_GRADIENT_START = DEFAULT_PRIMARY_GRADIENT_START;
export const DEFAULT_LOGIN_BACKGROUND_GRADIENT_END = DEFAULT_PRIMARY_GRADIENT_END;
export const DEFAULT_LOGIN_BACKGROUND_COLOR = "220 25% 97%";
export const DEFAULT_LOGIN_PAGE_LOGO_SIZE = 100;
export const DEFAULT_LOGIN_BACKGROUND_TYPE_MOBILE = DEFAULT_LOGIN_BACKGROUND_TYPE;

export const DEFAULT_EVALUATE_HEADER_BACKGROUND_TYPE: EvaluateHeaderBackgroundType = "gradient";
export const DEFAULT_EVALUATE_HEADER_BACKGROUND_GRADIENT_START = DEFAULT_PRIMARY_GRADIENT_START;
export const DEFAULT_EVALUATE_HEADER_BACKGROUND_GRADIENT_END = DEFAULT_PRIMARY_GRADIENT_END;
export const DEFAULT_EVALUATE_HEADER_BACKGROUND_COLOR = "220 25% 97%";
export const DEFAULT_EVALUATE_HEADER_TEXT_COLOR = "0 0% 0%";

export const DEFAULT_HEADER_BACKGROUND_TYPE: HeaderBackgroundType = "solid";
export const DEFAULT_HEADER_BACKGROUND_COLOR = "0 0% 100%";
export const DEFAULT_HEADER_TEXT_COLOR = "240 10% 3.9%";

export const DEFAULT_SIDEBAR_BACKGROUND_BLUR_PERCENT = 0;
export const DEFAULT_SIDEBAR_BACKGROUND_TRANSLUCENCY_PERCENT = 0;

export const DEFAULT_INTERVIEWER_SELECTED_BG_COLOR = "220 25% 97%";
export const DEFAULT_INTERVIEWER_SELECTED_TEXT_COLOR = "0 0% 0%";
export const DEFAULT_INTERVIEWER_SELECTED_BORDER_COLOR = "220 15% 50%";
export const DEFAULT_INTERVIEWER_SELECTED_BORDER_WIDTH = "2px";
export const DEFAULT_INTERVIEWER_NON_SELECTED_BG_COLOR = "220 25% 97%";
export const DEFAULT_INTERVIEWER_NON_SELECTED_TEXT_COLOR = "220 25% 50%";
export const DEFAULT_INTERVIEWER_NON_SELECTED_BORDER_COLOR = "220 15% 85%";
export const DEFAULT_INTERVIEWER_NON_SELECTED_BORDER_WIDTH = "1px";
export const DEFAULT_INTERVIEWER_NAME_COLOR = "220 25% 30%";
