"use client";

import { EvaluationWaitingMobilePage } from "./components/EvaluationWaitingMobilePage";
import type { LoadedEvaluationPageViewProps } from "./evaluation-page-view-types";

export function EvaluationSelectionMobileBranch({
  allEvaluations,
  applicantData,
  applicantId,
  appLogoUrl,
  attachments,
  canEditScores,
  evaluateHeaderBackgroundColor,
  evaluateHeaderBackgroundGradient,
  evaluateHeaderBackgroundImage,
  evaluateHeaderBackgroundType,
  evaluateHeaderStyle,
  evaluateHeaderTextColor,
  evaluationLinkRequireLogin,
  existingEvaluation,
  fileViewerOpen,
  formData,
  hasToken,
  interviewerNameColor,
  interviewerNonSelectedBgColor,
  interviewerNonSelectedBorderColor,
  interviewerNonSelectedBorderWidth,
  interviewerNonSelectedTextColor,
  interviewerSelectedBgColor,
  interviewerSelectedBorderColor,
  interviewerSelectedBorderWidth,
  interviewerSelectedTextColor,
  interviewers,
  isMobile,
  onBackToInterview,
  onCloseRemark,
  onFileSelect,
  onFileViewerOpenChange,
  onInterviewerSelect,
  onOpenReportInNewPage,
  onRemarkChange,
  onReportClick,
  onReportDrawerOpenChange,
  onStartMobileEvaluation,
  onTestingResultScoreChange,
  onTestingResultsBlur,
  onTraitClick,
  personalityGroupsConfig,
  remarkSaved,
  remarkSectionVisible,
  remarkText,
  reportDrawerOpen,
  savingRemark,
  searchParams,
  selectedFile,
  selectedInterviewerId,
  status,
  testingResults,
  testingResultsRef,
}: LoadedEvaluationPageViewProps) {
  return (
    <EvaluationWaitingMobilePage
      evaluateHeaderStyle={evaluateHeaderStyle}
      formData={formData}
      appLogoUrl={appLogoUrl}
      evaluateHeaderTextColor={evaluateHeaderTextColor}
      onBack={onBackToInterview}
      attachments={attachments}
      applicantId={applicantId}
      onFileSelect={onFileSelect}
      testingResults={testingResults}
      canEditScores={canEditScores}
      onTestingResultScoreChange={onTestingResultScoreChange}
      onTestingResultsBlur={onTestingResultsBlur}
      testingResultsRef={testingResultsRef}
      interviewers={interviewers}
      selectedInterviewerId={selectedInterviewerId}
      allEvaluations={allEvaluations}
      hasToken={hasToken}
      evaluationLinkRequireLogin={evaluationLinkRequireLogin}
      status={status}
      applicantData={applicantData}
      interviewerSelectedBgColor={interviewerSelectedBgColor}
      interviewerSelectedTextColor={interviewerSelectedTextColor}
      interviewerSelectedBorderColor={interviewerSelectedBorderColor}
      interviewerSelectedBorderWidth={interviewerSelectedBorderWidth}
      interviewerNonSelectedBgColor={interviewerNonSelectedBgColor}
      interviewerNonSelectedTextColor={interviewerNonSelectedTextColor}
      interviewerNonSelectedBorderColor={interviewerNonSelectedBorderColor}
      interviewerNonSelectedBorderWidth={interviewerNonSelectedBorderWidth}
      onInterviewerSelect={onInterviewerSelect}
      existingEvaluation={existingEvaluation}
      interviewerNameColor={interviewerNameColor}
      onStartEvaluation={onStartMobileEvaluation}
      personalityGroupsConfig={personalityGroupsConfig}
      searchParams={searchParams}
      onTraitClick={onTraitClick}
      remarkSectionVisible={remarkSectionVisible}
      remarkText={remarkText}
      savingRemark={savingRemark}
      remarkSaved={remarkSaved}
      onRemarkChange={onRemarkChange}
      onReportClick={onReportClick}
      onCloseRemark={onCloseRemark}
      evaluateHeaderBackgroundType={evaluateHeaderBackgroundType}
      evaluateHeaderBackgroundImage={evaluateHeaderBackgroundImage}
      evaluateHeaderBackgroundGradient={evaluateHeaderBackgroundGradient}
      evaluateHeaderBackgroundColor={evaluateHeaderBackgroundColor}
      fileViewerOpen={fileViewerOpen}
      selectedFile={selectedFile}
      onFileViewerOpenChange={onFileViewerOpenChange}
      isMobile={isMobile}
      reportDrawerOpen={reportDrawerOpen}
      onReportDrawerOpenChange={onReportDrawerOpenChange}
      onOpenReportInNewPage={onOpenReportInNewPage}
    />
  );
}
