import type { PlatformModuleId } from '@/lib/types';

export const adminCenterTabs = [
  'HR Setup',
  'Roles & Permissions',
  'Branding',
  'Field Management',
  'Communication',
  'AI',
  'Security',
  'Billing',
  'App API',
  'Logs & Monitoring',
] as const;

export type AdminCenterTab = (typeof adminCenterTabs)[number];

export const adminCenterTabSlugs: Record<AdminCenterTab, string> = {
  'HR Setup': 'hr-setup',
  'Roles & Permissions': 'roles-permissions',
  Branding: 'branding',
  'Field Management': 'field-management',
  Communication: 'communication',
  AI: 'ai',
  Security: 'security',
  Billing: 'billing',
  'App API': 'app-api',
  'Logs & Monitoring': 'logs-monitoring',
};

export function getAdminCenterTabFromSlug(slug: string | null): AdminCenterTab {
  // Keep bookmarked links to the former standalone category working.
  if (slug === 'feature-flags') return 'Security';

  return adminCenterTabs.find(tab => adminCenterTabSlugs[tab] === slug) || 'HR Setup';
}

export interface SettingsPageItem {
  href: string;
  label: string;
  description: string;
  tab: AdminCenterTab;
  section: string;
  value?: string;
  permissionId?: PlatformModuleId;
  permissionIds?: PlatformModuleId[];
  adminOnly?: boolean;
  adminOnlyOrPermission?: boolean;
  hidden?: boolean;
}

export const settingsItems: SettingsPageItem[] = [
  {
    href: '/settings/system-settings?tab=organize',
    label: 'Company Info',
    description: 'Legal details, address, contacts, and the employee email domain.',
    tab: 'HR Setup',
    section: 'Organization',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/people/department',
    label: 'Department',
    description: 'Define and manage organization divisions, departments, and sections.',
    tab: 'HR Setup',
    section: 'Organization',
    value: 'Manage',
  },
  {
    href: '/positions',
    label: 'Designation',
    description: 'Configure job titles and designations used across the platform.',
    tab: 'HR Setup',
    section: 'Organization',
    value: 'Manage',
  },
  {
    href: '/settings/branches',
    label: 'Branch',
    description: 'Set up office branches and work locations.',
    tab: 'HR Setup',
    section: 'Organization',
    value: 'Manage',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/financial-dimensions',
    label: 'Cost Centers & Projects',
    description: 'Govern the financial dimensions used by time, expenses, payroll, reporting, and integrations.',
    tab: 'HR Setup',
    section: 'Organization',
    value: 'Manage',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/leave-policies',
    label: 'Leave Policies',
    description: 'Define leave allowances, approval rules, and policies used for employee allocations.',
    tab: 'HR Setup',
    section: 'Organization',
    value: 'Manage',
    permissionIds: ['HR_WORKFORCE_VIEW', 'HR_WORKFORCE_MANAGE'],
    adminOnlyOrPermission: true,
  },
  {
    href: '/policy-documents',
    label: 'Policy Documents',
    description: 'Create, govern, and publish company policy documents.',
    tab: 'HR Setup',
    section: 'Documents',
    value: 'Manage',
  },
  {
    href: '/settings/onboarding',
    label: 'Onboarding Checklist',
    description: 'Configure onboarding templates, owners, and checklist steps.',
    tab: 'HR Setup',
    section: 'People Configuration',
    value: 'Configure',
    permissionId: 'HR_PEOPLE_MANAGE',
  },
  {
    href: '/settings/service-desk',
    label: 'Service Desk Categories',
    description: 'Configure employee support categories and assign one or more HR owners to each.',
    tab: 'HR Setup',
    section: 'People Configuration',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/company-references',
    label: 'Company References',
    description: 'Manage the company list used across HR and load shared company data from AppKit.',
    tab: 'HR Setup',
    section: 'Organization',
    value: 'Manage',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/platform-defaults',
    label: 'Platform Defaults',
    description: 'Load and manage the default platform configuration shared across HR workflows.',
    tab: 'HR Setup',
    section: 'Organization',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/learning-categories',
    label: 'Course Categories',
    description: 'Build the category hierarchy used when organizing employee learning courses.',
    tab: 'HR Setup',
    section: 'Learning Configuration',
    value: 'Manage',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/headcount-types',
    label: 'Headcount Types',
    description: 'Define the headcount categories available when planning and creating positions.',
    tab: 'HR Setup',
    section: 'Position Configuration',
    value: 'Manage',
  },
  {
    href: '/settings/headcount-approval-paths',
    label: 'Headcount Approval Paths',
    description: 'Configure default and specialized approval sequences for headcount requests.',
    tab: 'HR Setup',
    section: 'Position Configuration',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/headcount-approval-paths',
    label: 'Headcount Approval Paths',
    description: 'Configure default and specialized approval sequences for headcount requests.',
    tab: 'HR Setup',
    section: 'Position Configuration',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/dropdown-options',
    label: 'Dropdown Options',
    description: 'Manage shared business vocabulary used by dropdowns across HR workflows.',
    tab: 'HR Setup',
    section: 'Organization',
    value: 'Manage',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/grades',
    label: 'Grades',
    description: 'Configure the employee and position grades used across the organization.',
    tab: 'HR Setup',
    section: 'Position Configuration',
    value: 'Manage',
  },
  {
    href: '/settings/position-levels',
    label: 'Position Levels',
    description: 'Maintain the position levels used to structure roles and progression.',
    tab: 'HR Setup',
    section: 'Position Configuration',
    value: 'Manage',
  },
  {
    href: '/settings/system-settings?tab=auto-close',
    label: 'Position Auto-Close',
    description: 'Configure automatic closing rules for filled or expired positions.',
    tab: 'HR Setup',
    section: 'Recruitment Automation',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/stages',
    label: 'Recruitment Stages',
    description: 'Configure the stages used in applicant hiring workflows.',
    tab: 'HR Setup',
    section: 'Recruitment Configuration',
    value: 'Manage',
    permissionId: 'RECRUITMENT_STAGES_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/applicant-sources',
    label: 'Applicant Sources',
    description: 'Define and organize applicant sourcing channels.',
    tab: 'HR Setup',
    section: 'Recruitment Configuration',
    value: 'Manage',
    permissionId: 'RECRUITMENT_STAGES_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/evaluation-configuration',
    label: 'Evaluation Configuration',
    description: 'Configure evaluation modules, expertise, and assessment fields.',
    tab: 'HR Setup',
    section: 'Recruitment Configuration',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/users',
    label: 'Active Users',
    description: 'View and manage all platform user accounts.',
    tab: 'Roles & Permissions',
    section: 'Users',
    value: 'Manage',
    permissionId: 'USERS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/user-groups',
    label: 'Employee Account Role',
    description: 'New employee platform accounts receive the least-privilege Employee role.',
    tab: 'Roles & Permissions',
    section: 'Users',
    value: 'Employee',
    permissionId: 'USERS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-preferences?tab=branding',
    label: 'Branding',
    description: 'Configure login branding, application logos, headers, and splash screens.',
    tab: 'Branding',
    section: 'Branding & Theme',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-preferences?tab=general',
    label: 'General Preferences',
    description: 'Set the application name, default theme, and general presentation preferences.',
    tab: 'Branding',
    section: 'Branding & Theme',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-preferences?tab=appearance',
    label: 'Appearance',
    description: 'Configure application colors, surfaces, buttons, and visual styling.',
    tab: 'Branding',
    section: 'Branding & Theme',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-preferences?tab=sidebar',
    label: 'Sidebar Theme',
    description: 'Customize sidebar colors, gradients, text, and active states.',
    tab: 'Branding',
    section: 'Branding & Theme',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-preferences?tab=evaluate',
    label: 'Evaluation Theme',
    description: 'Customize the colors and presentation used in evaluation experiences.',
    tab: 'Branding',
    section: 'Branding & Theme',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/localization',
    label: 'Localization',
    description: 'Load language configuration and translations from AppKit.',
    tab: 'Branding',
    section: 'Language & Region',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/field-management',
    label: 'Field Management',
    description: 'Browse every platform data model and manage dynamic fields.',
    tab: 'Field Management',
    section: 'Data Models',
    value: 'Manage',
    permissionId: 'CUSTOM_FIELDS_EDIT',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-settings?tab=email-server',
    label: 'Notification Settings',
    description: 'Configure the delivery channel and sender identity used by workspace notifications.',
    tab: 'Communication',
    section: 'Notifications',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-settings?tab=broadcast-banner',
    label: 'Broadcast Channels',
    description: 'Configure broadcast email, SMS providers, and in-app announcement bars.',
    tab: 'Communication',
    section: 'Broadcast',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-settings?tab=email-server',
    label: 'Email Server',
    description: 'Configure SMTP delivery, sender identity, and secure connection settings.',
    tab: 'Communication',
    section: 'Email',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-settings?tab=email-templates',
    label: 'Email Templates',
    description: 'Manage interview invitation content and calendar event templates.',
    tab: 'Communication',
    section: 'Email',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/webhooks',
    label: 'Webhooks',
    description: 'Create and manage outgoing event notifications.',
    tab: 'Communication',
    section: 'Integrations',
    value: 'Manage',
    permissionId: 'WEBHOOKS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/rooms',
    label: 'Meeting Rooms',
    description: 'Manage integrated interview rooms and calendar resources.',
    tab: 'Communication',
    section: 'Calendar',
    value: 'Manage',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-prompts',
    label: 'AI Prompt Library',
    description: 'Manage reusable AI prompt templates and categories.',
    tab: 'AI',
    section: 'AI Configuration',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-settings?tab=processing',
    label: 'AI Processing',
    description: 'Configure resume processors, queue concurrency, timeouts, and webhooks.',
    tab: 'AI',
    section: 'Processing',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-settings?tab=match-criteria',
    label: 'Match Criteria',
    description: 'Set default matching behavior for positions and applicants.',
    tab: 'AI',
    section: 'Matching',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-settings?tab=ai-search',
    label: 'AI Search',
    description: 'Configure AI-powered search behavior and availability.',
    tab: 'AI',
    section: 'AI Services',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-settings?tab=knowledge-base',
    label: 'Knowledge Base',
    description: 'Configure Qdrant connection settings for service desk knowledge indexing and retrieval.',
    tab: 'AI',
    section: 'AI Services',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-settings?tab=ai-api-keys',
    label: 'AI API Keys',
    description: 'Manage provider credentials and model access for AI services.',
    tab: 'AI',
    section: 'AI Services',
    value: 'Manage',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-settings?tab=ai-prompts',
    label: 'AI Processing Prompts',
    description: 'Configure job-description and applicant-evaluation system prompts.',
    tab: 'AI',
    section: 'AI Configuration',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-settings?tab=digital-footprint',
    label: 'Digital Footprint Screening',
    description: 'Configure consent-gated public-source screening, optional AI, quotas, and retention.',
    tab: 'AI',
    section: 'AI Services',
    value: 'Configure',
    permissionId: 'SCREENING_SETTINGS_MANAGE',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-settings?tab=login-methods',
    label: 'Login Methods',
    description: 'Choose which sign-in methods employees can use on the default login page.',
    tab: 'Security',
    section: 'Authentication Features',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-settings?tab=azure',
    label: 'Azure Integration',
    description: 'Configure Azure tenant credentials and connected Microsoft services.',
    tab: 'Security',
    section: 'Authentication Features',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-settings?tab=domain-verification',
    label: 'Domain Verification',
    description: 'Configure the organization email domain used for employee identities and sign-in.',
    tab: 'Security',
    section: 'Authentication Features',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-settings?tab=security',
    label: 'Security Controls',
    description: 'Configure session, access, and platform security controls.',
    tab: 'Security',
    section: 'Access Security',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/security-logs',
    label: 'Security Logs',
    description: 'Review authentication and access security events.',
    tab: 'Security',
    section: 'Audit',
    value: 'View',
    permissionId: 'LOGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-settings?tab=features',
    label: 'Feature Flags',
    description: 'Enable or disable controlled platform capabilities.',
    tab: 'Security',
    section: 'Platform Features',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-settings?tab=pwa',
    label: 'PWA Settings',
    description: 'Configure installable app names, colors, and mobile presentation.',
    tab: 'Security',
    section: 'Platform Features',
    value: 'Configure',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings',
    label: 'Billing',
    description: 'Manage subscription, invoices, billing contacts, and payment settings.',
    tab: 'Billing',
    section: 'Subscription',
    value: 'Unavailable',
    hidden: true,
  },
  {
    href: '/settings/api-docs',
    label: 'API Documentation',
    description: 'View the application API reference and endpoint documentation.',
    tab: 'App API',
    section: 'Application API',
    value: 'Open',
  },
  {
    href: '/settings/system-settings?tab=system-api-keys',
    label: 'API Keys',
    description: 'Create and manage credentials for connected applications.',
    tab: 'App API',
    section: 'Application API',
    value: 'Manage',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnly: true,
  },
  {
    href: '/settings/logs',
    label: 'Application Logs',
    description: 'Review system activity and operational events.',
    tab: 'Logs & Monitoring',
    section: 'System Logs',
    value: 'View',
    permissionId: 'LOGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/settings/system-settings?tab=monitoring',
    label: 'System Monitoring',
    description: 'Monitor platform health, service status, and background processing.',
    tab: 'Logs & Monitoring',
    section: 'Monitoring',
    value: 'View',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
  {
    href: '/system-status',
    label: 'System Status',
    description: 'Check application services and connected infrastructure.',
    tab: 'Logs & Monitoring',
    section: 'Monitoring',
    value: 'View',
    permissionId: 'SYSTEM_SETTINGS_VIEW',
    adminOnlyOrPermission: true,
  },
];
